### ISSUE TITLE
封装请求+线程池，没有额外的扩展，如自定义数据库+离线缓存列表展示，通知更新

### ISSUE THREAD

**Issue by qsw-net** [liujingxing/RxHttp#10]

**Comment by liujingxing** [comment]
感谢提问。线程池默认使用RxJava的，如果需要自定义，可通过RxJavaPlugins相关方法去实现；`自定义数据库+离线缓存列表展示，通知更新`  这个话能说一下您的具体场景吗？  欢迎加群交流 378530627

**Comment by liujingxing** [comment]
缓存功能1.3.5版本已加入，详情请查看：https://github.com/liujingxing/RxHttp/wiki/%E7%BC%93%E5%AD%98%E7%AD%96%E7%95%A5
