### ISSUE TITLE
上传，下載可以返回自定义的对象吗

### ISSUE THREAD

**Issue by CaiJingFu** [liujingxing/RxHttp#12]
上传的时候，后台返回的是一个json对象，支持返回自定义对象吗

**Comment by liujingxing** [comment]
上传可以，下载不支持。

**Comment by liujingxing** [comment]
如：uploadProgress(Parser<T> parser)

**Comment by CaiJingFu** [comment]
加入自己的项目中，报这个错误
More than one file was found with OS independent path 'META-INF/proguard/androidx-annotations.pro'

**Comment by liujingxing** [comment]
你开启了AndroidX，RxLife库AndroidX版本，应该就ok了

**Comment by CaiJingFu** [comment]
我没有开启AndroidX，之前是依赖这个
`implementation 'com.rxjava.rxhttp:rxhttp:1.0.5'
       //注解处理器，生成RxHttp类，即可一条链发送请求
       annotationProcessor 'com.rxjava.rxhttp:rxhttp-compiler:1.0.5'
       //管理RxJava及生命周期，Activity/Fragment 销毁，自动关闭未完成的请求
       implementation 'com.rxjava.rxlife:rxlife:1.0.5'`
现在改成
`implementation 'com.rxjava.rxhttp:rxhttp:1.0.5'
       //注解处理器，生成RxHttp类，即可一条链发送请求
       annotationProcessor 'com.rxjava.rxhttp:rxhttp-compiler:1.0.5'
       //管理RxJava及生命周期，Activity/Fragment 销毁，自动关闭未完成的请求
      //AndroidX
   implementation 'com.rxjava.rxlife:rxlife-x:1.0.5'`
还是报同样的错误
`More than one file was found with OS independent path 'META-INF/proguard/androidx-annotations.pro'`

**Comment by CaiJingFu** [comment]
`implementation 'com.rxjava.rxlife:rxlife:1.0.4'`
就没有问题

**Comment by liujingxing** [comment]
你使用的是kotlin?有依赖第三方kotlin写的 库吗？

**Comment by CaiJingFu** [comment]
我使用的是Java，没有依赖第三方的kotlin
