### ISSUE TITLE
个人有两个小需求

### ISSUE THREAD

**Issue by inshyma** [liujingxing/RxHttp#14]
1. 有时我需要两个或两个以上请求才可以得到自己想要的数据,可以使用你的封装么?

2. 一些异常的统一处理 如: 断网提示, cookie失效, 登录被踢... ...

**Comment by liujingxing** [comment]
1、多请求问题，请查看https://blog.csdn.net/liujingxing93/article/details/86651522
2、统一异常处理请查看https://juejin.im/post/5cc095b7f265da0379417be0(自定义解析这块)，并结合OnErrer类处理异常，OnErrer类已上传。

**Comment by liujingxing** [comment]
1、多请求问题，请查看https://blog.csdn.net/liujingxing93/article/details/86651522
2、统一异常处理请查看https://juejin.im/post/5cc095b7f265da0379417be0   
  (自定义解析这块)，并结合OnErrer类处理异常，OnErrer类已上传。
