### ISSUE TITLE
不能在 kotlin 中使用吗,每次都会提示Unresolved reference: RxHttp

### ISSUE THREAD

**Issue by KiWiLss** [liujingxing/RxHttp#15]

**Comment by liujingxing** [comment]
可以的，你有使用注解吗？没有的话就找不会生成RxHttp类

**Comment by KiWiLss** [comment]
有注解,也生成了 Rxhttp 类,不过一运行就报错
public class Url {
    //设置为默认域名
    @DefaultDomain()
    public static String baseUrl = "https://lepaytest.weemang.com/";
}

**Comment by liujingxing** [comment]
很抱歉，这两天没来得及回复
`kapt 'com.rxjava.rxhttp:rxhttp-compiler:1.0.5` kotlin的话，用这个试试
