### ISSUE TITLE
什么时候能出一份专门适配kotlin的教程啊？

### ISSUE THREAD

**Issue by ted23335921** [liujingxing/RxHttp#16]
什么时候能出一份专门适配kotlin的教程啊？我这边引入kotlin项目中，各种报错和找不到。就算直接把这边clone下来的项目转换成kotlin项目，也是跑不起来。。。

**Comment by liujingxing** [comment]
好的，今晚解决这个问题

**Comment by liujingxing** [comment]
你好，我用kotlin试了下确实不行，`kapt 'com.rxjava.rxhttp:rxhttp-compiler:1.0.5`，使用kapt代替annotationProcessor就好了，感谢你的反馈。

**Comment by ted23335921** [comment]
> 你好，我用kotlin试了下确实不行`kapt 'com.rxjava.rxhttp:rxhttp-compiler:1.0.5`，，使用kapt代替annotationProcessor就好了，感谢你的反馈。

大佬，post请求的时候，参数要放到body体里面，我创建map，然后.add(map)的形势传参，这样是无法调通的。是我用的不对，还是怎么回事？怎样把参数放到body体中？

**Comment by liujingxing** [comment]
你使用的postForm还是postJson?前者是发送表单形式的post请求，后者是发送Json形式的post请求，都会将参数放到body里面。无法调通，有报什么错误吗？

**Comment by ted23335921** [comment]
> 你使用的postForm还是postJson?前者是发送表单形式的post请求，后者是发送Json形式的post请求，都会将参数放到body里面。无法调通，有报什么错误吗？

请求这个解决了，但是，如果在activity和fragment中使用是没有问题的，不过在MVP中，网络请求并不在activity中，而是在P中，这样，【.`as`(RxLife.asOnMain(this))  】这里就会报错。怎么处理能把这个请求还是绑定到activity的生命周期中？

**Comment by liujingxing** [comment]
P层及任意类使用`RxLife.as(this)`请查看https://juejin.im/post/5cf3e1235188251c064815f1
