### ISSUE TITLE
现在还没有返回结果拦截器吗

### ISSUE THREAD

**Issue by 18723309899** [liujingxing/RxHttp#17]
现在还没有返回结果拦截器吗

**Comment by liujingxing** [comment]
你可以看看自定义解析器https://juejin.im/post/5cc095b7f265da0379417be0。
也可以OkHttpClient增加拦截器。

**Comment by Richard-lxz** [comment]
没有网络拦截器吗？现有的功能有没有什么方法可以做到类似的实现？

**Comment by liujingxing** [comment]
拦截器可通过自定义OkHttpClient对象添加，然后在初始化调用RxHttp.init(OkHttpClient client)方法传入OkHttpClient对象，这样即可。

**Comment by 18723309899** [comment]
准备下个项目用,思路已经理解了
------------------ 原始邮件 ------------------
发件人: "liujingxing"<notifications@github.com>;
发送时间: 2019年7月29日(星期一) 晚上11:17
收件人: "liujingxing/RxHttp"<RxHttp@noreply.github.com>;
抄送: "Mr.Yan"<310816920@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [liujingxing/RxHttp] 现在还没有返回结果拦截器吗 (#17)




拦截器可通过自定义OkHttpClient对象添加，然后在初始化调用RxHttp.init(OkHttpClient client)方法传入OkHttpClient对象，这样即可。
