### ISSUE TITLE
添加请求参数时是否可以添加params

### ISSUE THREAD

**Issue by wlingf** [liujingxing/RxHttp#2]
添加请求参数时，每个参数都要add,是否可以设置一个params 通过params去add每个参数，最后在请求的时候去add (params)，这样更有利于对每个请求做二次封装

**Comment by liujingxing** [comment]
好的，下个版本会加入这个方法

**Comment by wlingf** [comment]
坐等更新

**Comment by liujingxing** [comment]
已更新，请查看 1.0.2版本
