### ISSUE TITLE
请问这个相对于Retrofit+rx的优点和不足在哪

### ISSUE THREAD

**Issue by zhulujiang** [liujingxing/RxHttp#21]
请问这个相对于Retrofit+rx的优点和不足在哪

**Comment by liujingxing** [comment]
1、API简单易用，学习成本极低，学会请求三部曲就可以基本掌握
2、对文件的操作非常优雅，详情https://juejin.im/post/5cd0568a51882569bf52153cjuejin.im/post/5cd0568a5...
3、对baseUrl的处理也非常优雅，详情https://juejin.im/post/5ce2cdc3e51d45554877a528juejin.im/post/5ce2cdc3e...
4、增加了解析器的概念，这一点对于统一异常处理非常方便，详情https://juejin.im/post/5cc095b7f265da0379417be0juejin.im/post/5cc095b7f...
