### ISSUE TITLE
from -> asObject

### ISSUE THREAD

**Issue by inshyma** [liujingxing/RxHttp#24]
可以把from加回来么? 我这边数据返回嵌套的不一样 所以用起来不如from方便

**Comment by liujingxing** [comment]
什么场景下，asXXX不如from方便？

**Comment by inshyma** [comment]
from(new AppSimpleParser<List<UserInfo>>() {
                })

**Comment by inshyma** [comment]
from(new AppSimpleParser<List<UserInfo>>() {
                });
AppSimpleParser 里面有处理errorCode的逻辑

**Comment by inshyma** [comment]
`from(new AppSimpleParser<List<xxx>>() {
});`
AppSimpleParser 里面有处理errorCode的逻辑

**Comment by liujingxing** [comment]
可以在自定义的解析器上使用@Parser注解，比使用from还更方便。详情查看https://juejin.im/post/5cc095b7f265da0379417be0

**Comment by inshyma** [comment]
我发现了asParser  这个应该可以代替from

**Comment by liujingxing** [comment]
你说不如from方便，我以为你知道asParser呢。不过还是建议你使用注解。

**Comment by inshyma** [comment]
我把网络框架放在另一个model  使用注解DataParser时  编译器没有在RxHttp自动生成相应的方法 所以直接用asParser 吧

**Comment by liujingxing** [comment]
A Module依赖注解处理器，那么只能在A Module中使用注解。注解处理器只会在本Module 中检索注解。

**Comment by inshyma** [comment]
onError异常统一处理在哪个文章写着  麻烦分享下  我没找到

**Comment by liujingxing** [comment]
你看下Demo里面的OnError、ErrorInfo类
