### ISSUE TITLE
会抛出android.os.NetworkOnMainThreadException

### ISSUE THREAD

**Issue by lalozhang** [liujingxing/rxhttp#243]
调用的的时候 会抛出android.os.NetworkOnMainThreadException 使用移步调用时候

**Comment by liujingxing** [comment]
检查下是否在子线程操作UI了，如果是，请指定[回调所在线程](https://github.com/liujingxing/okhttp-RxHttp/wiki/%E6%8C%87%E5%AE%9A%E8%AF%B7%E6%B1%82%E3%80%81%E5%9B%9E%E8%B0%83%E7%BA%BF%E7%A8%8B)
