### ISSUE TITLE
2.6.0版本build报错

### ISSUE THREAD

**Issue by eternallyjie** [liujingxing/rxhttp#248]
升级2.6.0版本，build之后生成RxHttp之类的文件，报错，缺少init等方法。

**Comment by liujingxing** [comment]
看看更新日志

**Comment by liujingxing** [comment]
你真快，我刚升级，还没通报大家呢，你就知道了

**Comment by eternallyjie** [comment]
> 你真快，我刚升级，还没通报大家呢，你就知道了

刚好在升级其他插件版本，就看到了没然后升级了下。build好几次都报错，重启项目还是报错，就是生成的RxHttp文件缺少了一些方法。然后我就又退回去了。。。

**Comment by eternallyjie** [comment]
升级后怎么自定义Parse报错啊。找不到AbstractParser这个类啊。
![image](https://user-images.githubusercontent.com/30895476/118110220-bbeab980-b414-11eb-8b3b-e9d444f7c5b3.png)

**Comment by liujingxing** [comment]
升级下kotlin版本，kotlin 1.5对低版本兼容性不太好，kotlin1.4.32可以用。

**Comment by eternallyjie** [comment]
> 升级下kotlin版本，kotlin 1.5对低版本兼容性不太好，kotlin1.4.32可以用。

![image](https://user-images.githubusercontent.com/30895476/118420654-0066a580-b6f2-11eb-8cba-0f20518227bc.png)

升级了kotlin版本，并不行，然后没办法看着难受，AS直接升到4.2就可以了。

**Comment by liujingxing** [comment]
@eternallyjie 你这kotlin版本没升级成功，我这as 4.1.3 + kotlin 1.4.32是可以的

**Comment by eternallyjie** [comment]
> @eternallyjie 你这kotlin版本没升级成功，我这as 4.1.3 + kotlin 1.4.32是可以的

我AS 3.6.3+kotlin 1.4.10也可以了
