### ISSUE TITLE
2.6.0版 无法自定义Parser，找不到AbstractParser

### ISSUE THREAD

**Issue by zqf-dev** [liujingxing/rxhttp#251]
依赖如下并且 Rebuild 已成功，可以生成RxHttp：
![image](https://user-images.githubusercontent.com/16233519/118909664-ef1dd300-b955-11eb-9694-56057c77e5c9.png)

![image](https://user-images.githubusercontent.com/16233519/118909709-fe048580-b955-11eb-9379-8259a355d6f6.png)

![image](https://user-images.githubusercontent.com/16233519/118909849-2e4c2400-b956-11eb-81a1-139c1a772a1a.png)

![1](https://user-images.githubusercontent.com/16233519/118909265-5b4c0700-b955-11eb-86a5-03f938c75ee0.png)

**Comment by liujingxing** [comment]
请升级kotlin版本，详情#248

**Comment by zqf-dev** [comment]
> 请升级kotlin版本，详情#248

非常感谢，AS 3.6.1，将kotlin升级到1.4.10可以了。
