### ISSUE TITLE
两个子moudle都依赖了rxhttp，出现BaseRxHttp is defined multiple times

### ISSUE THREAD

**Issue by ppg408331701** [liujingxing/rxhttp#253]
Type rxhttp.BaseRxHttp is defined multiple times: E:\project\GXRCW_2021\app_gxzpb\build\.transforms\ed639b27b1db40363da4896faff07237\classes\classes.dex, E:\project\GXRCW_2021\app_gxrcw\build\.transforms\e503aab4d17c0a85e3f8ec40b2d9b2f5\classes\classes.dex

今天升级到2.6.1。出现了这个问题。之前使用的是2.5.7
项目是这样依赖的。
 **baselib 依赖 
 api 'com.github.liujingxing.rxhttp:rxhttp:2.6.1'**

**Alib 依赖
kapt  'com.github.liujingxing.rxhttp:rxhttp-compiler:2.6.1'**

**Blib 依赖
kapt  'com.github.liujingxing.rxhttp:rxhttp-compiler:2.6.1'**

Alib和 Blib 通过  api project(path: ':baselib')  引用rxhttp。

我这样使用有什么问题吗？

**Comment by ppg408331701** [comment]
。。。那我以前都这么干的，居然没出错

谢了

**Comment by ppg408331701** [comment]
不行，如果Alib、Blib都去除  kapt 'com.github.liujingxing.rxhttp:rxhttp-compiler:2.6.1'  这个的话

那么就引用不到rxhttp。  kapt 有类似  api project(path: ':baselib')  这样的用法吗？

不然子moudle无法使用

**Comment by liujingxing** [comment]
`kapt rxhttp-compiler`的作用仅仅是为了生成RxHttp相关类，只要在baselib生成了RxHttp类，上层就可以使用。引用不到，就说明没有生存，为啥不生产，请查看[集成RxHttp，却没有RxHttp这个类？](https://github.com/liujingxing/rxhttp/wiki/FAQ#%E9%A6%96%E6%AC%A1%E9%9B%86%E6%88%90rxhttp%E5%8D%B4%E6%B2%A1%E6%9C%89rxhttp%E8%BF%99%E4%B8%AA%E7%B1%BB)

**Comment by ppg408331701** [comment]
![image](https://user-images.githubusercontent.com/16531268/118960235-a71ea080-b995-11eb-9f10-8523ea2d9749.png)
应该是生成了的  

baselib自身是可以引用的。

我明天再研究一下

**Comment by liujingxing** [comment]
生成了，那这个类就属于baselib下的类，只要上层依赖了baselib，就可引用到。

**Comment by ppg408331701** [comment]
我的错，今天早上重启了android studio之后就没问题了。估计的IDE的锅
