### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by xiaotian-freedom** [liujingxing/rxhttp#254]
上传完成后会进到error中，报错：java.io.EOFException

**Comment by liujingxing** [comment]
你这提供的信息太少了，RxHttp、OkHttp版本多少，以及具体的错误堆栈信息发出来

**Comment by xiaotian-freedom** [comment]
rxhttp:2.6.1
okhttp:4.9.1
该错误信息是在Rxjava onError 中输出

**Comment by liujingxing** [comment]
请贴出具体的错误堆栈信息，否则我无法定位。

**Comment by xiaotian-freedom** [comment]
添加了自定义OKHttpClient后解决了这个问题，可以关闭了
