### ISSUE TITLE
多线程执行顺序问题

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/rxhttp#257]
app的架构是MVP，有三个 presenter.dealA， presenter.dealB， presenter.dealC 需要依次按顺序执行，每个dealA，dealB，dealC方法里都是用RxHttp写的，请问怎么按顺序执行，即执行完presenter.dealA后，再执行presenter.dealB，再执行请求presenter.dealC

如何保证dealA，dealB，dealC依次按照顺序执行？
```java
如何保证依次按照顺序执行
void onClick() {
    if () {
        presenter.dealA()
    }

    if () {
        presenter.dealB()
    }

    presenter.dealC();
}

class Presenter {
    void dealA() {
        RxHttp.get("1")
    }

    void dealB() {
        RxHttp.get("2")
    }

    void dealC() {
        RxHttp.get("3")
    }
}
```

**Comment by liujingxing** [comment]
RxHttp + RxJava请求串/并行问题，查看[RxHttp 优雅的实现请求串行与并行](https://juejin.cn/post/6844903870074732551);
RxHttp + 协程请求串/并行问题，查看[RxHttp ，比Retrofit 更优雅的协程体验](https://juejin.cn/post/6844904100090347528)

**Comment by chenyinchao** [comment]
> RxHttp + RxJava 请求串 / 并行问题，查看[RxHttp 优雅的实现请求与并行](https://juejin.cn/post/6844903870074732551)；
> RxHttp + 协程请求串 / 并行问题，查看 [RxHttp 更漂亮，比 Retrofit 更优雅的协程体验](https://juejin.cn/post/6844904100090347528)

好的，我看到了，只是这样写有没有很冗余，根据我上面列出的代码，有多个if判断，是不是每个判断用串行来写？

**Comment by liujingxing** [comment]
多任务处理，优先考虑协程，这是最优解，不管你有多复杂的逻辑，它都能适应；
随后再考虑RxJava的 'doOnNext + filter + flatMap‘操作符配套使用，filter里面写你的判断逻辑，具体如何使用需要你自己去了解；
最后那就是原始方法，在上一个请求的回调里执行下一个请求，判断逻辑同样可以写在回调里

**Comment by chenyinchao** [comment]
> 多任务处理，优先考虑协程，这是最优解，不管你有多复杂的逻辑，它都能适应；
> 随后再考虑 RxJava 的 `doOnNext + filter + flatMap` 操作符配套使用，filter 里面写你的判断逻辑，具体如何使用需要你自己去了解；
> 最后那就是原始方法，在上一个请求的回调里执行下一个请求，判断逻辑同样可以写在回调里

感谢了，我知道从哪个方向着手了
