### ISSUE TITLE
如果请求状态码非200 , 但服务器有返回数据, 直接走了失败回调, 怎么接收服务器的返回数据?

### ISSUE THREAD

**Issue by yuyuyu000** [liujingxing/RxHttp#26]
如果请求状态码非200 , 
但服务器有返回数据, 直接走了失败回调, 
怎么接收服务器的返回数据?

**Comment by liujingxing** [comment]
什么情况下状态码非200，服务器还有数据返回？

**Comment by yuyuyu000** [comment]
> 什么情况下状态码非200，服务器还有数据返回？

像这样
![image](https://user-images.githubusercontent.com/5947547/62137967-687baa00-b319-11e9-8d46-2d3d0c93ccf5.png)

**Comment by yuyuyu000** [comment]
> 什么情况下状态码非200，服务器还有数据返回？

像这样的
![image](https://user-images.githubusercontent.com/5947547/62138040-8a752c80-b319-11e9-8b59-0c7dcebf3641.png)

**Comment by liujingxing** [comment]
方便加QQ吗，327744707

**Comment by jin123d** [comment]
@liujingxing 标准化RESTful API基本是这样设计的，只有成功才走200+，其他错误信息在300+返回

**Comment by liujingxing** [comment]
1.2.1版本，非200抛出异常时，会带上服务器的返回数据，可通过HttpStatusCodeException#getResult()方法获取
