### ISSUE TITLE
rebuild报错

### ISSUE THREAD

**Issue by TangStudio** [liujingxing/rxhttp#261]
起初找不到rxhttp，看了你的FAQ后在本module的URL里加了@DefaultDomain，然后rebuild了一下工程，报A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction

**Comment by liujingxing** [comment]
往上翻，有错误详情

**Comment by TangStudio** [comment]
OK，应该是as版本太老了，4.01用习惯了，升级到4.2.1,gradle也升级上来后就好了
