### ISSUE TITLE
部分设备报错，导致请求不了

### ISSUE THREAD

**Issue by VolleyCN** [liujingxing/rxhttp#262]
E/RxJava: java.lang.IllegalArgumentException: Unexpected char 0x4e2d at 0 in provider value: 中国移动
 E/RxJava: java.lang.NullPointerException: Actually not, but can't throw other exceptions due to RS

**Comment by VolleyCN** [comment]
已知是因为请求头包含中文，okhttp3检测不支持中文导致，可以加一个请求头编码检测处理

**Comment by liujingxing** [comment]
使用`addNonAsciiHeader`方法添加请求头即可

**Comment by VolleyCN** [comment]
ok
