### ISSUE TITLE
碰到个错误……

### ISSUE THREAD

**Issue by xiaxinqing** [liujingxing/rxhttp#264]
Execution failed for task ':app:javaPreCompileDebug'.
> Could not resolve all files for configuration ':app:debugAnnotationProcessorClasspath'.
   > Could not find ccom.github.liujingxing.rxhttp:rxhttp-compiler:2.6.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/ccom/github/liujingxing/rxhttp/rxhttp-compiler/2.6.2/rxhttp-compiler-2.6.2.pom
       - https://repo.maven.apache.org/maven2/ccom/github/liujingxing/rxhttp/rxhttp-compiler/2.6.2/rxhttp-compiler-2.6.2.pom
       - https://jitpack.io/ccom/github/liujingxing/rxhttp/rxhttp-compiler/2.6.2/rxhttp-compiler-2.6.2.pom
       - https://jcenter.bintray.com/ccom/github/liujingxing/rxhttp/rxhttp-compiler/2.6.2/rxhttp-compiler-2.6.2.pom
       - file:/Users/xiaxinqing/Desktop/sfbapp/huawai_community/HWSQApp/app/libs/rxhttp-compiler-2.6.2.jar
       - file:/Users/xiaxinqing/Desktop/sfbapp/huawai_community/HWSQApp/app/libs/rxhttp-compiler.jar
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

修改成和你项目一样 也无法下载，求帮助

**Comment by liujingxing** [comment]
你依赖错了，不是`ccom.github.liujingxing.rxhttp:rxhttp-compiler:2.6.2`，而是`com.github.liujingxing.rxhttp:rxhttp-compiler:2.6.2`
