### ISSUE TITLE
使用addJsonElement遇到的问题。

### ISSUE THREAD

**Issue by dangxiaop** [liujingxing/rxhttp#265]
使用addJsonElement设置参数的时候，数据会被改掉
比如我设置了一个字符串addJsonElement("id","5396635409676328962")
传到后台就变成了5396635409676328960，看了下rxhttp的代码，数据是在JsonUtils.toAny中将String转成Json的时候toDouble,toLong之后变的。
![image](https://user-images.githubusercontent.com/64882275/122501919-2e5c4400-d028-11eb-8038-f9c9aff22fa0.png)
![image](https://user-images.githubusercontent.com/64882275/122502022-5f3c7900-d028-11eb-9483-93c36b6f8e3e.png)

**Comment by dangxiaop** [comment]
![image](https://user-images.githubusercontent.com/64882275/122502236-d4a84980-d028-11eb-948a-f50200f6a93e.png)

**Comment by liujingxing** [comment]
你的RxHttp版本应该有点老了，这个很早就修复了，升级到最新版本就好

**Comment by dangxiaop** [comment]
2.5.4的，可能是有点老了，我抽空升级一下看看，谢谢啦

**Comment by liujingxing** [comment]
#225
