### ISSUE TITLE
关闭请求报错

### ISSUE THREAD

**Issue by zuimengliu** [liujingxing/rxhttp#266]
同一个接口需要多地方调用，使用RxHttpPlugins.cancelAll(tag);关闭请求 报Socket closed或者canceled错误

**Comment by liujingxing** [comment]
请求被强制中断，抛出对应的异常，这是正常的，这对你有什么影响吗？

**Comment by zuimengliu** [comment]
调用RxHttpPlugins.cancelAll(tag)关闭请求，是不想重复接到请求结果，调用RxHttpPlugins.cancelAll(tag)之后的请求结果也没有了

**Comment by liujingxing** [comment]
没懂？为啥会重复收到请求结果？

**Comment by zuimengliu** [comment]
页面显示和接收到各种消息时调用请求数据接口，同一时间可能调用多次，于是在请求数据前调用一下RxHttpPlugins.cancelAll(tag)关闭之前的请求，

**Comment by liujingxing** [comment]
那你现在的问题是什么？

**Comment by zuimengliu** [comment]
调用RxHttpPlugins.cancelAll(tag)关闭上次请求，不影响下次请求

**Comment by liujingxing** [comment]
现在就是不影响下次请求

**Comment by zuimengliu** [comment]
我现在使用是影响下次请求的，不知道是不是我同时请求的次数太多的原因

**Comment by liujingxing** [comment]
可以写了demo我看看
