### ISSUE TITLE
单个接口解密，不同的接口对应不同的解密方式

### ISSUE THREAD

**Issue by 1Ezreal** [liujingxing/rxhttp#271]

**Comment by liujingxing** [comment]
你说的太空泛了，可以详细点

**Comment by 1Ezreal** [comment]
就是现在接口解密不是统一配置的吗，我现在的需求是有每个接口都对应不同的解密方式

**Comment by 1Ezreal** [comment]
RxHttp.get(Url.Help.help_list)
            .toStr()
            .map {
                //解密操作
                val decodeStr=DecodeUtils.decodeByType(it,DecodeUtils.TYPE_NORMAL)
                //类型转换
                val type = object : TypeToken<List<HelpBean?>?>() {}.type
                return@map GsonUtil.getObject<List<HelpBean>>(it,type)
            }
            .await()

**Comment by 1Ezreal** [comment]
我现在用的是map，但是统一code判断就不知道怎么弄了

**Comment by 1Ezreal** [comment]
RxHttp.get(Url.Help.help_list)
            .toStr()
            .map {
                //解密操作
                val decodeStr=DecodeUtils.decodeByType(it,DecodeUtils.TYPE_NORMAL)
                //类型转换
                val type = object : TypeToken<List<HelpBean?>?>() {}.type
                return@map GsonUtil.getObject<List<HelpBean>>(decodeStr,type)
            }
            .await()

**Comment by liujingxing** [comment]
那你得跟我说详细点，具体是什么解密的，有什么相同点及不同点？

**Comment by 1Ezreal** [comment]
接口回调得到的string为加密字符串，需要将string进行解密然后得到JSON

**Comment by liujingxing** [comment]
我想知道的是，不同请求解密如何不一样，是解密的key不一样，还是说解密方式完全不一样？

**Comment by 1Ezreal** [comment]
解密方式不一样

**Comment by 1Ezreal** [comment]
需求是每个接口能单独配置解密方式，大佬看下改、该咋搞

**Comment by 1Ezreal** [comment]
需求是每个接口能单独配置解密方式，大佬看下该咋搞！

**Comment by liujingxing** [comment]
不好搞，都不一样，只能一个个写

**Comment by 1Ezreal** [comment]
全局配置加密的那里可以判断不

**Comment by liujingxing** [comment]
不可以，这个需求不合理，我感觉你是不是理解错了，我不太相信有接口这么设计的，一般都是解密的key不一样，将key传给解析器就好了

**Comment by liujingxing** [comment]
你也可以在解析器里去判断

**Comment by 1Ezreal** [comment]
可以，解析器里面可以判断，我们的接口乱七八糟的
