### ISSUE TITLE
怎么上传body类型的数据啊

### ISSUE THREAD

**Issue by 345127607** [liujingxing/rxhttp#272]
怎么上传body类型的数据啊。  Retorfit 里面的@Body 直接上传一个对象 ，找了一圈 API 都没发现使用

**Comment by liujingxing** [comment]
RxHttp.postBody("url").setJsonBody(Object)

**Comment by 345127607** [comment]
> postBody

好的 谢谢，我试试最新版 用的2.4.2.没有这个方法

**Comment by 345127607** [comment]
> RxHttp.postBody("url").setJsonBody(Object)

我试了最新版本 没有 postBody呢 要做什么特殊配置吗

**Comment by liujingxing** [comment]
不需要额外配置，2.5.2版本就有这个方法。最新是2.6.4版本。

**Comment by 345127607** [comment]
> 不需要额外配置，2.5.2版本就有这个方法。最新是2.6.4版本。
好的，感谢大佬。我换了高版本应该没有Rebuild
