### ISSUE TITLE
rxhttp能够解析xml吗

### ISSUE THREAD

**Issue by Zhao187** [liujingxing/RxHttp#28]
rxhttp能够解析后台返回的xml数据吗

**Comment by liujingxing** [comment]
可以，但是需要你自定义解析器。可以看看https://juejin.im/post/5cc095b7f265da0379417be0

**Comment by Zhao187** [comment]
rxhttp可以集成 retrofit的xmlConvert吗

**Comment by liujingxing** [comment]
正在考虑以更好的方式支持Xml等其它格式解析，如果没有更好的方式，会采用retrofit的xmlConvert

**Comment by liujingxing** [comment]
刚发布了1.3.1版本，已解决此问题。并提供了RxHttp.setConverter(IConverter)方法，可设置自定义的Converter，详情请查看[README.md](https://github.com/liujingxing/RxHttp/blob/master/README.md)
