### ISSUE TITLE
post请求,想直接传递加密密文,该怎么写？

### ISSUE THREAD

**Issue by johnvi-l** [liujingxing/rxhttp#280]
请求的传参直接传递密文,不是{"参数1":"值1",”sign“:"密文"},   而是 "密文"   如何写？

**Comment by liujingxing** [comment]
请查看[自定义Param文档](https://github.com/liujingxing/rxhttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Param)
