### ISSUE TITLE
无法按照你的掘金原文一样来继承UriFactory

### ISSUE THREAD

**Issue by Bystander291** [liujingxing/rxhttp#282]
我的版本是最新的2.6.5，但是我继承UriFactory的时候发现UriFactory里面就一个Context参数，也没有getUri的函数，我上Github看您的源码，里面也是一样的，请问这怎么解决

**Comment by liujingxing** [comment]
为什么要有getUri函数？仅需要实现insert方法即可，当然，如果你用到断点下载，还需要重写query方法
