### ISSUE TITLE
setResultDecoder回调会走2遍

### ISSUE THREAD

**Issue by johnvi-l** [liujingxing/rxhttp#284]
setResultDecoder回调走2遍是什么情况呢？

**Comment by liujingxing** [comment]
日志打印会额外走一次，https://github.com/liujingxing/rxhttp/issues/65

**Comment by johnvi-l** [comment]
> 日志打印会额外走一次，#65

toast也会多走一遍啊

**Comment by liujingxing** [comment]
关闭debug模式就好了

**Comment by johnvi-l** [comment]
> 关闭debug模式就好了

关了之后还是会走2遍

**Comment by liujingxing** [comment]
调试看看就知道了
