### ISSUE TITLE
kotlin 使用文档细节

### ISSUE THREAD

**Issue by pangli** [liujingxing/rxhttp#286]
kotlin中应该不是asXXXX是toXXXX吧
还有能否将kotlin结合协程异常处理这块文档详细一下
https://juejin.cn/post/6844904100090347528 这个文档好久没更新了许多用法变了吧
业务code统一判断实现方式也改变了吧
class ResponseParser<T> : TypeParser<T>

**Comment by liujingxing** [comment]
协程异常处理，看[awaitResult](https://juejin.cn/post/6844904100090347528#heading-6)操作符

**Comment by pangli** [comment]
是否有非协程和Rxjava的普通用法？假如在后台调用一个简单的接口，既不想用协程，也不想用Rxjava，想少引入几个依赖库

**Comment by liujingxing** [comment]
```java
//异步
RxHttp.get("...").add("","").newCall().enqueue(Callback)
//同步
RxHttp.get("...").add("","").executeXxx()
```
