### ISSUE TITLE
使用RxHttp .postForm .addFile  方法 后端报"不支持' Content type 'multipart/form-data;boundary=d78c3a8a-dbb0-412f-9c45-13575d01a921;charset=UTF-8' not supported'请求"

### ISSUE THREAD

**Issue by johnvi-l** [liujingxing/rxhttp#288]
除了postForm上传文件 还有什么方法上传文件

**Comment by liujingxing** [comment]
http一共有三种方式上传文件  https://images.zsxq.com/FpxIQ8uCQpcOIKa5eer8TwMn6FjU?imageMogr2/auto-orient/quality/100!/ignore-error/1&e=1633017599&token=kIxbL07-8jAj8w1n4s9zv64FuZZNEATmlU_Vm6zD:tIj9EZmUnACeGinV9jb5wqt_dk4=
