### ISSUE TITLE
如图，类里面报红，用的最新版版本1.16

### ISSUE THREAD

**Issue by liuwen370494581** [liujingxing/RxHttp#29]
![QQ浏览器截图20190823164939](https://user-images.githubusercontent.com/19323065/63580047-7cd45f00-c5c6-11e9-92f4-ee416efdbb4f.png)

**Comment by liuwen370494581** [comment]
还有RxHttp类里面的 asResponse（）方法也没有，是最新版移除了还是？

**Comment by liujingxing** [comment]
这些方法是通过注解生成的

**Comment by liuwen370494581** [comment]
额。。。。 是通过注解，但我这里是报好的，怎么解决呢

**Comment by liujingxing** [comment]
看看这篇文章https://juejin.im/post/5cc484146fb9a032332b35ae

**Comment by liuwen370494581** [comment]
看完了，但是下面那个下载里面getProcess()那个方法也是自动生成的嘛？

**Comment by liujingxing** [comment]
那个不是，那是因为上面报红，所以下面就报红
