### ISSUE TITLE
 Caused by: java.lang.IllegalStateException: Not a JSON Object: 

### ISSUE THREAD

**Issue by chenyinchao** [liujingxing/rxhttp#293]
使用 RxHttp.postJson().addAll() 报错：

Caused by: java.lang.IllegalStateException: Not a JSON Object: 
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
        at rxhttp.wrapper.param.JsonParam.addAll(JsonParam.java:56)
        at rxhttp.wrapper.param.RxHttpJsonParam.addAll(RxHttpJsonParam.java:42)

环境：
Android Studio Arctic Fox | 2020.3.1
使用FastJsonConverter
rxhttp                       : "2.6.5",
rxhttp-compiler       : "2.6.5",
rxlife                        : "2.1.0",
okhttp                       : "3.12.6",
rxandroid                    : "2.1.1",
rxjava                       : "2.2.8",
gson                         : "2.8.7",
converter-fastjson    :2.6.5'

**Comment by liujingxing** [comment]
`addAll(String json)`仅接受json对象字符串

**Comment by chenyinchao** [comment]
> `addAll(String json)` 仅接受 json 对象字符串

addAll(GsonUtils.toJson(list))，这样不行吗

**Comment by liujingxing** [comment]
如果我没猜错，`GsonUtils.toJson(list)`是json数组字符串，这是不支持的，可以考虑调用`addJsonElement(String key, String jsonElement)`方法

**Comment by 932707629** [comment]
> 如果我没猜错，`GsonUtils.toJson(list)`是json数组字符串，这是不支持的，可以考虑调用`addJsonElement(String key, String jsonElement)`方法

大佬您好，想问一下为啥不支持jsonArray呢

**Comment by liujingxing** [comment]
> > 如果我没猜错，`GsonUtils.toJson(list)`是json数组字符串，这是不支持的，可以考虑调用`addJsonElement(String key, String jsonElement)`方法
> 
> 大佬您好，想问一下为啥不支持jsonArray呢

jsonArray里面是n个对象，没有对应的key。
如果仅发送jsonArray字符串，可以
```java
RxHtpp.postJsonArray(...)
        .addAll(jsonArray)
        ...
```

**Comment by liujingxing** [comment]
> > > 如果我没猜错，`GsonUtils.toJson(list)`是json数组字符串，这是不支持的，可以考虑调用`addJsonElement(String key, String jsonElement)`方法
> > 
> > 大佬您好，想问一下为啥不支持jsonArray呢
> 
> jsonArray里面是n个对象，没有对应的key。
> 如果仅发送jsonArray字符串，可以
> ```java
> RxHtpp.postJsonArray(...)
>     .addAll(jsonArray)
>     ...
> ```

**Comment by 932707629** [comment]
> > > > 如果我没猜错，`GsonUtils.toJson(list)`是json数组字符串，这是不支持的，可以考虑调用`addJsonElement(String key, String jsonElement)`方法
> > > 
> > > 
> > > 大佬您好，想问一下为啥不支持jsonArray呢
> > 
> > 
> > jsonArray里面是n个对象，没有对应的key。
> > 如果仅发送jsonArray字符串，可以
> > ```java
> > RxHtpp.postJsonArray(...)
> >     .addAll(jsonArray)
> >     ...
> > ```

好的，要的就是这个，感谢大佬回复
