### ISSUE TITLE
打release包后找不到RxHttp导致请求失败

### ISSUE THREAD

**Issue by EHG613** [liujingxing/rxhttp#298]
java+kolin 混合开发，使用kapt
调试的时候正常，打release包之后，无法发出网络请求

**Comment by liujingxing** [comment]
你咋确定请求没发出去？请求都会发的；
这肯定是混淆引起的问题，实体类要防混

**Comment by EHG613** [comment]
实体类肯定是防混淆的，本来想用rxhttp 逐步替换老项目的网络请求库，部分模块打包后出现问题，换成老的网络请求库可以正常使用

**Comment by EHG613** [comment]
也可能是老项目里的其他插件冲突导致的问题，debug的时候经常也会出现RxHttp找不到的情况，重新clean rebuild就又好了

**Comment by liujingxing** [comment]
问题解决了？当你执行Clean Project操作时，RxHttp类是会被删除的，所以就会找不到，rebuild操作重新生成
