### ISSUE TITLE
Demo 有优化的空间

### ISSUE THREAD

**Issue by libertyfree** [liujingxing/RxHttp#3]
1.界面多元化
2.回调加入页面的提醒
3.后期是否支持kotlin?

**Comment by liujingxing** [comment]
首先，感谢您的宝贵意见。
1.界面多元化指的是多请求的并行/串行吗？是的话，https://blog.csdn.net/liujingxing93/article/details/86651522，这篇文章有介绍
2.不是很明白，什么是页面的提醒？
3.后续会考虑适配AndroidX  和 kotlin

**Comment by 282144757** [comment]
支持作者
