### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by insomniastay** [liujingxing/RxHttp#30]
下载文件时,会崩溃, 定制机的缓存大小有限制,报错位置是 ProgressResponseBody 的86行 long bytesRead = super.read(sink, byteCount);,内存溢出了, 发现已下载的内容页没有写入本地, 请问, 这个下载是读取整个文件到缓存, 在把缓存写入到本地的吗

**Comment by liujingxing** [comment]
方便进群吗，方便交流？群号：378530627，或者提供下错误日志
