### ISSUE TITLE
关于自定义解析器code=200，data.data = null 时也希望走success的回调如何处理

### ISSUE THREAD

**Issue by lihomyang** [liujingxing/rxhttp#300]

**Comment by liujingxing** [comment]
[服务器返回数据不规范，导致数据解析异常](https://github.com/liujingxing/rxhttp/wiki/FAQ#%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE%E4%B8%8D%E8%A7%84%E8%8C%83%E5%AF%BC%E8%87%B4%E6%95%B0%E6%8D%AE%E8%A7%A3%E6%9E%90%E5%BC%82%E5%B8%B8)
