### ISSUE TITLE
toResponse<T>()方法TypeParser<T?>的使用问题

### ISSUE THREAD

**Issue by ericwangjp** [liujingxing/rxhttp#303]
请问如何自定义toResponse<>()的传参，比如有这种需求，全局拦截接口返回的登录超时错误码，踢出到登录页并关闭当前页面防止手动返回；或者用户账号突然被后台冻结，根据任意接口的返回错误码进行弹框提示用户，这种场景下，需要context的介入，不然没法处理，有什么方法能处理这种场景吗

**Comment by liujingxing** [comment]
这就是一个如何拿到当前context的问题，百度有很多资料；
其中`Application.ActivityLifecycleCallbacks`可以去了解下；
当然，还有更简单的做法，拿到`Application`对象，直接跳转到`LoginActivity`即可，如下：
```
public void logout(Application context) {
    Intent intent = new Intent(context, LoginActivity.class); 
    intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK | Intent.FLAG_ACTIVITY_NEW_TASK);
    context.startActivity(intent);
}
```

**Comment by ericwangjp** [comment]
模块化开发的时候是不允许这样的，网络属于独立的模块，app依赖网络模块，不能反过来网络依赖APP模块，而且application context只能实现跳转，并不能关闭当前页面

**Comment by liujingxing** [comment]
通过EventBus等方式通知上层就可以了，另外，上面代码加了`Intent.FLAG_ACTIVITY_CLEAR_TASK`，是会关闭所有activity的。

**Comment by ericwangjp** [comment]
EventBus是一个方案，但是不是很喜欢他，我再考虑下有没有更优的方案，感谢你的答复
