### ISSUE TITLE
RxJava 3.1.1 support

### ISSUE THREAD

**Issue by sunbeams001** [liujingxing/rxhttp#305]
error: cannot find symbol in the latest version of RxJava 3 with rxhttp 2.6.7
import io.reactivex.rxjava3.internal.fuseable.SimplePlainQueue;
import io.reactivex.rxjava3.internal.queue.SpscArrayQueue;

**Comment by liujingxing** [comment]
看了下，`RxJava v3.1.1`版本5天前更新的，`RxHttp`还未来得及适配；现已适配，更新到`RxHttp v2.6.8`版本，并需要通过`rxhttp_rxjava`传递具体的版本号给`rxhttp-compiler`，具体查看[更新日志](https://github.com/liujingxing/rxhttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v268)

**Comment by sunbeams001** [comment]
谢了老哥
