### ISSUE TITLE
converter-moshi 找不到

### ISSUE THREAD

**Issue by pangli** [liujingxing/rxhttp#306]
Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.liujingxing.rxhttp:converter-moshi:2.6.8.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/liujingxing/rxhttp/converter-moshi/2.6.8/converter-moshi-2.6.8.pom
       - https://jcenter.bintray.com/com/github/liujingxing/rxhttp/converter-moshi/2.6.8/converter-moshi-2.6.8.pom
       - https://repo.maven.apache.org/maven2/com/github/liujingxing/rxhttp/converter-moshi/2.6.8/converter-moshi-2.6.8.pom
       - https://jitpack.io/com/github/liujingxing/rxhttp/converter-moshi/2.6.8/converter-moshi-2.6.8.pom

**Comment by liujingxing** [comment]
再试下，应该可以了

**Comment by pangli** [comment]
好了
再问一下 rxlife-coroutine 这个依赖库废弃了？我看你最新的更新删掉了

**Comment by liujingxing** [comment]
是的，更新下，打开RxlifeScope类，里面有被抛弃的原因

**Comment by pangli** [comment]
找不到这个类了，能具体说明一下原因和替代方案吗？

**Comment by liujingxing** [comment]
怎么会没有呢，更新到2.2.0版本
```
implementation 'com.github.liujingxing.rxlife:rxlife-coroutine:2.2.0'
```
里面有原因及替代方案

**Comment by pangli** [comment]
我是使用了如下代码：自定义解析和moshi
private fun initHttp() {
        RxHttpPlugins.init(getDefaultOkHttpClient())
            .setConverter(MoshiConverter.create())
            .setDebug(true)
    }


解析：
@Parser(name = "Response")
open class ResponseParser<T> : TypeParser<BaseResponse<T>> {

    protected constructor() : super()

    constructor(type: Type) : super(type)

    override fun onParse(response: Response): BaseResponse<T> {
        val data: BaseResponse<T> = response.convertTo(BaseResponse::class, *types)
        var t = data.data //获取data字段
        if (t == null && types[0] === String::class.java) {
            /*
             * 考虑到有些时候服务端会返回：{"errorCode":300,"errorMsg":"关注成功"}  类似没有data的数据
             * 此时code正确，但是data字段为空，直接返回data的话，会报空指针错误，
             * 所以，判断泛型为String类型时，重新赋值，并确保赋值不为null
             */
            @Suppress("UNCHECKED_CAST")
            t = data.message as T
        }
        if (data.code != 0 || t == null) { //code不等于200，说明数据不正确，抛出异常
            throw ParseException(data.code.toString(), data.message, response)
        }
        return data
    }
}

然后运行报错
RxHttp: java.lang.IllegalArgumentException: Cannot serialize Kotlin type com.sino.basic.net.BaseResponse. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
这两不能结合使用吗？

**Comment by liujingxing** [comment]
可以的，这是moshi解析问题，你要自己去解决，可以自己尝试写段代码去解析`BaseResponse<T>`类
