### ISSUE TITLE
自定义Parser 对返回值code统一处理 有没有Java版写法教程

### ISSUE THREAD

**Issue by coderlater** [liujingxing/rxhttp#307]
项目中使用RxHttp做网络请求，现在需要封装BaseBean统一处理code，参照之前的文章自定义BaseParser，Rebuild编译不通过，Demo中是Kotlin写法，新手有点看不懂，以下是自定义Parser写法，@Parser注解报错：����: �����ݵ�����: Parser�޷�ת��ΪAnnotation @Parser(name = "BaseParser")

```
@Parser(name = "BaseParser")
public class BaseParser<T> extends AbstractParser<T> {

    @Override
    public T onParse(@NotNull Response response) throws IOException {


        return null;
    }
}
```

**Comment by liujingxing** [comment]
把你乱码解决就知道问题了，两个构造方法没有提供，这是必须的；Demo有Java版本的[ResponseParser](https://github.com/liujingxing/rxhttp/blob/1a269f880df71ca9749ede467c134563eed25417/app/src/main/java/com/example/httpsender/parser/java/ResponseParser.java)

**Comment by coderlater** [comment]
解决了，还是上面的代码，重新多编译了几次
项目中添加的依赖应该是旧版本implementation('com.rxjava.rxhttp:rxhttp:2.1.1')
所以继续使用的AbstractParser
感谢！
