### ISSUE TITLE
请求这个接口 一直解析错误，不知道是什么原因！这个接口可以复制在网页打开是没有问题

### ISSUE THREAD

**Issue by liuwen370494581** [liujingxing/RxHttp#31]
RxHttp: throwable = rxhttp.wrapper.exception.ParseException: Method=GET Code=-1
    
    url = https://api.apiopen.top/getJoke?page=1&count=2&type=video

    Message = data parse fail

**Comment by liujingxing** [comment]
检查下实体类结构跟数据是否一致，如果还不能解决，进群反馈吧，378530627，方便沟通

**Comment by liuwen370494581** [comment]
实体类的数据结构是用AS插件 GsonFormat 自动生成的，所以应该不是实体结构的问题，数据主要是不能解析出来，AsString()也不行，按道理asString()是万能的解析的吧

**Comment by liujingxing** [comment]
贴下你的代码，我这边asString是可以的
`RxHttp.get("https://api.apiopen.top/getJoke?page=1&count=2&type=video")
                    .asString()
                    .as(RxLife.asOnMain(this))
                    .subscribe(s -> {

                    }, throwable -> {

                    });`

**Comment by liujingxing** [comment]
贴下你的代码，我这边asString是可以的
`                RxHttp.get("https://api.apiopen.top/getJoke?page=1&count=2&type=video")
                    .asString()
                    .as(RxLife.asOnMain(this))
                    .subscribe(s -> {

                    }, throwable -> {

                    });`

**Comment by liujingxing** [comment]
![image](https://user-images.githubusercontent.com/7237396/63917263-d2988380-ca6c-11e9-9520-504218cf37a5.png)
实际解析也是可以的，估计是你代码层面的问题

**Comment by liuwen370494581** [comment]
是的 我用你写的Demo 跑是没有问题的，但是我用我自己的就是解析错误，代码很简单 就是一个按钮 点击请求网络 

    RxHttp.get("https://api.apiopen.top/getJoke?page=1&count=2&type=video")
                .asString()
                .as(RxLife.asOnMain(this))
                .subscribe(new Consumer<String>() {
                    @Override
                    public void accept(String s) throws Exception {
                        Tip.show(s);

                    }
                }, new OnError() {
                    @Override
                    public void onError(ErrorInfo error) throws Exception {
                        error.show(error.getErrorMsg());

                    }
                });

**Comment by liuwen370494581** [comment]
RxHttp.setOnConverter(s -> s); //设置数据转换器,可用于数据解密
        RxHttp.setOnParamAssembly(new Function<Param, Param>() {
            /**
             * <p>在这里可以为所有请求添加公共参数，也可以为url统一添加前缀或者后缀
             * <p>子线程执行，每次发送请求前都会被回调
             *
             * @param p Param
             * @return 修改后的Param对象
             */
            @Override
            public Param apply(Param p) {

                //根据不同请求添加不同参数
                if (p instanceof GetRequest) {

                } else if (p instanceof PostRequest) {

                } else if (p instanceof PutRequest) {

                } else if (p instanceof DeleteRequest) {

                }
                //为url 添加前缀或者后缀  并重新设置url
                //p.setUrl("");
                return p.add("versionName", "1.0.0")//添加公共参数
                        .addHeader("deviceType", "android"); //添加公共请求头
            }
        });
我发现加了这些就可以了   这些都是必须的？

**Comment by liujingxing** [comment]
非必须的，过滤RxHttp，看下完整日志截图。asString方法是不可能抛出data parse fail 错误的。

![image](https://user-images.githubusercontent.com/7237396/63918311-096f9900-ca6f-11e9-8f6d-725e067cc0cf.png)

**Comment by liuwen370494581** [comment]
我debug   是 t==null 报的解析错误

**Comment by liuwen370494581** [comment]
RxHttp.setOnConverter(s -> s); //设置数据转换器,可用于数据解密  被我调试出来了 是这个原因 我之前return null 了这个数据转换器是干嘛用的

**Comment by liujingxing** [comment]
如果Http返回的是密文，可通过此接口解密，并将解密后的字符串返回。

**Comment by liuwen370494581** [comment]
恩恩，谢谢耐心解答。
