### ISSUE TITLE
asObject方法找不到，求教

### ISSUE THREAD

**Issue by piaomiao8179** [liujingxing/rxhttp#320]
你好，大佬，这个方法是删除了吗，2.6.8版本找不到，能找到asClass等方法。
@liujingxing

**Comment by liujingxing** [comment]
`asClass`就是`asObject`的替代方法

**Comment by piaomiao8179** [comment]
asClass就是asObject的替代方法



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月8日(周一) 晚上10:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liujingxing/rxhttp] asObject方法找不到，求教 (Issue #320)




 
Closed #320.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
