### ISSUE TITLE
下载文件进度问题

### ISSUE THREAD

**Issue by Ekhui** [liujingxing/rxhttp#325]
版本:2.7.2 
timeout设置120s
协程
下载apk（用来更新） 有概率下载到99和100停住不动 无任何回调

**Comment by liujingxing** [comment]
大概率是你链接问题，换个下载链接试试

**Comment by Ekhui** [comment]
> 大概率是你链接问题，换个下载链接试试

链接没问题 祖传的cdn固定下载链接 不是每台机子会出现 概率大概在40分之一左右 每四十台有一台

**Comment by Ekhui** [comment]
> 大概率是你链接问题，换个下载链接试试

另外有个小bug 无伤大雅 就是debug模式的时候 进度不会回调 一直是0 但是release正常 不过无所谓就是了

**Comment by liujingxing** [comment]
你是不是添加了日志拦截器？

**Comment by Ekhui** [comment]
> 你是不是添加了日志拦截器？

懂了

**Comment by liujingxing** [comment]
取消日志拦截器后，再试试下载到99和100停住不动问题

**Comment by Ekhui** [comment]
> 取消日志拦截器后，再试试下载到99和100停住不动问题

拦截器是debug才生效的 出现无回调的基本都是正式版本 我先按你这个试试
