### ISSUE TITLE
请问json解析异常如何全局捕获？

### ISSUE THREAD

**Issue by hanchanpo13** [liujingxing/rxhttp#327]
我使用的是moshi,然后报错了，代码中我有看见你try-catch,但貌似不工作

**Comment by hanchanpo13** [comment]
com.squareup.moshi.JsonDataException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $
        at com.squareup.moshi.JsonUtf8Reader.beginArray(JsonUtf8Reader.java:142)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:79)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at rxhttp.wrapper.converter.MoshiConverter.convert(MoshiConverter.java:121)
        at rxhttp.wrapper.utils.Converter.convert(Converter.kt:45)
        at rxhttp.wrapper.parse.SimpleParser.onParse(SimpleParser.kt:20)
        at rxhttp.wrapper.utils.CallKt$await$4$2.onResponse(Call.kt:44)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by liujingxing** [comment]
代码中哪里的`try-catch`?，这个问题去解决，而不是怎么捕获，很明显，这是json字符串跟你定义的实体类结构不一致导致的

**Comment by hanchanpo13** [comment]
确实需要解决，但是我并不增确保后端数据不会出错，不能因为后端数据异常而引发手机应用崩溃，我跟了代码，你捕获到了异常，但是依然崩溃了发自我的华为手机-------- 原始邮件 --------发件人： liujingxing ***@***.***>日期： 2021年11月14日周日 23:13收件人： liujingxing/rxhttp ***@***.***>抄送： Jeven ***@***.***>, Author ***@***.***>主    题： Re: [liujingxing/rxhttp] 请问json解析异常如何全局捕获？ (Issue #327)

代码中哪里的try-catch?，这个问题去解决，而不是怎么捕获，很明显，这是json字符串跟你定义的实体类结构不一致导致的

**Comment by liujingxing** [comment]
引发崩溃，那就是没有处理异常，RxHttp+Await异常处理操作符你再看看[RxHttp ，比Retrofit 更优雅的协程体验](https://juejin.cn/post/6844904100090347528#heading-5)

**Comment by hanchanpo13** [comment]
捕获到了，但是只能返回泛型数据，没法返回code&msg信息

**Comment by hanchanpo13** [comment]
suspend inline fun <reified T : Any> get(
        path: String,
        params: Map<String, String> = mapOf()
    ): T? {
        return RxHttp.get(path)
            .addAll(params)
            .toResponse<T>()
            .tryAwait {
                Log.d("javen", "msg====>${it.msg},code====>${it.code}")
            }
    }

**Comment by hanchanpo13** [comment]
我在此处做了一层封装，想既能统一处理异常，还能将异常返回到每个具体接口调用处，然他们处理一些各自的异常反馈，如：

**Comment by hanchanpo13** [comment]
我在此处做了一层封装，想既能统一处理异常，还能将异常返回到每个具体接口调用处，然他们处理一些各自的异常反馈，如：
我在封装层用tryAwait 统一处理了登录失效，在上层具体接口请求，我将没有机会处理各自特殊异常反馈
// 封装层
suspend inline fun get(
path: String,
params: Map<String, String> = mapOf()
): T? {
return RxHttp.get(path)
.addAll(params)
.toResponse()
.tryAwait {
// 处理统一错误：如登录跳转
}
}

// 具体接口调用层
// 获取地区码列表
    suspend fun getCodeList() {
        val getCodeList = get<List<Region>>("/Api2/Ecustomers/getCode")
        // TODO 对异常做特殊反馈：如弹窗提示，特殊跳转等。。。
    }

**Comment by hanchanpo13** [comment]
我看了你的博客，想了下，我的需求应该可以实现，只是我对你的库使用有点误解，我的想法是这样：

**Comment by hanchanpo13** [comment]
还有解法2：不在自定义TypeParser中处理（保证职责单一），在封装层利用扩展函数重载tryAwait，代码如下：
```
// 在封装层重载tryAwait
    suspend fun <T> Await<T>.tryAwait(
        onCatchGlobal: ((Throwable) -> Boolean),
        onCatch: ((Throwable) -> Unit)?
    ): T? =
        try {
            await()
        } catch (e: Throwable) {
            if (!onCatchGlobal.invoke(e)) {
                onCatch?.invoke(e)
            }
            null
        }

// 封装层调用重载扩展函数
 suspend inline fun <reified T : Any> callGet(
        path: String,
        params: Map<String, String> = mapOf(),
        noinline onCatch: ((Throwable) -> Unit)? = null
    ): T? {
        return RxHttp.get(path)
            .addAll(params)
            .toResponse<T>()
            .tryAwait(this::doFailure, onCatch)
    }

// 调用层使用
 suspend fun getCodeList() {
        callGet<List<Region>>("/Api2/Ecustomers/getCode") {
            // TODO 对异常做特殊反馈：如弹窗提示，特殊跳转等。。。
        }
    }

```

**Comment by liujingxing** [comment]
> 捕获到了，但是只能返回泛型数据，没法返回code&msg信息

失败回调可以拿到code&msg信息，文档有介绍，如果成功回调也需要code&msg，解析器返回'Reaponse<T>'即可; 当然，你可以直接调用'toClass<Response<T>>()'方法，但需要你在回调处单独判断code

**Comment by liujingxing** [comment]
> 还有解法2：不在自定义TypeParser中处理（保证职责单一），在封装层利用扩展函数重载tryAwait，代码如下：
> ```
> // 在封装层重载tryAwait
>     suspend fun <T> Await<T>.tryAwait(
>         onCatchGlobal: ((Throwable) -> Boolean),
>         onCatch: ((Throwable) -> Unit)?
>     ): T? =
>         try {
>             await()
>         } catch (e: Throwable) {
>             if (!onCatchGlobal.invoke(e)) {
>                 onCatch?.invoke(e)
>             }
>             null
>         }
> 
> // 封装层调用重载扩展函数
>  suspend inline fun <reified T : Any> callGet(
>         path: String,
>         params: Map<String, String> = mapOf(),
>         noinline onCatch: ((Throwable) -> Unit)? = null
>     ): T? {
>         return RxHttp.get(path)
>             .addAll(params)
>             .toResponse<T>()
>             .tryAwait(this::globalCatch, onCatch)
>     }
> 
> fun globalCatch(t: Throwable) = t.run {
>         //处理全局异常
>         when (true) {
>             code == -1 -> {
>                 //  XXXXXXXXXXXXX
>                 true
>             }
>             code == -2 -> {
>                 //  XXXXXXXXXXXXX
>                 true
>             }
>             else -> false
>         }
>     }
> 
> // 调用层使用
>  suspend fun getCodeList() {
>         callGet<List<Region>>("/Api2/Ecustomers/getCode") {
>             // TODO 对异常做特殊反馈：如弹窗提示，特殊跳转等。。。
>         }
>     }
> 
> ```
> 
> 

扩展方法一直是我推荐的方式，但这跟自定义解析器并不矛盾，如果不自定义解析器，你将需要在回调处单独判断code，此时，你的异常回调就收不到业务code异常

**Comment by hanchanpo13** [comment]
> > 还有解法2：不在自定义TypeParser中处理（保证职责单一），在封装层利用扩展函数重载tryAwait，代码如下：
> > ```
> > // 在封装层重载tryAwait
> >     suspend fun <T> Await<T>.tryAwait(
> >         onCatchGlobal: ((Throwable) -> Boolean),
> >         onCatch: ((Throwable) -> Unit)?
> >     ): T? =
> >         try {
> >             await()
> >         } catch (e: Throwable) {
> >             if (!onCatchGlobal.invoke(e)) {
> >                 onCatch?.invoke(e)
> >             }
> >             null
> >         }
> > 
> > // 封装层调用重载扩展函数
> >  suspend inline fun <reified T : Any> callGet(
> >         path: String,
> >         params: Map<String, String> = mapOf(),
> >         noinline onCatch: ((Throwable) -> Unit)? = null
> >     ): T? {
> >         return RxHttp.get(path)
> >             .addAll(params)
> >             .toResponse<T>()
> >             .tryAwait(this::globalCatch, onCatch)
> >     }
> > 
> > fun globalCatch(t: Throwable) = t.run {
> >         //处理全局异常
> >         when (true) {
> >             code == -1 -> {
> >                 //  XXXXXXXXXXXXX
> >                 true
> >             }
> >             code == -2 -> {
> >                 //  XXXXXXXXXXXXX
> >                 true
> >             }
> >             else -> false
> >         }
> >     }
> > 
> > // 调用层使用
> >  suspend fun getCodeList() {
> >         callGet<List<Region>>("/Api2/Ecustomers/getCode") {
> >             // TODO 对异常做特殊反馈：如弹窗提示，特殊跳转等。。。
> >         }
> >     }
> > ```
> 
> 扩展方法一直是我推荐的方式，但这跟自定义解析器并不矛盾，如果不自定义解析器，你将需要在回调处单独判断code，此时，你的异常回调就收不到业务code异常

是的，解法2比较好，我没有抛弃在自定义解析器中统一定义code,只是没有在里面统一处理code下的反馈行为，因为必须保证上层业务的弹性
