### ISSUE TITLE
希望能增加配合moshi使用的例子

### ISSUE THREAD

**Issue by NeVaDaAAA** [liujingxing/rxhttp#328]
一直使用该库做网路请求, 也确实用起来很舒服 ,最近在替换moshi 希望作者能增加配合moshi使用的例子 ,感谢

**Comment by hanchanpo13** [comment]
赞同，目前kt在普及，moshi自然走到前台来了，需要丰富下moshi在rxhttp中的使用

**Comment by liujingxing** [comment]
要丰富什么？配置下moshi对应的converter就好了，详情[设置Converter](https://github.com/liujingxing/rxhttp/wiki/%E8%AE%BE%E7%BD%AEConverter)

**Comment by hanchanpo13** [comment]
并没有，解析会有问题，也许是我不会用

**Comment by NeVaDaAAA** [comment]
这是我的moshi引用
![image](https://user-images.githubusercontent.com/20659340/142569362-5140bc1e-b03f-475d-9fdc-7b497c9cd2e1.png)
这是rxhttp的引用
![image](https://user-images.githubusercontent.com/20659340/142569410-b92d961c-4dd6-485f-b9d8-9fa44bfaded2.png)
rxhttp设置
![image](https://user-images.githubusercontent.com/20659340/142569467-926c88c1-1b88-43b6-8055-ee19a7e8d169.png)
baseResponse设置
![image](https://user-images.githubusercontent.com/20659340/142569524-e477d97e-bb62-46a6-991e-fc3b62898d8b.png)
最外层pageBean设置
![image](https://user-images.githubusercontent.com/20659340/142569559-f4ccc227-7c4e-4aa4-8346-fde16e77d881.png)
postDetailBean设置
![image](https://user-images.githubusercontent.com/20659340/142569598-2f1dc80a-0afe-4b16-85be-2cc625cba515.png)
目前报错信息
![image](https://user-images.githubusercontent.com/20659340/142569695-37b6d807-b35f-4c35-bee8-520da4269c7d.png)
不知道是哪里出错了 第一次接触moshi

**Comment by liujingxing** [comment]
是使用kapt依赖的`"com.squareup.moshi:moshi-kotlin-codegen:1.12.0"`的吗？

**Comment by NeVaDaAAA** [comment]
是的
![image](https://user-images.githubusercontent.com/20659340/142571925-548e5eff-7fea-46d8-8d20-020bfecde00f.png)

**Comment by liujingxing** [comment]
你先直接用moshi去反序列化json字符串试试

**Comment by NeVaDaAAA** [comment]
![image](https://user-images.githubusercontent.com/20659340/142574392-2538cf43-29da-48c6-8c27-5b111bb4a650.png)
我感觉这里是不是得变换一下写法

**Comment by liujingxing** [comment]
不用怀疑，这就是你moshi的使用问题，需要注意的是，`com.squareup.moshi:moshi-kotlin-codegen:1.12.0`要跟`@JsonClass`注解在同一个module

**Comment by liujingxing** [comment]
> 并没有，解析会有问题，也许是我不会用
> 
> 如：Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.

你需要依赖`com.squareup.moshi:moshi-kotlin-codegen:1.12.0`

**Comment by liujingxing** [comment]
我简单介绍下吧
1、添加一下依赖
```java
kapt "com.squareup.moshi:moshi-kotlin-codegen:1.12.0"
implementation 'com.github.liujingxing.rxhttp:converter-moshi:2.7.3'
```
2、给实体类加上`@JsonClass(generateAdapter = true)`注解，要注意的是，`@JsonClass`注解跟`moshi-kotlin-codegen`要在同一个module，不然注解不会生效
3、最后给RxHttp设置一个`MoshiConverter`即可，详情查看[设置Converter](https://github.com/liujingxing/rxhttp/wiki/%E8%AE%BE%E7%BD%AEConverter)

**Comment by NeVaDaAAA** [comment]
感谢大佬的指导 问题确实是因为项目是模块化架构 但却只在base模块中引用
kapt "com.squareup.moshi:moshi-kotlin-codegen:1.12.0"
引起的 
PS:提示 如果gson替换moshi的话需要注意将@SerializedName 替换为 @Json(name =xxx)
