### ISSUE TITLE
个人功能

### ISSUE THREAD

**Issue by inshyma** [liujingxing/RxHttp#33]
如果我想在请求的时候,页面显示弹窗 请求结束弹窗关闭,并且同一个页面所有请求都结束的时候才关闭弹窗.这个RxLife有可以实现的方法么?

**Comment by liujingxing** [comment]
使用RxJava操作符对请求做并/串行操作，订阅回调显示弹窗，事件完成销毁弹窗

**Comment by inshyma** [comment]
那样的话 就和每次请求都敲一遍代码一样了,没有更好的方式么?

**Comment by liujingxing** [comment]
不是很明白你的需求

**Comment by inshyma** [comment]
就是我不想在每次网络请求都写一个弹窗 然后控制它的显示隐藏  想在RxHttp或者RxLife上实现公共的

**Comment by liujingxing** [comment]
你可以自定义观察者

**Comment by inshyma** [comment]
找到了Scope类 里面的两个方法应该可以实现功能
