### ISSUE TITLE
求助，网络请求如何获取返回数据中的Header

### ISSUE THREAD

**Issue by pangli** [liujingxing/rxhttp#331]
场景：登录接口服务端将验证用的Token放在了返回header中，需要解析header
我使用了全局自定义ResponseParser的方式解析返回数据，代码如下：
```kotlin
@Parser(name = "Response")
open class ResponseParser<T> : TypeParser<BaseResponse<T>> {

    protected constructor() : super()

    constructor(type: Type) : super(type)

    override fun onParse(response: Response): BaseResponse<T> {
        
        val data: BaseResponse<T> = response.convertTo(BaseResponse::class, *types)
        if (data.code != 0) {
            throw ParseException(data.code.toString(), data.message, response)
        }
        return data
    }
}
```
请问我需要怎样处理才能返回header中的数据？

**Comment by liujingxing** [comment]
`okhttp`的`api`你要去补补了, `response .headers()`获取所有响应头，`response.header("xxx")`获取某个响应头

**Comment by pangli** [comment]
这个我肯定是知道的，我想知道，我用以上公共处理返回数据，使用你的库我要怎么修改可以在回调中获取到header
![image](https://user-images.githubusercontent.com/7498978/144155927-93b1a9f1-f7ea-4a24-b6d6-f9bc0141469f.png)

**Comment by bingdu0** [comment]
> 这个我肯定是知道的，我想知道，我用以上自定义解析，直接返回的是实体类对象，使用你的库我要怎么修改可以在回调中获取到header中的数据 ![image](https://user-images.githubusercontent.com/7498978/144155927-93b1a9f1-f7ea-4a24-b6d6-f9bc0141469f.png)

可以使用拦截器

**Comment by pangli** [comment]
自定义拦截器，是可以，我也只是登录接口需要解析返回的header，感觉完全没必要定义拦截器，就想知道RxHttp这个库有没有更加简洁的方法，可以让我在某个特定接口的回调中直接获取到header数据，或者我做简单的修改就可以，既然用了这个库，就想从他的方法中解决问题

**Comment by liujingxing** [comment]
> 这个我肯定是知道的，我想知道，我用以上自定义解析，直接返回的是实体类对象，使用你的库我要怎么修改可以在回调中获取到header中的数据
> ![image](https://user-images.githubusercontent.com/7498978/144155927-93b1a9f1-f7ea-4a24-b6d6-f9bc0141469f.png)
> 
首先，你要知道，解析器泛型声明啥，就返回啥，你可以定义个实体类，将其返回即可

**Comment by pangli** [comment]
你的意思就是我在自定义实体中增加个公共字段，然后把header取出来，再放在实体中返回？

**Comment by liujingxing** [comment]
> 这个我肯定是知道的，我想知道，我用以上自定义解析，直接返回的是实体类对象，使用你的库我要怎么修改可以在回调中获取到header中的数据
> ![image](https://user-images.githubusercontent.com/7498978/144155927-93b1a9f1-f7ea-4a24-b6d6-f9bc0141469f.png)
> 

看你当前已经返回BaseReaponse对象，里面可以包含你想要的header

**Comment by liujingxing** [comment]
> 你的意思就是我在自定义实体中增加个公共字段，然后把header取出来，再放在实体中返回？

是的，里面当个map最直接

**Comment by pangli** [comment]
嗯嗯

**Comment by liujingxing** [comment]
那不需要自定义解析器，有asOkRespose/toOkResponse方法

**Comment by pangli** [comment]
嗯嗯，看到这个方法了
