### ISSUE TITLE
找不到符号 import kotlin.collections.MutableList

### ISSUE THREAD

**Issue by Beta116Beta** [liujingxing/rxhttp#332]
![image](https://user-images.githubusercontent.com/93580411/144374507-fca4fa82-ec51-4abf-a901-d16f1879324b.png)

![image](https://user-images.githubusercontent.com/93580411/144374574-7695b8cb-b452-4b99-ae33-223f6a9614c5.png)

2.7.0都是可以的，升级到2.8.0出现这个问题，不知道是不是我哪儿缺少了配置

**Comment by liujingxing** [comment]
用的是ksp还是kapt编译？不过，你可以移除`List`参数，内部会自动添加

**Comment by Beta116Beta** [comment]
@liujingxing  我使用的是ksp编译的，移除了List是可以的了
感谢大佬解答
