### ISSUE TITLE
Response 解析时泛型为 list 集合类型，返回的 data 为null，就会报错java.lang.NullPointerException

### ISSUE THREAD

**Issue by joklmT** [liujingxing/rxhttp#334]
Response<T> data = Converter.convertTo(response, Response.class, types);
        T t = data.getData(); //获取data字段
        if (t == null && types[0] == String.class) {
            /*
             * 考虑到有些时候服务端会返回：{"errorCode":0,"errorMsg":"关注成功"}  类似没有data的数据
             * 此时code正确，但是data字段为空，直接返回data的话，会报空指针错误，
             * 所以，判断泛型为String类型时，重新赋值，并确保赋值不为null
             */
            t = (T) data.getMsg();
        }

T为String时可以直接判断重新赋值，那请问下 泛型为 list 集合类型 时，该如何判断 重新赋值？

**Comment by liujingxing** [comment]
判断List跟String是一个意思。

但不建议这么干，这样做了，在成功回调还得判断List.size是否等于零，没有意义

list为null，你可以抛出一个具体异常，然后异常回调去处理
