### ISSUE TITLE
多渠道打包

### ISSUE THREAD

**Issue by 1843163412** [liujingxing/rxhttp#336]
生成的代码提示
e: D:\tools\electronic_photo\httputils\build\generated\ksp\debug\kotlin\rxhttp\wrapper\param\RxHttp.kt: (21, 1): Conflicting overloads: public inline fun <reified T> RxHttp<*, *>.executeClass(): T! defined in rxhttp.wrapper.param in file RxHttp.kt, public inline fun <reified T> RxHttp<*, *>.executeClass(): T! defined in rxhttp.wrapper.param in file RxHttp.kt
e: D:\tools\electronic_photo\httputils\build\generated\ksp\debug\kotlin\rxhttp\wrapper\param\RxHttp.kt: (23, 1): Conflicting overloads: public inline fun <reified T> BaseRxHttp.asList(): [ERROR : Error function type] defined in rxhttp.wrapper.param in file RxHttp.kt, public inline fun <reified T> BaseRxHttp.asList(): [ERROR : Error function type] defined in rxhttp.wrapper.param in file RxHttp.kt
e: D:\tools\electronic_photo\httputils\build\generated\ksp\debug\kotlin\rxhttp\wrapper\param\RxHttp.kt: (23, 53): Overload resolution ambiguity: 
public inline fun <reified T> BaseRxHttp.asClass(): Observable<TypeVariable(T)!>! defined in rxhttp.wrapper.param in file RxHttp.kt
public inline fun <reified T> BaseRxHttp.asClass(): Observable<TypeVariable(T)!>! defined in rxhttp.wrapper.param in file RxHttp.kt

**Comment by liujingxing** [comment]
打包前，clean下就好，详情https://github.com/liujingxing/rxhttp/issues/335
