### ISSUE TITLE
自定义parser 无法找到TypeParser 或者AbstractParser

### ISSUE THREAD

**Issue by seaCool96** [liujingxing/rxhttp#337]

**Comment by liujingxing** [comment]
升级kotlin插件

**Comment by seaCool96** [comment]
我不是使用kotlin 版本，没有java 版本的吗

**Comment by liujingxing** [comment]
跟你使不使用kotlin没关系，我说的是as的kotlin插件

**Comment by seaCool96** [comment]
你好，不升级到最新的无法使用吗,因为我的as 版本还是4.1的，kotlin 好像没法升到最新的

**Comment by liujingxing** [comment]
1.5.x及以上版本应该就可以

**Comment by seaCool96** [comment]
确实好了， 多谢

**Comment by llllonger** [comment]
升级到了1.7的最新的kotlin插件，仿照ResponseParser写的，但是toResponse还是找不到，这是什么情况啊

**Comment by liujingxing** [comment]
首先，你得确定`toResponse`方法是否有生成(查看下解析器构造方法是否有调用)，没有的话，查看[自定义Parser](https://github.com/liujingxing/rxhttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Parser)，有生成的，如果你使用ksp编译，IDE是不知道ksp生成的kotlin文件的，得手动告诉IDE，如下
```gradle
//让IDE知道ksp生成的kotlin代码
kotlin {
    sourceSets.debug {
        //如果通过productFlavors配置了多渠道，则配置 /../ksp/xxxDebug/kotlin
        kotlin.srcDir("build/generated/ksp/debug/kotlin")
    }
}
```

**Comment by llllonger** [comment]
使用kapt或者ksp是不是都需要加一下这个
kotlin {
    sourceSets.debug {
        //如果通过productFlavors配置了多渠道，则配置 /../ksp/xxxDebug/kotlin
        kotlin.srcDir("build/generated/ksp/debug/kotlin")
    }
}

**Comment by llllonger** [comment]
我看文档说的仅使用ksp时才需要，目前使用的是kapt，所以这个是没有添加的，不知道哪一步出的问题，在build里没有找到toResponse

**Comment by liujingxing** [comment]
> 我看文档说的仅使用ksp时才需要，目前使用的是kapt，所以这个是没有添加的，不知道哪一步出的问题，在build里没有找到toResponse

检查下解析器构造方法是否有调用，没有的话，查看[自定义Parser](https://github.com/liujingxing/rxhttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Parser)

**Comment by seaCool96** [comment]
![QQ图片20211229131945](https://user-images.githubusercontent.com/18422922/147629867-2cb54ff5-d55a-44e3-bdbd-7210c7eeec17.png)
你好，问下，如果我这数据返回体里面没有data，即data=null的情况下，你这都抛出异常吗（observableParser 里面会出现The onParse function returned a null value.）

**Comment by liujingxing** [comment]
#345
