### ISSUE TITLE
今天升到2.8.0，使用ksp插件的问题

### ISSUE THREAD

**Issue by timizhuoym** [liujingxing/rxhttp#339]
今天看到有新版本然后就升级了，也使用了ksp插件
![image](https://user-images.githubusercontent.com/24522660/146004805-be34ade2-0454-48f5-aca5-f50faf85493c.png)
配置正常，也在debug中出现了数据
![image](https://user-images.githubusercontent.com/24522660/146004949-f1ce9769-d339-4a3e-909e-61adbe3c2d4d.png)
但是出现了两个文件夹，以前的没注意，是不是这样，但是以前自定义Parser可以使用，现在运行也可以使用，但是在代码里一直报错，请问有没有解决方案？
![image](https://user-images.githubusercontent.com/24522660/146005184-6ef1427e-d95e-456f-be6a-93ae65ab1d1f.png)
![image](https://user-images.githubusercontent.com/24522660/146005343-87863e21-62d0-4e7c-8fd9-ebf449def10f.png)
大神，帮帮忙，全报红，可以运行，但是后续如果有改动，将没有任何提示了

**Comment by liujingxing** [comment]
gradle 插件4.x版本的话，继续在`android.defaultConfig`下编辑ksp生成的kotlin代码
```gradle
sourceSets.debug {
    java.srcDir("build/generated/ksp/debug/kotlin")
}
```
gradle 插件7.x及以上版本才使用`kotlin.srcDir("build/generated/ksp/debug/kotlin")`

**Comment by timizhuoym** [comment]
我的gradle版本 7.2



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月14日(周二) 晚上10:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liujingxing/rxhttp] 今天升到2.8.0，使用ksp插件的问题 (Issue #339)




 
gradle 插件4.x版本的话，继续在android.defaultConfig下编辑ksp生成的kotlin代码
 sourceSets.debug {     java.srcDir("build/generated/ksp/debug/kotlin") }
 
gradle 插件7.x及以上版本才使用kotlin.srcDir("build/generated/ksp/debug/kotlin")
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by timizhuoym** [comment]
谢谢大佬，改成7.0.4可以了，第一次用ksp，见笑了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月14日(周二) 晚上10:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liujingxing/rxhttp] 今天升到2.8.0，使用ksp插件的问题 (Issue #339)




 
gradle 版本跟gradle插件版本是两个概念
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
