### ISSUE TITLE
如何搭配RxWorker使用

### ISSUE THREAD

**Issue by guominfang** [liujingxing/rxhttp#340]

**Comment by liujingxing** [comment]
你可以问的再细点，亦或者贴上的你的代码

**Comment by guominfang** [comment]
我想实现的是，使用RxHttp，配合Work库来实现来在后台中进行下载，并且通知进度，

代码：
![image](https://user-images.githubusercontent.com/24568042/147054193-7d06493c-5ff1-471b-8ce5-dc8be41c1d0a.png)

如图，RxWork使用的是：Single<Result>

RxHttp使用的Observable<String>

**Comment by liujingxing** [comment]
RxJava 提供了 Observable 转 Single的方法`single`

**Comment by guominfang** [comment]
这样一看，是需要去看看Rxjava详细使用咯
