### ISSUE TITLE
中文参数

### ISSUE THREAD

**Issue by 79660095** [liujingxing/rxhttp#342]
求教，post参数为中文时会被转为一些符号之类的%，这个应该怎么处理。

**Comment by liujingxing** [comment]
计算机不认识中文，转码是必须的，你的问题应该不是这个，postman可以先去调通

**Comment by 79660095** [comment]
request start 打印的日志 参数部分被转译了，类似这样E5%8F%8B%5D%29 这个我看到是叫什么url编码，这个后台那边收到是需要他们自己解码吗，如果后台一定要求到他哪里是中文这个是不是我们处理不了，一定要让他们自己解呢。求点解一下感谢

**Comment by liujingxing** [comment]
如果你是表单请求(postForm)，中文是必须会被编码的，后台收到用UrlDecoder类解码下就好了；如果传递的是json字符串(postJson)，后台收到byte数组，用UTF-8转字符串就好。

**Comment by 79660095** [comment]
好的谢谢， 这个关了吧。
