### ISSUE TITLE
文件下载进度

### ISSUE THREAD

**Issue by YQcharlse** [liujingxing/rxhttp#344]
文件下载拿不到文件的总字节大小。
 版本 rxhttp:2.8.2

**Comment by liujingxing** [comment]
你接口问题  详情查看https://github.com/liujingxing/rxhttp/issues/283

**Comment by YQcharlse** [comment]
好的谢谢

**Comment by YQcharlse** [comment]
使用ksp 导包 RxHttp都找不到，但是生成了。
这个对   gradle 版本 有要求吗？

**Comment by liujingxing** [comment]
> 使用ksp 导包 RxHttp都找不到，但是生成了。 这个对 gradle 版本 有要求吗？

请重新创建issue
