### ISSUE TITLE
使用ksp  使用最新的rxhttp 2.8.2

### ISSUE THREAD

**Issue by YQcharlse** [liujingxing/rxhttp#345]
使用ksp 导包 RxHttp都找不到，但是生成了。 这个对 gradle 版本 有要求吗？

**Comment by liujingxing** [comment]
需要你告知IDE ksp生成的kotlin代码目录  ，详情https://github.com/liujingxing/rxhttp/issues/339

**Comment by YQcharlse** [comment]
![image](https://user-images.githubusercontent.com/42264736/147811470-4e8de5a5-7d45-4e1d-a379-d1394e0290e9.png)

**Comment by YQcharlse** [comment]
//让IDE知道ksp生成的kotlin代码
kotlin {
    sourceSets.debug {
        //如果通过productFlavors配置了多渠道，则配置 /../ksp/xxxDebug/kotlin
        kotlin.srcDir("build/generated/ksp/debug/kotlin")
    }
} 


使用这个

**Comment by YQcharlse** [comment]
kotlin  版本1.6.10   gradle-6.8.3  gradle:4.1.3

**Comment by liujingxing** [comment]
你平时写代码用release环境？

**Comment by YQcharlse** [comment]
不是

**Comment by liujingxing** [comment]
看你代码生成就在`release`目录下，自己检查下

**Comment by YQcharlse** [comment]
> 不是
就是测试点东西，切换到了release  
![image](https://user-images.githubusercontent.com/42264736/147811751-9d09e584-830d-4e3b-86c7-da72392e22b1.png)

**Comment by liujingxing** [comment]
gradle 插件4.x版本的话，在`android.defaultConfig`下标记ksp生成的kotlin代码
```gradle
sourceSets.debug {
    java.srcDir("build/generated/ksp/debug/kotlin")
}
```
gradle 插件7.x及以上版本才使用`kotlin.srcDir("build/generated/ksp/debug/kotlin")`

**Comment by YQcharlse** [comment]
ok明白了
