### ISSUE TITLE
老哥，我这一直报注解的错误

### ISSUE THREAD

**Issue by Martin-zhq** [liujingxing/rxhttp#348]
Task :campus:kaptDebugKotlin
/Users/zhq/git/Android/nmkq220126/campus/build/generated/source/kapt/debug/rxhttp/ObservableCall.java:14: 错误: 找不到符号
abstract class ObservableCall extends Observable<Progress> {
                                      ^
  符号: 类 Observable
/Users/zhq/git/Android/nmkq220126/campus/build/generated/source/kapt/debug/rxhttp/ObservableParser.java:27: 错误: 找不到符号
final class ObservableParser<T> extends Observable<T> {
                                        ^
  符号: 类 Observable
What went wrong:
Execution failed for task ':campus:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

请问这可能是什么原因啊，我往前翻了之前的issue，设置了butterknife的版本为10.1.0，但是没用，另外我翻完日志也没发现提示其他的错误。我用了inspect code也排查了工程里其他的错误，但是每次rebuild都报这个错误；我gradle版本号是6.5，as是4.0的，kotlin是1.6.10的

**Comment by liujingxing** [comment]
你要自己依赖rxjava，并通过rxhttp_rxjava参数传递rxjava版本号

**Comment by Martin-zhq** [comment]
对了，我这工程是Java工程，引入的kotlin的module里边的build是下面这样的

plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-android-extensions'
    id 'com.jakewharton.butterknife'
    //annotationProcessor无需依赖额外插件
    // kapt/ksp 选其一
     id 'kotlin-kapt'
//    id("com.google.devtools.ksp") version "1.6.10-1.0.2"
}

//kotlin {
//    sourceSets.debug {
//        kotlin.srcDir("/../ksp/HnxxtDebug/kotlin")
//    }
//}

android {
    useLibrary 'org.apache.http.legacy'

    compileSdkVersion 29
    buildToolsVersion '29.0.2'

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 27
        aaptOptions.cruncherEnabled = false
        aaptOptions.useNewCruncher = false

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [
                        rxhttp_package: 'rxhttp',   //非必须，指定RxHttp类包名
                        //传入你依赖的rxjava版本，可传入rxjava2、rxjava3，依赖RxJava时必须
                        rxhttp_rxjava: 'rxjava3'

                ]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

//ksp {
//    arg("rxhttp_rxjava", "3.1.1")
//    arg("rxhttp_package", "rxhttp")
//}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    //Kotlin 组件库
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.6.10"
    //网络库
    implementation project(':asyncHttpClient')
    //日历控件
    implementation 'com.haibin:calendarview:3.6.8'
    //腾讯X5:Webview
    implementation files('libs/tbs_sdk_thirdapp_v3.1.0.1034_43100_sharewithdownload_obfs_20170301_182143.jar')
    //ProtoBuf
    compile files('libs/protobuf-java-2.5.0.jar')
    //Gson解析
    implementation 'com.google.code.gson:gson:2.8.5'
    //Butterknife Plugin
    implementation 'com.jakewharton:butterknife:10.1.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.1.0'
    //XpopupWindow 弹窗遮罩层
    implementation 'com.github.li-xiaojun:XPopup:2.3.5'
    implementation 'com.github.li-xiaojun:XPopupExt:0.0.6'
    //EventBus 事件总线
    implementation("org.greenrobot:eventbus:3.3.1")
    //BaseQuickAdapter RecyclerView简易适配器
    implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.50'
    //Glide图片加载框架
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    //QMUI
    implementation 'com.qmuiteam:qmui:2.0.0-alpha10'
    //RXHttp
    implementation 'com.github.liujingxing.rxhttp:rxhttp:2.8.3'
    implementation 'com.squareup.okhttp3:okhttp:4.9.0' //rxhttp v2.2.2版本起，需要手动依赖okhttp
    kapt 'com.github.liujingxing.rxhttp:rxhttp-compiler:2.8.3' //生成RxHttp类，纯Java项目，请使用annotationProcessor代替kapt

    implementation 'com.github.liujingxing.rxlife:rxlife-coroutine:2.1.0' //管理协程生命周期，页面销毁，关闭请求

    //rxjava2   (RxJava2/Rxjava3二选一，使用asXxx方法时必须)
    implementation 'io.reactivex.rxjava2:rxjava:2.2.8'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'com.github.liujingxing.rxlife:rxlife-rxjava2:2.1.0' //管理RxJava2生命周期，页面销毁，关闭请求

    //rxjava3
//    implementation 'io.reactivex.rxjava3:rxjava:3.0.6'
//    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
//    implementation 'com.github.liujingxing.rxlife:rxlife-rxjava3:2.1.0' //管理RxJava3生命周期，页面销毁，关闭请求

    //非必须，根据自己需求选择 RxHttp默认内置了GsonConverter
    implementation 'com.github.liujingxing.rxhttp:converter-fastjson:2.8.3'
    implementation 'com.github.liujingxing.rxhttp:converter-jackson:2.8.3'
    implementation 'com.github.liujingxing.rxhttp:converter-moshi:2.8.3'
    //implementation 'com.github.liujingxing.rxhttp:converter-protobuf:2.6.1'
    //implementation 'com.github.liujingxing.rxhttp:converter-simplexml:2.6.1'
}

**Comment by Martin-zhq** [comment]
哦哦，好的，多谢老哥

**Comment by Martin-zhq** [comment]
kapt {
    arguments {
        arg("rxhttp_rxjava", "3.1.1") //可传入rxjava2、rxjava3或具体版本号，如 3.1.1
//            arg("rxhttp_package", "rxhttp") //设置RxHttp相关类的包名，多module依赖时，需要配置不同的包名
    }
}
老哥，我再请教个问题，这个注释这一行，我放开就报错：Unresolved reference: RxHttp
我分开去写：
kapt {
    arguments {
        arg("rxhttp_rxjava", "3.1.1") //可传入rxjava2、rxjava3或具体版本号，如 3.1.1
    }
}
kapt {
    arguments {
        arg("rxhttp_package", "rxhttp") //设置RxHttp相关类的包名，多module依赖时，需要配置不同的包名
    }
}
也是报上面那错

**Comment by liujingxing** [comment]
rxhttp_package是指定RxHttp等类的包名，不指定默认为rxhttp.wrapper.param，导入RxHttp类时看下路径就知道了

**Comment by Martin-zhq** [comment]
好的，谢谢大哥
