### ISSUE TITLE
网络接口延时比较高，怎么设置超时时间

### ISSUE THREAD

**Issue by xiaoyao521** [liujingxing/RxHttp#35]

**Comment by liujingxing** [comment]
也可以对单个请求设置超时时间，在调用asXXX方法后，通过timeout设置超时时间，但这个超时时间要小于OKHttpClient对象中设置的超时时间

**Comment by xiaoyao521** [comment]
如果我不设置okhttpclient的超时时间的话只设置timeout的话也是可以的吧

**Comment by liujingxing** [comment]
RxHttp内部默认的读、写、连接超时时间都是10s，imeout设置的话，要小于10s，才能保证有效

**Comment by xiaoyao521** [comment]
如果我需要更长的超时时间只能通过Okhttpclient了，对吧

**Comment by liujingxing** [comment]
对的
