### ISSUE TITLE
请问post直接提交数组怎么提交？

### ISSUE THREAD

**Issue by piaomiao8179** [liujingxing/rxhttp#350]
@liujingxing 
`RxHttp.postEncryptJson(Constant.categorySort).addXXX("key", [])`
我看现在post的请求体参数都是以map形式的，如果我需要以下传递方式，请问有什么办法吗？
`RxHttp.postEncryptJson(Constant.categorySort).addXXX([])`

**Comment by liujingxing** [comment]
`RxHttp.postBody("...").setBody(Object)`提交任意对象；或者`RxHttp.postJsonArray("...").addAll(List)`提交json数组

**Comment by piaomiao8179** [comment]
> `RxHttp.postBody("...").setBody(Object)`提交任意对象；或者`RxHttp.postJsonArray("...").addAll(List)`提交json数组

**Comment by piaomiao8179** [comment]
好的 谢谢

**Comment by piaomiao8179** [comment]
@liujingxing 大佬，我现在重写了PostEncryptJsonParam继承JsonParam，进行了加密和防重放，如果我用postJsonArray的话需要怎样继承呢。
`@Param(methodName = "postEncryptJson")
public class PostEncryptJsonParam extends JsonParam {

    public PostEncryptJsonParam(String url) {
}

}`

**Comment by liujingxing** [comment]
`JsonArrayParam`

**Comment by piaomiao8179** [comment]
收到 谢谢
