### ISSUE TITLE
Add RxHttp dependency ,add to project or app gradle

### ISSUE THREAD

**Issue by TangPinJia** [liujingxing/rxhttp#352]
Build file '/Users/good/Documents/project/reader_android/app/build.gradle' line: 10

A problem occurred evaluating project ':app'.
> Could not find method kotlin() for arguments [build_btkt3yfhpywrfxi6gpzw9yznb$_run_closure1@61b8763] on project ':app' of type org.gradle.api.Project.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method kotlin() for arguments [build_btkt3yfhpywrfxi6gpzw9yznb$_run_closure1@61b8763] on project ':app' of type org.gradle.api.Project

**Comment by liujingxing** [comment]
add ksp plugin
```gradle
plugins {
    id("com.google.devtools.ksp") version "1.6.10-1.0.2"
}
```

**Comment by TangPinJia** [comment]
同学你好，邮件已收到，祝你生活愉快

**Comment by TangPinJia** [comment]
I have ，
![image](https://user-images.githubusercontent.com/33646260/154194333-e11206b4-f9be-4cb1-b8f6-6d1a807f32e8.png)

**Comment by liujingxing** [comment]
https://github.com/liujingxing/rxhttp/issues/345#issuecomment-1003305360

**Comment by TangPinJia** [comment]
> [#345 (comment)](https://github.com/liujingxing/rxhttp/issues/345#issuecomment-1003305360)

老项目，没用到kotlin也需要指定吗，我看文档写着这些配置是必须的，不是可选的

**Comment by liujingxing** [comment]
没用到kotlin，就不要用ksp，用annotationProcessor就好，[ksp、kapt、annotationProcessor 用法及区别](https://github.com/liujingxing/rxhttp/wiki/ksp%E3%80%81kapt%E3%80%81annotationProcessor-%E7%94%A8%E6%B3%95%E5%8F%8A%E5%8C%BA%E5%88%AB)

**Comment by TangPinJia** [comment]
感谢你的框架和花时间回复，我建议你把这些集成的弄到readme里面，这样你就不用一一回复不熟悉集成的用户了



---Original---
From: ***@***.***&gt;
Date: Wed, Feb 16, 2022 12:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [liujingxing/rxhttp] Add RxHttp dependency ,add to project or appgradle (Issue #352)




 
没用到kotlin，就不要用ksp，用annotationProcessor就好，ksp、kapt、annotationProcessor 用法及区别
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liujingxing** [comment]
认真看readme，都有

**Comment by TangPinJia** [comment]
> 认真看readme，都有

respect
