### ISSUE TITLE
RxHttp 类找不到 

### ISSUE THREAD

**Issue by TangPinJia** [liujingxing/rxhttp#354]
![image](https://user-images.githubusercontent.com/33646260/154234179-22e1933e-912d-413e-a337-49fd81ff18af.png)

**Comment by liujingxing** [comment]
[首次集成RxHttp，却没有RxHttp这个类?](https://github.com/liujingxing/rxhttp/wiki/FAQ#%E9%A6%96%E6%AC%A1%E9%9B%86%E6%88%90rxhttp%E5%8D%B4%E6%B2%A1%E6%9C%89rxhttp%E8%BF%99%E4%B8%AA%E7%B1%BB)

**Comment by TangPinJia** [comment]
![image](https://user-images.githubusercontent.com/33646260/154236115-b3434241-b66c-4afa-9394-c1c2cbe23271.png)

**Comment by TangPinJia** [comment]
> [首次集成RxHttp，却没有RxHttp这个类?](https://github.com/liujingxing/rxhttp/wiki/FAQ#%E9%A6%96%E6%AC%A1%E9%9B%86%E6%88%90rxhttp%E5%8D%B4%E6%B2%A1%E6%9C%89rxhttp%E8%BF%99%E4%B8%AA%E7%B1%BB)

是的，集成之后新建了一个类使用了@DefaultDomain，rebuild了项目，依然没有RxHttp这个类

**Comment by liujingxing** [comment]
仔细看我发的链接，你会找到答案

**Comment by TangPinJia** [comment]
> 仔细看我发的链接，你会找到答案

![image](https://user-images.githubusercontent.com/33646260/154238772-5f5bc744-3b9b-42ab-be94-1772ed38c796.png)
这俩不是和ksp任选一个吗，我用了ksp，这两还要弄进去吗

**Comment by liujingxing** [comment]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/7237396/154240510-61f711f3-2eef-4474-a396-d548119d11a6.png">
看这个

**Comment by TangPinJia** [comment]
> <img alt="image" width="930" src="https://user-images.githubusercontent.com/7237396/154240510-61f711f3-2eef-4474-a396-d548119d11a6.png">
> 
> 看这个

文档我看完了，不是上面的原因，我看下ksp，应该是因为ksp配置问题

**Comment by liujingxing** [comment]
打开`build/generated/ksp/debug/kotlin`目录，看看`RxHttp`类在不在，如果在，引用不到，需要你告诉IDE 生成的kotlin文件目录

**Comment by TangPinJia** [comment]
> 打开`build/generated/ksp/debug/kotlin`目录，看看`RxHttp`类在不在，如果在，引用不到，需要你告诉IDE 生成的kotlin文件目录

谢谢，是因为我的路径不一样
![image](https://user-images.githubusercontent.com/33646260/154250014-84bedba5-07be-481f-8182-8ead82eb8f2e.png)

**Comment by TangPinJia** [comment]
> > 打开`build/generated/ksp/debug/kotlin`目录，看看`RxHttp`类在不在，如果在，引用不到，需要你告诉IDE 生成的kotlin文件目录
> 
> 谢谢，是因为我的路径不一样 ![image](https://user-images.githubusercontent.com/33646260/154250014-84bedba5-07be-481f-8182-8ead82eb8f2e.png)

也就是说，我如果上线，这个路径还得改

**Comment by liujingxing** [comment]
上线不用改，直接打包就行

**Comment by TangPinJia** [comment]
> 上线不用改，直接打包就行

也就是说，release模式下，是不需要通过build文件引用RxHttp的是吧

**Comment by liujingxing** [comment]
> > 上线不用改，直接打包就行
> 
> 也就是说，release模式下，是不需要通过build文件引用RxHttp的是吧

不是，打包会自动包含build文件夹下的类，打包不需要引用，只有你写代码的时候需要引用

**Comment by TangPinJia** [comment]
明白，谢谢解答



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月16日(周三) 晚上7:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [liujingxing/rxhttp] RxHttp 类找不到  (Issue #354)




   
上线不用改，直接打包就行
  
也就是说，release模式下，是不需要通过build文件引用RxHttp的是吧
  
不是，打包会自动包含build文件夹下的类，打包不需要引用，只有你写代码的时候需要引用
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liujingxing** [comment]
#446

**Comment by TangPinJia** [comment]
同学你好，邮件已收到，祝你生活愉快

**Comment by cyjeen** [comment]
太费劲了，搞了整整两天都找不到RxHttp，某个时候不小心生成了RxHttp，但是也没有addClass, addQuery, toObservable等这些东西。今天按流程升级到3.1.1，按github步骤，每个步聚都不敢省，生怕生成不了RxHttp，可以很遗憾，最后还是没有生成RxHttp，而且怎么搞都没有，这个东西就不是让人拿来用的，就是用来折磨人的，还不如直接上okhttp，太费劲，毫无实用性，比供个祖宗都更难伺候。

**Comment by TangPinJia** [comment]
同学你好，邮件已收到，祝你生活愉快

**Comment by liujingxing** [comment]
> 太费劲了，搞了整整两天都找不到RxHttp，某个时候不小心生成了RxHttp，但是也没有addClass, addQuery, toObservable等这些东西。今天按流程升级到3.1.1，按github步骤，每个步聚都不敢省，生怕生成不了RxHttp，可以很遗憾，最后还是没有生成RxHttp，而且怎么搞都没有，这个东西就不是让人拿来用的，就是用来折磨人的，还不如直接上okhttp，太费劲，毫无实用性，比供个祖宗都更难伺候。

啥时候有`addClass`方法？我怎么不知道，另外，`toObservable`方法是RxJava实现，需要使用者额外配置，文档写的很清楚，遇到问题，请查看[常见问题列表](https://github.com/liujingxing/rxhttp/wiki/FAQ#%E4%BD%BF%E7%94%A8%E4%BA%86%E7%9B%B8%E5%85%B3%E6%B3%A8%E8%A7%A3%E6%B2%A1%E7%94%9F%E6%88%90%E7%9B%B8%E5%85%B3%E6%96%B9%E6%B3%95)，别上来就一顿喷
