### ISSUE TITLE
 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type OkHttpClient.Builder

### ISSUE THREAD

**Issue by GrapefruitBrother** [liujingxing/rxhttp#355]
okhttp版本:3.12.13，rebuild会出现"Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type OkHttpClient.Builder?"

**Comment by liujingxing** [comment]
rxhttp版本号多少

**Comment by GrapefruitBrother** [comment]
2.8.3

**Comment by liujingxing** [comment]
版本兼容问题，仅ksp编译会有这个问题，你暂时可用kapt编译。下个版本兼容

**Comment by GrapefruitBrother** [comment]
已解决，感谢！

**Comment by 603751448** [comment]
V2.8.8  ksp编译，出现了这个问题
Type mismatch: inferred type is OkHttpClient? but OkHttpClient was expected
