### ISSUE TITLE
postbody方法setbody了一个xml进去自动带上了斜杠

### ISSUE THREAD

**Issue by 1226362423** [liujingxing/rxhttp#356]
``` 
RxHttp.postBody("")
                .setBody(xml)
                .toStr()
                .awaitResult {
                    Log.i(TAG,"返回："+it)
                }
                .onFailure {
                    Log.e(TAG,"错误"+it.message)
                }
```
xml 请求体本来是没有斜杠的 请求的时候自动加上了 导致服务器解析不出来：
```
<Transaction xmlns=\"http://www.opengis.net/wfs\" service=\"WFS\" version=\"1.1.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd\"><Insert><test:gis_osm_buildings_a_free_1 xmlns:test=\"test\"><test:geom><MultiPolygon xmlns=\"http://www.opengis.net/gml\" srsName=\"EPSG:4326\"><polygonMember><Polygon srsName=\"EPSG:4326\"><exterior><LinearRing srsName=\"EPSG:4326\"><posList srsDimension=\"2\">113.0308706 28.1385212 113.0311424 28.1383194 113.0311532 28.1382216 113.0308456 28.13784 113.0306096 28.1381207</posList></LinearRing></exterior></Polygon></polygonMember></MultiPolygon></test:geom></test:gis_osm_buildings_a_free_1></Insert></Transaction>
```

**Comment by liujingxing** [comment]
请求日志截图；你是要发送xml格式数据？

**Comment by 1226362423** [comment]
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/15227754/155276522-b4724c87-325d-461d-bb40-6c9a7025345f.png">

对的 是要发送xml数据

**Comment by liujingxing** [comment]
那你要配置XmlConverter，详情https://github.com/liujingxing/rxhttp/wiki/%E8%AE%BE%E7%BD%AEConverter

**Comment by 1226362423** [comment]
加上了 成下面这样了 服务器报400了
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/15227754/155278723-17c4808b-a488-41d5-ab11-ab0a7b6fde9c.png">


`RxHttp.postBody("")
                .setXmlConverter()
                .setBody(xml)
                .toStr()
                .awaitResult {
                    Log.i(TAG,"返回："+it)
                }
                .onFailure {
                    Log.e(TAG,"错误"+it.message)
                }`

**Comment by liujingxing** [comment]
你这个xml是什么对象？String？是的话，调用`setBody(String,MediaType)`就好，第二个参数传`MediaType.get("application/xml; charset=UTF-8")`；此时XmlConverter就没必要设置

**Comment by 1226362423** [comment]
对的 string对象。 方法可以
