### ISSUE TITLE
切换服务器地址后的第一个请求很慢

### ISSUE THREAD

**Issue by timizhuoym** [liujingxing/rxhttp#357]
项目中设计到使用第三方接口，首先登录和首页用的是我们自己的服务器接口，请求响应很快，使用的是默认域名方式，当切换第三方接口请求时，第一次非常慢达到了30秒，使用的是手写全域名的方式，后续再请求就会很快，请问是什么原因呢？
![image](https://user-images.githubusercontent.com/24522660/155345432-a770a02e-b603-4ebc-bffc-f290bd22b590.png)

**Comment by timizhuoym** [comment]
就第一次切换复现率特别高，我用response.receivedResponseAtMillis-response.sentRequestAtMillis这个计算出的耗时就很少，图上的30秒时这种计算出的耗时也只有57ms，很奇怪，可能是接口偶发性问题吧，这么晚谢谢回复，我再多试试

**Comment by liujingxing** [comment]
每次有问题时，时间都是30秒左右？自己是否有添加拦截器，有的话，去掉试试。

**Comment by timizhuoym** [comment]
我把自己写在自定义okhttp对象中的拦截器去掉了，写在了您提供的方法中，但是依然会出现这个问题，我甚至将头部直接写在需要的接口处，使用rxhttp.addHeader依然会出现这种问题，95%都是在第一次切换服务器时出现，是的每次有问题都是30秒，然而我设置的超时也才15秒，使用上述的response计算得到的却是57ms。
![image](https://user-images.githubusercontent.com/24522660/155450215-5f7ba0c3-bfa3-4a46-b244-b92ee8b53501.png)

**Comment by liujingxing** [comment]
可以写个Demo给我

**Comment by timizhuoym** [comment]
可以提供个邮箱吗？我直接发您，麻烦您尽量不要外泄

**Comment by liujingxing** [comment]
直接加我微信吧  ljx-studio

**Comment by HoneyWorld** [comment]
曾经做过某个项目，也是第一次请求很慢，但是成功后下面的请求就快了，不知道是不是域名解析的问题

**Comment by liujingxing** [comment]
> 曾经做过某个项目，也是第一次请求很慢，但是成功后下面的请求就快了，不知道是不是域名解析的问题

跟进了一下，很鸿蒙有关，直接用okhttp请求正常；Android 系统也正常
