### ISSUE TITLE
如何设置拦截器？

### ISSUE THREAD

**Issue by wjsir** [liujingxing/rxhttp#358]
我想在请求的header中全局加入token，并且根据响应的header来判断加密状态然后解密，我看了文档中的加解密，但是不能拿到全局的响应，只能获取到响应的内容，请问响应的header如何获取？

**Comment by liujingxing** [comment]
RxHttpPlugins.init(OkHttpClient)   自定义OkHttpClient对象以添加拦截器

**Comment by wjsir** [comment]
> 

感谢
