### ISSUE TITLE
能不能设置baseResponse类，用来承载status code和message等请求信息，现在每一个model类都得继承一个baseResponse

### ISSUE THREAD

**Issue by TangPinJia** [liujingxing/rxhttp#359]
因为接口返回肯定会有状态码等，直接等于重复写了一个model类，太多余了

**Comment by liujingxing** [comment]
[自定义解析器](https://github.com/liujingxing/rxhttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Parser)用的就是[BaseResponse类](https://github.com/liujingxing/rxhttp/blob/master/app/src/main/java/com/example/httpsender/entity/Response.java)

**Comment by TangPinJia** [comment]
好的
