### ISSUE TITLE
Failed to resolve: com.rxjava.rxhttp:rxhttp:1.1.0

### ISSUE THREAD

**Issue by jksfood** [liujingxing/RxHttp#36]
你好，请问这个版本的还有吗 ？ 我在新的电脑上依赖这个文件一直不成功， 但是如果换成 1.2.4 的版本， 相关类又会报错

**Comment by liujingxing** [comment]
1.1.0版本已经不在了。建议你直接升级到1.2.4，功能更加抢到，且更稳定。升级过程问题可以在群里(378530627)反馈，我会第一时间回复你。

**Comment by liujingxing** [comment]
1.1.0版本已经不在了。建议你直接升级到1.2.4，功能更加强大，且更稳定。升级过程问题可以在群里(378530627)反馈，我会第一时间回复你。
