### ISSUE TITLE
关于最新版使用ResponseParser生成RxHttp报错的问题

### ISSUE THREAD

**Issue by Jeremyzwc** [liujingxing/rxhttp#361]
兄弟，想请教一个问题，关于设置ResponseParser，我定义了一个BaseResponse ，所有的返回类型实体都会继承它，所以声明成这样的：`ResponseParser<T extends BaseResponse>`，这样的设置在旧版本2.2.4是没有问题，一直使用了快两年，最近升级到最新版2.8.4，只要编译就提示RxHttp中的asResponseList(Class<T> type)报错，错误: 不兼容的类型: 推论变量 T#1 具有不兼容的上限：return asParser(new ResponseParser<>(typeList))。OKhttp使用的4.9.1版本，RxJava使用的是RxJava3最新版本。

下面是我的代码：

```java
@Parser(name = "Response")
public class ResponseParser<T extends BaseResponse> extends AbstractParser<T> {

    /**
     * 此构造方法适用于任意Class对象，但更多用于带泛型的Class对象，如：List<Student>
     * <p>
     * 用法:
     * Java: .asParser(new ResponseParser<List<Student>>(){})
     * Kotlin: .asParser(object : ResponseParser<List<Student>>() {})
     * <p>
     * 注：此构造方法一定要用protected关键字修饰，否则调用此构造方法将拿不到泛型类型
     */
    protected ResponseParser() {
        super();
    }

    /**
     * 此构造方法仅适用于不带泛型的Class对象，如: Student.class
     * <p>
     * 用法
     * Java: .asParser(new ResponseParser<>(Student.class))   或者  .asResponse(Student.class)
     * Kotlin: .asParser(ResponseParser(Student::class.java)) 或者  .asResponse(Student::class.java)
     */
    public ResponseParser(Type type) {
        super(type);
    }

    @SuppressWarnings("unchecked")
    @Override
    public T onParse(@NotNull Response response) throws IOException {
        saveServerTime(response);
        T data = convert(response, mType);

        if (data == null) {
            //code不等于0，说明数据不正确，抛出异常
            throw new ParseException(String.valueOf(ErrorCode.RESPONSE_NULL), "response is null", response);
        }

        if (!isSuccess(data.getCode(), data.getStatus())) {
            processError(data);
            throw new TikServerException(String.valueOf(data.getCode()), data.getError(), response);
        } else {
            //请求成功
            Url.success();
        }

        return data;
    }
}
```

```java
public class BaseResponse implements NoProguard {
    protected String status;
    protected String error;
    protected int code = Integer.MAX_VALUE;

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public boolean isSuccess() {
        return "ok".equals(status) || code == 0;
    }
}
```

**Comment by Jeremyzwc** [comment]
> 所有类都继承`BaseResponse`，还有这种设计？ 那列表数据如何定义？RxHttp 在2.4.0版本开始，会自动为带泛型的解析器生成asXxxList方法，从而直接得到`List<T>`数据，所以你这种情况就报错了，因为List并没有继承`BaseResponse`；
> 
> 自定义解析器仅适合下面这种数据结构
> 
> ```java
> public class Response<T> {
> 
>     private int    errorCode;
>     private String errorMsg;
>     private T      data;
> 
> }
> ```
> 
> 如果可以，考虑用组合替代继承

老哥，是这样的，我们后台定义的数据结构没有直接返回一个数组，都是Object类型，里面内嵌统一的code和成功或者失败的信息，另外就是数据Object了，所以之前的接收数据的类都统一继承了BaseResponse，我们的数据结构统一都是这样：
`  {
    
      "status": "ok",
      "code": 0,
      "error": "",
      “data”:{}
     //或者
     “goods”:[]
`
现在如果改成兄弟你说的那样，改动会比较大，如果要保留目前这种做法，有没有办法做到呢

**Comment by liujingxing** [comment]
如果你使用kotlin的话，可以自己扩展一个asReponse方法，如下：
```
public inline fun <reified T> BaseRxHttp.asResponse() = asParser(object: ResponseParser<T>() {})
```
此时，需要你就注释`@Parser`注解


如果不使用kotlin，现阶段就没办法了，我的建议还是组合替代继承，其实改动也不是很大，你现在每一个接口，都得写两个实体类，不觉得麻烦吗？

**Comment by Jeremyzwc** [comment]
> 如果你使用kotlin的话，可以自己扩展一个asReponse方法，如下：
> 
> ```kotlin
> public inline fun <reified T> BaseRxHttp.asResponse() = asParser(object: ResponseParser<T>() {})
> ```
> 
> 此时，需要你就注释`@Parser`注解
> 
> 如果不使用kotlin，现阶段就没办法了，我的建议还是组合替代继承，其实改动也不是很大，你现在每一个接口，都得写两个实体类，不觉得麻烦吗？

了解了，兄弟，麻烦了！我这边看一下需要怎么改~谢谢~

**Comment by liujingxing** [comment]
下个版本我加个判断，如果T有限制，就不生成asXxxList方法
