### ISSUE TITLE
缓存和重试问题

### ISSUE THREAD

**Issue by pj567** [liujingxing/rxhttp#363]
缓存模式，不设置缓存key，分页加载数据非第一页数据会把第一页缓存的数据给覆盖掉；没有请求失败重试机制，麻烦修复一下，大佬

**Comment by pj567** [comment]
大佬，我没实际测试，但是我看到这个代码逻辑，好像不对，只要不为空就不会重新赋值，对吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 晚上6:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liujingxing/rxhttp] 缓存和重试问题 (Issue #363)





 
加载第一页，第二页或第n页，只要参数不一样，那么内部生成的cacheKey也不会一样，就不会有你说的缓存覆盖问题，你自己再看看。

**Comment by liujingxing** [comment]
你这，，先动手试吧

**Comment by pj567** [comment]
大佬不好意思，我的问题，突然一下搞蒙了，我是参考你的代码和OKGo的代码，搞一个简单点的框架，我想错了，那个是每次请求都是重新new的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 晚上6:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liujingxing/rxhttp] 缓存和重试问题 (Issue #363)





 
你这，，先动手试吧
