### ISSUE TITLE
能否使用DSL或高阶函数让使用更简单？

### ISSUE THREAD

**Issue by rayzeng0221** [liujingxing/rxhttp#364]
能否使用DSL或高阶函数让使用更简单？比如把方法名都给省略了，直接就一对 {}  然后就是直接在里面处理业务，而不用关注需要调用什么方法做什么事情。类似    request(req){
           {
//请求成功
},{
//请求失败
}
}

**Comment by liujingxing** [comment]
`RxHttp  + RxJava`就是这样的，有些人不喜欢，因为这样降低了可读性，如果你喜欢，可以自己再封装
