### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by wlingf** [liujingxing/rxhttp#367]
希望增加flow 关于串行、并行的案例，某个请求失败如何返回默认值不影响其他请求

**Comment by liujingxing** [comment]
flow属于kotlin协程的知识体系，你可以找找相关资料，个人暂时没有详细介绍flow的计划

**Comment by liujingxing** [comment]
出现异常，返回默认值，Flow也有一系列onErrorXxx方法可实现，但目前被标记为过时，使用catch方法替代
