### ISSUE TITLE
请问下如何清空所有的缓存

### ISSUE THREAD

**Issue by yanpengqing** [liujingxing/rxhttp#369]
RT

**Comment by liujingxing** [comment]
```
//删除所有缓存
RxHttpPlugins.getCache().removeAll()
//根据key删除缓存
RxHttpPlugins.getCache().remove(String)
```

**Comment by yanpengqing** [comment]
http/1.1 400 Bad Request
    Server: nginx
    Date: Tue, 24 May 2022 02:27:48 GMT
    Content-Type: application/xml
    Content-Length: 254
    Connection: keep-alive
    Accept-Ranges: bytes
    Vary: Origin
    
    <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>InvalidRequest</Code><Message>Invalid Request</Message><Resource>/sndefbkt/74dad4d74226adb4477280bf42465966</Resource><RequestId></RequestId><HostId>1db8d88f-9163-4d2d-a678-6b7633a0bcfe</HostId></Error>
复制下载地址浏览器可以正常访问和下载

**Comment by liujingxing** [comment]
请提供下载链接

**Comment by yanpengqing** [comment]
地址有时效性 好像是60s就过期了 这边不方便发送 
我发你邮件了

**Comment by liujingxing** [comment]
没收到，加我微信ljx-studio

**Comment by yanpengqing** [comment]
已解决  
请求头加多了参数
