### ISSUE TITLE
okhttp请求超时无效

### ISSUE THREAD

**Issue by HoneyWorld** [liujingxing/RxHttp#37]
遇到一个偶发问题，使用okhttp在一些偶发情况下，会出现一直在加载中，设置的超时时间没有起作用，是什么问题呢

**Comment by liujingxing** [comment]
你是怎么设置的超时？读、写、连接超时各设置的多少？加载中时间大概多长？

**Comment by HoneyWorld** [comment]
@liujingxing 读、写、连接超时都是30s，但一直没有结果返回，超时也没有起作用，是okhttp的问题吗？

**Comment by liujingxing** [comment]
读、写、连接超时都是30s的话，最差的情况是90s才会触发超时异常。解决办法有两个：
1、读、写、连接超时时间设置短一点，如都设置10s，此时最差的情况也就30s内会触发超时异常
2、通过timeout方法，为单个请求设置超时时间，这个时间应小于读、写、连接超时时间之和。通过次方法设置的超时时间，就会在规定的时间内触发超时异常。

**Comment by HoneyWorld** [comment]
@liujingxing 好的，我试一下，多谢

**Comment by liujingxing** [comment]
嗯，遇到问题可以进群378530627，方便沟通

**Comment by tawny1** [comment]
读、写、连接超时时间设置分别为30，30，10，
我为单个请求设置超时时间为50，
但是超时时间还是30s，请问这是为什么呢？

**Comment by liujingxing** [comment]
你要了解下读、写、连接超时及总超时的区别，看这里。https://github.com/liujingxing/okhttp-RxHttp/wiki/%E8%B6%85%E6%97%B6%E8%AE%BE%E7%BD%AE

**Comment by tawny1** [comment]
读、写、连接超时时间之和为30s+30s+10s=70s，
timeout总超时时间为50s，
为什么是无效的呢？

**Comment by liujingxing** [comment]
举个例子，你要下载一个100M的文件，1s内就连接上了，接口开始下载，而下载会在while循环里不停的调用read方法，每次read，都会开启倒计时(时间为你设置的读超时)，而如果第一次读就超时了，那从开始到超时就是31s，那么你设置总超时50s就不会触发。

**Comment by tawny1** [comment]
好的 谢谢
