### ISSUE TITLE
请教一个泛型转换的问题

### ISSUE THREAD

**Issue by AndyYw** [liujingxing/rxhttp#372]
框架里面是通过response转换数据类的 val data: ApiResponse<T> = response.convertTo(ApiResponse::class.java, *types)。如果这里现在得到的是一个jsonObject，如果与 *types一起最后转换成val data: ApiResponse<T>？

**Comment by AndyYw** [comment]
我们后台数据太恶心了，有时候是{code:"0",msg:"",data:{}},有时候是{code:"",msg:"",属性1：“”，属性2：“”，属性3：“”}。我只能把属性遍历出来自己组装到data去。。
![image](https://user-images.githubusercontent.com/21366609/168720607-ee0557eb-92a0-416d-b502-32dab6a61ff8.png)

**Comment by liujingxing** [comment]
建议你写两个解析器，针对不同数据接口选择对应的解析器即可

**Comment by AndyYw** [comment]
{code:"",msg:"",属性1：“”，属性2：“”，属性3：“”}，{code:"",msg:"",属性1：“”，属性2：“”，属性3：“”，属性4：“”}这种格式不是固定的，可能又很多个属性，数据结构没法确定啊。

**Comment by liujingxing** [comment]
```java
public class BaseResponse {
     int code;
     String msg;
}

class A extends BaseResponse {
   //属性1
   //属性2
}

class B extends BaseResponse {
   //属性3
   //属性4

}
```

**Comment by AndyYw** [comment]
val type: Type = types[0]
val data: ApiResponse<T> = JSON.parseObject(assemblyJsonObject.toString(), object : TypeReference<ApiResponse<T>>(type) {})   我用fastjson转了下好了
