### ISSUE TITLE
是否可以统一处理超时问题？

### ISSUE THREAD

**Issue by yufan2014** [liujingxing/rxhttp#374]
读写和连接超时只能每个接口单独处理吗？

**Comment by NicodeLee** [comment]
有的，参考：https://github.com/liujingxing/rxhttp/blob/master/app/src/main/java/com/example/httpsender/RxHttpManager.java

**Comment by liujingxing** [comment]
[全局/局部超时配置](https://github.com/liujingxing/rxhttp/wiki/%E8%B6%85%E6%97%B6%E8%AE%BE%E7%BD%AE)
