### ISSUE TITLE
想请教一下我们这个框架里线程切换的问题

### ISSUE THREAD

**Issue by jalen2024** [liujingxing/rxhttp#377]
你好，目前用的是我们RxHttp这个框架， 由于是短平快的项目，还没有时间仔细阅读源码。

但是在引用阶段，发现Logcat日志里有提示  主线程有过多的任务， 所以我在想是不是我使用框架的时候把网络请求都放在主线程里了。

请教：我们这个框架里NetCallbackExt里的rxHttpRequest方法中，所有的网络请求都是走的主线程还是子线程呢。

**Comment by liujingxing** [comment]
1、任何框架，网络请求都只能在子现场执行
2、RxHttp内部没有`NetCallbackExt`、`rxHttpRequest`，估计你看错了

**Comment by jalen2024** [comment]
好的，谢谢。   我用的应该是别人基于你的rxHttp封装的一个helper框架。
