### ISSUE TITLE
线程分片下载文件的疑问

### ISSUE THREAD

**Issue by android-1995** [liujingxing/rxhttp#379]
```
RxHttp.get("")             
    .setRangeHeader(0,-1)  //设置下载范围
    .asDownload("")        
    .subscribe()     
//如果此时文件已经有1000的长度，下载完后文件会多出1000的长度
```
好像源码里面的写入都是用的FileOutputStream(this, append)，改为RandomAccessFile是不是更合适分片下载？

**Comment by liujingxing** [comment]
1、调用`setRangeHeader(0,-1)`该方法后，如果此时文件已经有1000的长度，下载完后文件会多出1000的长度问题，属于自己的代码逻辑问题，如果文件已有长度的情况下，应该调用`setRangeHeader(文件的实际长度,-1)`；

2、我没搞明白，就这个场景下，用RandomAccessFile为啥更合适？它的优势体现在哪？

**Comment by android-1995** [comment]
RandomAccessFile能减少出错吧，哈哈，就算.setRangeHeader的值跟真实的文件长度不对，也能保证下载完成后的文件是对的

**Comment by android-1995** [comment]
分片下载的时候还要记录每个片段的下载进度，处理不好的话，很容易出现记录的字节跟文件真实的字节对不上。

**Comment by android-1995** [comment]
还有一个问题，多线程分片下载，FileOutputStream(this, append)，能保证字节的写入顺序吗？
我没试过，猜测会出问题？demo中好像也没有这种例子？

**Comment by liujingxing** [comment]
1、逻辑是这样的，如果有`Content-Range`响应头，就会被认定为追加下载，跟`setRangeHeader`可以说没有直接关系

2、下载是单线程的，不用处理写入顺序

**Comment by android-1995** [comment]
可以理解为：内置的下载只支持单线程下载，不支持单文件的多线程分片下载？

**Comment by liujingxing** [comment]
> 可以理解为：内置的下载只支持单线程下载，不支持单文件的多线程分片下载？

是的，多线程下载不见得比单线程快，有兴趣可以自己去测试

**Comment by android-1995** [comment]
嗯嗯，好的。
没办法，我们的APP有这个需求。
