### ISSUE TITLE
能否自定义json解析工厂，如fastjson，还有找不到对应函数

### ISSUE THREAD

**Issue by Alexxiaopang** [liujingxing/RxHttp#38]
有没有类似retrofit的这个函数，.addConverterFactory(FastJsonConverterFactory.create())

还有就是  import rxhttp.wrapper.ssl.这个包下都没有，只找到这个rxhttp.wrapper.param.RxHttp包

**Comment by liujingxing** [comment]
感谢指出，下个版本会提供自定义json解析工厂相关方法；另外，RxHttp类是在代编编译阶段自动生成的，在build/source文件夹下能找到

**Comment by liujingxing** [comment]
感谢指出，下个版本会提供自定义json解析工厂相关方法；另外，RxHttp类是在代码编译阶段自动生成的，在build/source文件夹下能找到

**Comment by liujingxing** [comment]
刚发布了1.3.1版本，已解决此问题。并提供了RxHttp.setConverter(IConverter)方法，可设置自定义的Converter，详情请查看[README.md](https://github.com/liujingxing/RxHttp/blob/master/README.md)
