### ISSUE TITLE
postJson 参数值是json ，如何正则\"?

### ISSUE THREAD

**Issue by CangJieStore** [liujingxing/rxhttp#382]
类似这种"[{\"ossId\":\"1534449520409051137\"},{\"ossId\":\"1534449520283222018\"},{\"ossId\":\"1534449521155637250\"}]"
服务器不需要\"

**Comment by CangJieStore** [comment]
"[{\"ossId\":\"1534449520409051137\"},{\"ossId\":\"1534449520283222018\"},{\"ossId\":\"1534449521155637250\"}]"

**Comment by liujingxing** [comment]
你的问题肯定不是`"`导致的，postman先去调通，截图出来。另外，如果仅传json数组，用`postJsonArray`方法
