### ISSUE TITLE
postForm可以传入数组么

### ISSUE THREAD

**Issue by zpike** [liujingxing/rxhttp#383]
addQuery如果参数是数组怎么传，比如
```java
RxHttp.postForm(Api.ISREAD)
    .addQuery("ids", idsList)
```
idsList是一个id数组

**Comment by liujingxing** [comment]
那我得先问你，数组的话，你的url是怎样拼接的？

**Comment by zpike** [comment]
apixxxx?ids=1&ids=2

**Comment by liujingxing** [comment]
`addAllQuery(String,List)`

**Comment by zpike** [comment]
这样写，ids还是 api?ids=[1, 2 ,3, 4]

`Map<String, List<String>> idsMap = new HashMap<>();
        idsMap.put("ids", idsList);
        RxHttp.postForm(Api.ISREAD)
                .addAllQuery(idsMap)`
