### ISSUE TITLE
接口使用flow的话不能配置timeout

### ISSUE THREAD

**Issue by WhitePhoenixv5870** [liujingxing/rxhttp#385]
我有一个功能需要根据接口的超时时间与否来改变UI,使用flow的话不能设置timeout,只能设置connectTimeout(5000),readTimeout(5000),writeTimeout(5000),当我把手机下行网络全部关掉的话,手动触发网络请求10s后就超时了,然后我再次手动触发请求,得到超时结果却要40s,缓存,重试什么的都关过,不行,

**Comment by liujingxing** [comment]
> 我有一个功能需要根据接口的超时时间与否来改变UI,使用flow的话不能设置timeout,只能设置connectTimeout(5000),readTimeout(5000),writeTimeout(5000),当我把手机下行网络全部关掉的话,手动触发网络请求10s后就超时了,然后我再次手动触发请求,得到超时结果却要40s,缓存,重试什么的都关过,不行,

没有网络，触发请求，会立即抛出`UnknownHostException`异常并走失败回调

**Comment by liujingxing** [comment]
> 我用rxjava的话,可以设置timeout,得到的结果也是我想要的,就是想问大佬什么时候flow也配置下timeout呢

rxjava的`timeout`操作符是`rxjava`自带的，`flow`并没有超时相关的操作符，不过在`Await`下是有`timeout`的，`Await`可以转flow，如下：
```kotlin
RxHttp.get("/service/...")
    .toResponse<String>()         
    .timeout(5000)                
    .asFlow()                     
    .collect {                     
                                  
    }                             
```
