### ISSUE TITLE
GsonUtil.buildGson().toJson出现int变成double的问题

### ISSUE THREAD

**Issue by Khaos116** [liujingxing/rxhttp#386]
https://wenku.baidu.com/view/7bdaa4dbfa0f76c66137ee06eff9aef8941e4866.html
![image](https://user-images.githubusercontent.com/11989916/175257826-9f62a553-d400-4c11-bb12-979e10877d17.png)

**Comment by liujingxing** [comment]
`{"id":20,"name":"test"}`反序列化为`Map<String,Object>`，此时20就是`double`类型，此时序列化map对象，自然就得到了`{"id":20.0,"name":"test"}`，这是正常的，你应该在反序列化时规避这个问题，譬如反序列化为以下对象

```java
public class Bean {
     int id;
     String name;
}
```
此时，再将Bean对象序列化，就得到和原来一样的json字符串

**Comment by Khaos116** [comment]
为了通用接手一般都写的string，所以才出现这个问题，不是很大的问题，就是觉得这样会不会更好一点

**Comment by liujingxing** [comment]
这个就看个人，你可以自定义`Gson`对象，传入到`GsonConverter`对象中，详情[设置Converter](https://github.com/liujingxing/rxhttp/wiki/%E8%AE%BE%E7%BD%AEConverter)
