### ISSUE TITLE
postjson，base64传输文件出错

### ISSUE THREAD

**Issue by linhua55** [liujingxing/RxHttp#39]
因为base64编码生成的字符串中含有 “=” 等字符，Gson默认会对 “=” 字符进行处理，导致出错。
需要在 Gson builder时，加入 disableHtmlEscaping

builder.disableHtmlEscaping().create();

refer to :
https://stackoverflow.com/questions/32266321/base64-image-encoded-in-java-not-displaying-in-html

**Comment by liujingxing** [comment]
感谢指出，下个版本会提供自定义json解析工厂相关方法

**Comment by liujingxing** [comment]
刚发布了1.3.1版本，已解决此问题。并提供了RxHttp.setConverter(IConverter)方法，可设置自定义的Converter，详情请查看[README.md](https://github.com/liujingxing/RxHttp/blob/master/README.md)
