### ISSUE TITLE
HTTP FAILED: javax.net.ssl.SSLException: Unable to parse TLS packet header

### ISSUE THREAD

**Issue by folinwu2296** [liujingxing/rxhttp#390]

**Comment by liujingxing** [comment]
检查网络

**Comment by folinwu2296** [comment]
我换成http就可以正常，HTTPS 就提示这个错
![image](https://user-images.githubusercontent.com/16589199/179432672-f9fe7cf6-265c-4ab5-94fc-33fc7ef60aae.png)
大佬有遇到过吗？

**Comment by folinwu2296** [comment]
我们后台不支持HTTPS
