### ISSUE TITLE
多个lib引入问题

### ISSUE THREAD

**Issue by wanghongjia** [liujingxing/rxhttp#391]
多个lib引入会有冲突  该如何解决。比如 用户lib 和支付lib 是独立的  app 引入这两个lib 这三个module都引入了rxhttp ，会有冲突 必须改包名吗 ？

**Comment by liujingxing** [comment]
https://github.com/liujingxing/rxhttp/issues/253

**Comment by wanghongjia** [comment]
您好，现在我碰到的问题是  每个lib相对独立  接口返回的数据模型不一样  所以ResponseParser 没个lib不一样。这种情况很难下沉到一个baseLib。该如何处理呢？

**Comment by liujingxing** [comment]
baseLib可以定义多个解析器

**Comment by wanghongjia** [comment]
> 

好的 谢谢
