### ISSUE TITLE
307 Temporary Redirect

### ISSUE THREAD

**Issue by chaozi0118** [liujingxing/rxhttp#392]
大佬，现在要从http改为https。APP这边不动，后台会将http指向https，但是改完之后，get请求没有问题，post会报这个问题是什么原因呢？

**Comment by liujingxing** [comment]
307是临时重定向，在okhttp低版本中，仅`get`、`head`请求支持重定向，在高版本中，不支持从http重定向到https

**Comment by chaozi0118** [comment]
谢谢，已解决。
