### ISSUE TITLE
2.9没有toFlowResponse操作符了吗

### ISSUE THREAD

**Issue by lhj1079947827** [liujingxing/rxhttp#393]
在2.9中没有看到toFlowResponse操作符只有一个toFlowOkResponse不能定义泛型

**Comment by liujingxing** [comment]
这是自定义的方法，详情查看[自定义解析器](https://github.com/liujingxing/rxhttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD)

**Comment by lhj1079947827** [comment]
谢了啊，我还以为是本身自己有的呢
