### ISSUE TITLE
默认url不相同怎么处理

### ISSUE THREAD

**Issue by OvenCroc** [liujingxing/RxHttp#40]
大佬我想问一下如果我有两个请求, 并且这个两个请求的baseurl不是同一个应该怎么操作呢.

**Comment by liujingxing** [comment]
使用`@DefaultDomain `设置默认注解  ，使用`@Domain`设置非默认域名，详情请查看https://juejin.im/post/5ded221a518825125d14a1d4  文章3.6章节

**Comment by liujingxing** [comment]
使用`@DefaultDomain`注解 设置默认域名 ，使用`@Domain`注解设置非默认域名，详情请查看https://juejin.im/post/5ded221a518825125d14a1d4 文章3.6章节
