### ISSUE TITLE
2.9.0 版本 组件化开发 common 里面依赖rxhttp相关配置文件    其他model 里面使用默认注解BaseUrl 不可以使用怎么回事    

### ISSUE THREAD

**Issue by wangcheng24** [liujingxing/rxhttp#400]

**Comment by wangcheng24** [comment]
common 里面依赖    rxhttp 相关文件  这个时候需要在其他libmodel 里面使用 默认注解  这个类也在libModel里面  但是就找不到这个base 报错也是报没有https或者http    然后如果把这个含有默认注解的baseurl 放入common 里面 这个时候就正常

**Comment by liujingxing** [comment]
注解处理器`rxhttp-compiler`不会垮module工作，如果有需要，可以多个module依赖`rxhttp-compiler`，但不建议，一般base module依赖就好
