### ISSUE TITLE
是否可以支持 kotlin data 转 from-data请求参数

### ISSUE THREAD

**Issue by GoldDreams** [liujingxing/rxhttp#402]
服务器接收 body为from-data 的请求参数，请问该库支持 kotlin data 数据类型转 pageNo=1&pageSize=10 这种请求参数格式吗？目前支持转json,暂未满足实际需求

**Comment by liujingxing** [comment]
没明白你的需求
```java
RxHttp.postForm("")
    .setMultiForm()   //multipart/form-data 
    .addQuery("pageNo",  1)    //添加查询参数，拼接到url后面
    .addQuery("pageSize",  20)
    ...
```

**Comment by GoldDreams** [comment]
目前是这种形式请求的，但是我们需求可能调用addQuery二三十次，想问可否支持setBody(data)
传一个数据类进去解析为这种类型


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liujingxing/rxhttp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月6日(星期二) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liujingxing/rxhttp] 是否可以支持 kotlin data 转 from-data请求参数 (Issue #402)





 
没明白你的需求
 RxHttp.postForm("")     .setMultiForm()   //multipart/form-data      .addQuery("pageNo",  1)    //添加查询参数，拼接到url后面     .addQuery("pageSize",  20)     ...

**Comment by liujingxing** [comment]
`addAllQuery(Map)`

**Comment by GoldDreams** [comment]
可能我表述不够清楚，现在是能满足项目需求的，这种形式需要自己组装Map（组装代码达到二三十行左右）,实际项目中涉及到数据参数很多，且需要频繁修改，故使用的 data 数据类存储请求参数，看到支持setBoby(data)直接转化为json参数，就想问是否可以支持这种类型，或使用该库还有其他比较好的形式构建这种参数类型的数据请求，但是依然谢谢大佬抽时间回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月6日(星期二) 下午4:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liujingxing/rxhttp] 是否可以支持 kotlin data 转 from-data请求参数 (Issue #402)





 
addAllQuery(Map)

**Comment by liujingxing** [comment]
抱歉，不支持

`setBoby(data)`支持将data转化为Json，是因为`Gson`支持将Bean类转化为Json；

查询参数一个个拼接在url后面的，你写个Bean类，每个字段都set，个人感觉并没有map来得快。
