### ISSUE TITLE
2.9.2修复了#396，但是却引入了新的bug

### ISSUE THREAD

**Issue by SelectSex** [liujingxing/rxhttp#403]
![image](https://user-images.githubusercontent.com/90268640/188910972-3f2cac40-9903-4428-8aed-e35f5ced88bf.png)

![image](https://user-images.githubusercontent.com/90268640/188910322-398b58b9-8fc1-49e9-b7eb-40b8baad8b52.png)
我的自定义解析器，构造函数需要加入一个参数，表示是否开始多次解析json的功能，升级2.9.2之后，编译一下，
RxHttpExtension.kt 的 
public inline fun <reified T> BaseRxHttp.asResponse(type: Type) = asParser(ResponseParser<T>(javaTypeOf<T>(), type))

就开始报错了。
望大佬修复

**Comment by liujingxing** [comment]
这不是bug，规则就是这样，`Type`类型参数一定要放在第一位，所以，参数位置互换下就好`constructor(type: Type, isDataFix: Boolean = false)`

**Comment by liujingxing** [comment]
建议使用[v2.9.3版本](https://github.com/liujingxing/rxhttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v293)

**Comment by SelectSex** [comment]
谢谢大佬，试了下好了，是我的错，我之前试了很多次都不行，大佬一点拨，才发现是顺序的问题，我都没想到
