### ISSUE TITLE
希望支持下载限流

### ISSUE THREAD

**Issue by zhuifeng2215** [liujingxing/rxhttp#405]
部分业务场景做下载时，防止带宽被完全占用，需要做限流，当前框架不支持，希望可以改进

**Comment by liujingxing** [comment]
这个不应该由框架去实现，给你两个方案

- 自定义拦截器，包装`ResponseBody`，监听下载过程

- [自定义Parser](https://github.com/liujingxing/rxhttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD)，拿到`ResponseBody`对象，自己实现下载过程
