### ISSUE TITLE
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.

### ISSUE THREAD

**Issue by dingxiansen1** [liujingxing/rxhttp#408]
C:/Users/����/.gradle/caches/modules-2/files-2.1/com.github.liujingxing.rxhttp/rxhttp/2.9.3/8451a7f1d7e65c8f25824c3ea0741f68de5555a6/rxhttp-2.9.3.jar!/META-INF/rxhttp.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
您好，大佬，请问是还没适配到最新版吗，最近在用这个库写compose demo，发现这个build报错

**Comment by dingxiansen1** [comment]
![AO27Z6 TKYI4}OS`D8SU~(N](https://user-images.githubusercontent.com/50258853/190858684-76e8a364-22df-4ddf-9128-e83265e94667.png)

**Comment by liujingxing** [comment]
升级kotlin版本

**Comment by dingxiansen1** [comment]
感谢
