### ISSUE TITLE
RxHttp v3.0.0 版本讨论区

### ISSUE THREAD

**Issue by liujingxing** [liujingxing/rxhttp#409]
RxHttp 3.0版本一个重要的理念就是规范api的命名及使用，主要的改变有3点

1、`asXxx/toXxx/toFlowXxx`方法，均支持返回响应头及实体类，如下：

```Java
RxHttp.get("/server/...")
    .asClass<OkResponse<User>>()
    //.toClass<OkResponse<User>>()
    //.toFlow<OkResponse<User>>()
```

2、`RxJava`环境，新增`onProgress/onMainProgress`方法，该方法可监听上传/下载进度，如下：

```Java
//老方式监听下载进度
RxHttp.get("/server/...")
    .asDownload("本地下载路径", AndroidSchedulers.mainThread()) {
        //下载进度回调
    }
    ...

//老方式监听上传进度
RxHttp.postForm("/server/...")
    .addFile("file", File("本地文件路径"))
    .upload(AndroidSchedulers.mainThread()) {
        //上传进度回调
    }
    .asClass<T>()
    ...

//新方式监听下载进度
RxHttp.get("/server/...")
    .asDownload("本地下载路径")
    .onMainProgress {
        //下载进度回调
    }
    ...

//新方式监听上传进度
RxHttp.postForm("/server/...")
    .addFile("file", File("本地文件路径"))
    .asClass<T>()
    .onMainProgress {
        //上传进度回调
    }
    ...

```

3、计划将`asXxx/toXxx/toFlowXxx`方法改为`toObservableXxx/toAwaitXxx/toFlowXxx`

为啥要这么做？为了统一`RxJava/Await/Flow`三者的使用习惯，使得方法见名思义，如：

```kotlin
val observable: Observable<User>  = toObservable<User>()
val await: Await<User> = toAwait<User>()
val flow: Flow<User> = toFlow<User>()
```

[详细的toObservable/toAwait/toFlow方法点击这里](https://github.com/liujingxing/rxhttp/wiki/RxJava%E3%80%81Await%E3%80%81Flow-%E5%AF%B9%E5%BA%94%E7%9A%84-asXxx%E3%80%81toXxx%E3%80%81toFlowXxx%E6%96%B9%E6%B3%95%E4%BB%8B%E7%BB%8D)

但是，这样会有一个小小的问题，下载的时候，第一眼看去就不知是下载方法，如：

```Java
RxHttp.get("/server/...")
    .toObservable("本地绝对路径")
    ...

RxHttp.get("/server/...")
    .toAwait("本地绝对路径")
    ...

RxHttp.get("/server/...")
    .toFlow("本地绝对路径")
    ...

```

没有之前的`asDownload/toDownload`方法看起来舒服；有想过下载时额外处理，用`toDownloadObservable/toDownloadAwait/toDownloadFlow`方法替代，但方法名太长，还是有点难受，所以还在考虑中

对于RxHttp 3.0版本，大家有好的想法，欢迎留言，计划在国庆后正式发版。

**Comment by liujingxing** [comment]
`RxJava/Await/Flow`下载方法命名方案投票：

1. `toObservable/toAwait/toFlow`

2. `toDownObservable/toDownAwait/toDownFlow`

3. `toDownloadObservable/toDownloadAwait/toDownloadFlow`

选择对应的序号留言即可，你也可以有第4个方案，欢迎留言

**Comment by zwonb** [comment]
宁可长而清晰，也不短也而晦涩

**Comment by JasonYinH** [comment]
3

**Comment by jiqianwen** [comment]
3

**Comment by YJWWZHANG** [comment]
3

**Comment by xuxinjiang** [comment]
宁可长而清晰，也不短也而晦涩

**Comment by HuangEnDi** [comment]
目前来看是3，但是有没有把下载单独做成一个设置然后使用1  类似于:
Rxhttp.get()
          .isDownload()
          .toAwaitXXX()

**Comment by xuxinjiang** [comment]
asDownload/toDownload/toFlow 支持这种

**Comment by liujingxing** [comment]
> asDownload/toDownload/toFlow 支持这种

这种就api没有统一，toFlow看起来怪怪的

**Comment by xuxinjiang** [comment]
> 2\. toDownObservable/toDownAwait/toDownFlow

toDownObservable/toDownAwait/toDownFlow第2种可以

**Comment by liujingxing** [comment]
> 目前来看是3，但是有没有把下载单独做成一个设置然后使用1 类似于: Rxhttp.get() .isDownload() .toAwaitXXX()

我想想看

**Comment by haoshiwei** [comment]
一寸长一寸强

**Comment by haoshiwei** [comment]
一寸长一寸强，我选第三个，太短容易混淆

**Comment by zenghuiwang** [comment]
3

**Comment by LDLGH** [comment]
3

**Comment by manbuxingkong** [comment]
见名知意，我选第三个

**Comment by ctop007** [comment]
显而易见，3看起来更舒服

**Comment by willBars** [comment]
遇事不决，选c(3)

**Comment by nopspace** [comment]
3

**Comment by shenxinke** [comment]
三短一长选最长，我选3

**Comment by loperSeven** [comment]
> 目前来看是3，但是有没有把下载单独做成一个设置然后使用1 类似于: Rxhttp.get() .isDownload() .toAwaitXXX()

这种看来是最好的，用 isdownload 标识当前为下载模式

**Comment by YJWWZHANG** [comment]
> > 目前来看是3，但是有没有把下载单独做成一个设置然后使用1 类似于: Rxhttp.get() .isDownload() .toAwaitXXX()
> 
> 这种看来是最好的，用 isdownload 标识当前为下载模式

赞同

**Comment by liujingxing** [comment]
> > > 目前来看是3，但是有没有把下载单独做成一个设置然后使用1 类似于: Rxhttp.get() .isDownload() .toAwaitXXX()
> > 
> > 
> > 这种看来是最好的，用 isdownload 标识当前为下载模式
> 
> 赞同

初步看了下，这种会打破请求三部曲的规则

**Comment by HuangEnDi** [comment]
这个三部曲是指最初设计时定义的规则吗，我理解这个isDownload和add应该是算在同一步

**Comment by HuangEnDi** [comment]
> 

这个三部曲是指最初设计时定义的规则吗，在我理解这个isDownload和add应该是算在同一步里的

**Comment by HuangEnDi** [comment]
> > > > 目前来看是3，但是有没有把下载单独做成一个设置然后使用1 类似于: Rxhttp.get() .isDownload() .toAwaitXXX()
> > > 
> > > 
> > > 这种看来是最好的，用 isdownload 标识当前为下载模式
> > 
> > 
> > 赞同
> 
> 初步看了下，这种会打破请求三部曲的规则

这个三部曲是指最初设计时定义的规则吗，在我理解这个isDownload和add应该是算在同一步里的

**Comment by loperSeven** [comment]
> > > > 目前来看是3，但是有没有把下载单独做成一个设置然后使用1 类似于: Rxhttp.get() .isDownload() .toAwaitXXX()
> > > 
> > > 
> > > 这种看来是最好的，用 isdownload 标识当前为下载模式
> > 
> > 
> > 赞同
> 
> 初步看了下，这种会打破请求三部曲的规则

或者这样？
```kotlin
RxHttp.getDownload("/server/...")//postDownload
    .toObservable("本地绝对路径")
    ...
```

**Comment by liujingxing** [comment]
> 这个三部曲是指最初设计时定义的规则吗，在我理解这个isDownload和add应该是算在同一步里的

目前第一步都是返回RxHttp对象自身，`isDownload`返回自身的话就不适合，得返回一个新的对象，就多了一步。

**Comment by NeVaDaAAA** [comment]
3 清晰明了

**Comment by Jasperben** [comment]
有WebSocket支持么

**Comment by Jasperben** [comment]
期待加入WebSocket支持

**Comment by liujingxing** [comment]
> 期待加入WebSocket支持

okhttp自身就支持，okhttp怎么用，在rxhttp就怎么用，这块没有额外封装

**Comment by liujingxing** [comment]
[RxHttp 3.0版本](https://github.com/liujingxing/rxhttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)已正式更新

[RxHttp 3.0 更新指南，升级必看](https://github.com/liujingxing/rxhttp/wiki/RxHttp-3.0-%E6%9B%B4%E6%96%B0%E6%8C%87%E5%8D%97%EF%BC%8C%E5%8D%87%E7%BA%A7%E5%BF%85%E7%9C%8B)

**Comment by xiaoyvyv** [comment]
2.xx 的 toHeaders 没有兼容的 toAwaitHeaders

**Comment by liujingxing** [comment]
```kotlin
//3.0获取Headers/OkHttp3.Response
RxHttp.get("/server/...")
    .toObservable<OkResponse<User>>()  //Await/Flow 调用 toAwait/toFlow 
    .subscribe({                
        val headers = it.headers()    //Headers
        val response = it.raw()       //OkHttp3.Response
        val user = it.body()
    }, {                
        //异常回调                   
    })
```

**Comment by qyzhaojinxi** [comment]
我用的3.0.3，好像又改了，上边的不管用了

**Comment by liujingxing** [comment]
> 我用的3.0.3，好像又改了，上边的不管用了

没改，注意看3.0更新指南

**Comment by qyzhaojinxi** [comment]
![WX20230531-105215@2x](https://github.com/liujingxing/rxhttp/assets/4145405/716a4c00-bbd4-4e27-8e2f-4bbf61a21f0b)

这里不知道咋写，如果直接写.toObservable(OkResponse,class)会报gson解析报错，按照文档这种代码里就有红线报错

**Comment by liujingxing** [comment]
这是kotlin的写法，再仔细看看文档  https://github.com/liujingxing/rxhttp/wiki/RxJava%E3%80%81Await%E3%80%81Flow-%E5%AF%B9%E5%BA%94%E7%9A%84-asXxx%E3%80%81toXxx%E3%80%81toFlowXxx%E6%96%B9%E6%B3%95%E4%BB%8B%E7%BB%8D

**Comment by qyzhaojinxi** [comment]
哈哈，谢谢，找到了，java部分表格被遮住了，原来可以滑出来，之前没找到

**Comment by liujingxing** [comment]
#448

**Comment by itpers** [comment]
val partData: ByteArray = xxxx
RxHttp.putBody("xxxx")
            .setBody(partData.toRequestBody())
            .toFlow<String>()
            .onProgress {
            }
文件分块上传，只有在partData上传完成才会收到 onProgress 的回调

**Comment by liujingxing** [comment]
> ```kotlin
> val partData: ByteArray = xxxx
> RxHttp.putBody("xxxx")
>     .setBody(partData.toRequestBody())
>     .toFlow<String>()
>     .onProgress {
>     }
> ```
> 
> 文件分块上传，只有在partData上传完成才会收到 onProgress 的回调

RxHttp版本多少

**Comment by itpers** [comment]
> > ```kotlin
> > val partData: ByteArray = xxxx
> > RxHttp.putBody("xxxx")
> >     .setBody(partData.toRequestBody())
> >     .toFlow<String>()
> >     .onProgress {
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 文件分块上传，只有在partData上传完成才会收到 onProgress 的回调
> 
> RxHttp版本多少

3.2.0

**Comment by liujingxing** [comment]
[        return callback != null ? new ProgressRequestBody(requestBody, callback) : requestBody;](https://github.com/liujingxing/rxhttp/blob/750a161c1b3ced1979102014e081992bb746acb5/rxhttp/src/main/java/rxhttp/wrapper/param/AbstractBodyParam.java#L29C3-L29C3)

到这里去调试看看，理论上callback不为null，随后到ProgressRequestBody#sink(Sink)方法里的write方法去调试

**Comment by 1226362423** [comment]
一直没有停留在2.0没有升级 to方法 改的太暴力 应该设置一下过时过度一下 我这几百个类 调用了 to方法

**Comment by liujingxing** [comment]
> 一直没有停留在2.0没有升级 to方法 改的太暴力 应该设置一下过时过度一下 我这几百个类 调用了 to方法

看懂规则，全局搜索，一键替换即可[RxJava、Await、Flow 对应的 toObservaleXxx、toAwaitXxx、toFlowXxx方法介绍](https://github.com/liujingxing/rxhttp/wiki/RxJava%E3%80%81Await%E3%80%81Flow-%E5%AF%B9%E5%BA%94%E7%9A%84-asXxx%E3%80%81toXxx%E3%80%81toFlowXxx%E6%96%B9%E6%B3%95%E4%BB%8B%E7%BB%8D

**Comment by 1226362423** [comment]
<img width="817" alt="image" src="https://github.com/liujingxing/rxhttp/assets/15227754/7bbf80b8-1c21-42ec-b722-fb0494f030c8">
集成3.2.7版本 kotlin 版本1.9.24 ksp 报错 
老的2.8.0版本 kotlin 版本1.9.24 请求头参数传个字符串又乱码了 不知道怎么回事
<img width="1037" alt="image" src="https://github.com/liujingxing/rxhttp/assets/15227754/b2ffa73d-5bd8-46bc-893f-03467beaa393">

**Comment by liujingxing** [comment]
> <img width="817" alt="image" src="https://github.com/liujingxing/rxhttp/assets/15227754/7bbf80b8-1c21-42ec-b722-fb0494f030c8">
> 集成3.2.7版本 kotlin 版本1.9.24 ksp 报错 
> 老的2.8.0版本 kotlin 版本1.9.24 请求头参数传个字符串又乱码了 不知道怎么回事
> <img width="1037" alt="image" src="https://github.com/liujingxing/rxhttp/assets/15227754/b2ffa73d-5bd8-46bc-893f-03467beaa393">
> 
> 我现在kotlin版本用到了今年5月最新版本 1.9.24就出现一些问题了
>  

提供下gradle版本、gradle插件版本、ksp版本

**Comment by 1226362423** [comment]
com.google.devtools.ksp 集成到 1.9.24-1.0.20 ksp这块没问题了 但是3.2.7的这个 toDownloadAwait 怎么用啊 

` scope.launch {
                RxHttp.get(downloadUrl)
                    .setOkClient(MyApplication.okHttpClient)//需要单独设置okHttpClient
                    .setAssemblyEnabled(false)
                    .addAllHeader(Param.addUSM3AppHeader())
                    .toDownloadAwait(savePath){
                        val process = it.progress        //已下载进度 0-100
                        val currentSize = it.currentSize //已下载size，单位：byte
                        val totalSize = it.totalSize     //要下载的总size 单位：byte
                        progressDialog.setProgress(process,currentSize,totalSize)
                        if(process==100){
                            progressDialog.dismiss()
                            gotoInstallPage(savePath)
                            scope.cancel()
                        }
                    }
                    .await()
            }`
onProgress 方法也没有啊

**Comment by 1226362423** [comment]
已成功升级到3.2.7 请求头没有乱码的问题了

**Comment by liujingxing** [comment]
> com.google.devtools.ksp 集成到 1.9.24-1.0.20 ksp这块没问题了 但是3.2.7的这个 toDownloadAwait 怎么用呀
> 
> onProgress 方法也没有 <img alt="image" width="667" src="https://private-user-images.githubusercontent.com/15227754/344363759-abb9bb30-5b0c-4869-898c-4109baad0c3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjY5MDAsIm5iZiI6MTcxOTY2NjYwMCwicGF0aCI6Ii8xNTIyNzc1NC8zNDQzNjM3NTktYWJiOWJiMzAtNWIwYy00ODY5LTg5OGMtNDEwOWJhYWQwYzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDEzMTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMmZhM2I3NWJlY2MxOWRhMzk5ZDYxNGU2MTJiNjgwM2Q3ZjUwNGU0MWE4Y2RmMTE3MTJlNjBlOGRjZjQ1MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q7bMVz_MwNn_GLV6WaCMqb-BG6E-d13QcWAnyxne2Mg"> 原来这种方法要怎么改 <img alt="image" width="684" src="https://private-user-images.githubusercontent.com/15227754/344364406-378078f8-37db-42af-9a21-229218f89432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjY5MDAsIm5iZiI6MTcxOTY2NjYwMCwicGF0aCI6Ii8xNTIyNzc1NC8zNDQzNjQ0MDYtMzc4MDc4ZjgtMzdkYi00MmFmLTlhMjEtMjI5MjE4Zjg5NDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDEzMTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYzJhMTRmNDQ0ZWZiNDRjN2ZiZjdiYjVmYWI3MjE3MGI5ZmM2ZWJhZDA3OTFhZTNlNmM4YmY3YTQxMDkzOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S_-EBjsTdpoA9xBNULdlNT8_cP6bfY0Mf9leb2ZdlCg">
> 
> 另外的那个问题2.8.0版本下确实请求头乱码了暂时不知道什么问题 kotlin版本1.9.24，gradle插件版本7.4.2 gradle版本7.5 出现的 所以我现在升级到3.2.7试下看还会不会出现请求头乱码的问题
> 
> <img alt="image" width="819" src="https://private-user-images.githubusercontent.com/15227754/344364777-ce23c93e-a5c3-4304-a85c-bf61aab03435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjY5MDAsIm5iZiI6MTcxOTY2NjYwMCwicGF0aCI6Ii8xNTIyNzc1NC8zNDQzNjQ3NzctY2UyM2M5M2UtYTVjMy00MzA0LWE4NWMtYmY2MWFhYjAzNDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDEzMTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZWI1ZDAyYzBhNjk1NGQ2Mzk2ODQxM2Y3OTMxM2Y5YTc4MmM3Mjc3ZmY2NzRkOTZiMzQ3Nzc1ZWMzY2Q4NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9sViNaBrGg3n2WpYqlGpF0AjbZ-2X9yt1Fx_V0G-UBk"> Authorization 和 上面的token传的是一样的字符串
> 另外在 2.8.0下 还有个问题 你那个request请求头contentType字段的那个charset:utf-8前面自动带了一个空格 有一些服务端是不能带有空格的 这里我在2.8.0版本加入了拦截器 处理了一下 这种request

1、在3.0版本前，Awiat方式实现上传/下载进度监听，内部是通过Flow实现的， 所以在3.0版本时，就移除了Await方式的上传/下载进度监听，建议直接通过Flow方式去实现，如下：
```kotlin
//下载进度监听
RxHttp.get("")
    .toDownloadFlow(String)
    .onProgress { }
    ...

//上传进度监听
RxHttp.postForm("")
    .addFile("file", File(""))
    .toFlow(String)
    .onProgress { }
    ...
```

2、关于contentType，charset:utf-8前自带空格问题，这是标准的协议，这个只能自己手动处理掉
3、Authorization不显示问题，应该是内容打印不出来，可以在添加Authorization的地方，自己打印日志试试看

**Comment by 1226362423** [comment]
升级到3.2.7都已解决
