### ISSUE TITLE
请问怎么使用链式请求？

### ISSUE THREAD

**Issue by BeforeFuture** [liujingxing/RxHttp#41]
如题。
即想要几个请求按顺序完成，例如第一个请求里有一个结果参数会在第二个请求里使用到。
又或者一个页面有好几个接口，需要按顺序请求一遍。

**Comment by liujingxing** [comment]
请求串行/并行，请查看https://juejin.im/post/5d0782dbe51d4550bf1ae861

**Comment by BeforeFuture** [comment]
感谢解答。
