### ISSUE TITLE
上传图片100%进度总是卡住几秒

### ISSUE THREAD

**Issue by KobeKomi** [liujingxing/rxhttp#410]
上传图片时在toFlow已经获取到100%进度了，也没做耗时操作，但是在collect回调总是慢两三秒才回调，跟图片大小没关系，100多Kb和10多M都一样，这是为什么？

**Comment by liujingxing** [comment]
不能，要等服务端返回的数据

**Comment by KobeKomi** [comment]
好的，感谢
