### ISSUE TITLE
RxHttp没有生成

### ISSUE THREAD

**Issue by Sunyuwumengsheng** [liujingxing/rxhttp#411]
我跟着教程但是没有生成Rxhttp类，我没有办法生成对应Rxhttp
![image](https://user-images.githubusercontent.com/45329962/196223437-ada29041-1c35-47ec-bb90-7a1227ba7dad.png)
![image](https://user-images.githubusercontent.com/45329962/196223791-94fa6341-b423-4f7d-ac38-a031dea6bc47.png)
![image](https://user-images.githubusercontent.com/45329962/196223846-6cac76f4-d5b9-4b3d-9443-be9044e8bbe9.png)

**Comment by liujingxing** [comment]
集成了kotlin，就是用kapt或ksp依赖`rxhttp-compiler`,详情查看[rxhttp集成文档](https://github.com/liujingxing/rxhttp/blob/master/README_zh.md#4%E4%B8%8A%E6%89%8B%E5%87%86%E5%A4%87)

**Comment by liujingxing** [comment]
#446
