### ISSUE TITLE
建议取消默认Converter

### ISSUE THREAD

**Issue by jyygithub** [liujingxing/rxhttp#414]
不知道能不能考虑取消默认GsonConverter，让用户自定义？
现在是默认引入了GSON，如果用别的JSON解析库，那不是多引入了一个用不到的GSON库。

**Comment by liujingxing** [comment]
内置Gson，不仅仅是用于GsonConverter，还有其它地方用到，尝试过移除，但放弃了。
如果你没用到，可以手动移除，虽然这没有多大的意义，因为在打release包，会自动移除你没用的代码。
