### ISSUE TITLE
添加了okhttp拦截器Interceptor后下载方法受到影响 不实时回调Progress进度条

### ISSUE THREAD

**Issue by 1226362423** [liujingxing/rxhttp#415]
添加了okhttp拦截器Interceptor后下载方法受到影响 不实时回调Progress进度条

**Comment by liujingxing** [comment]
#325 日志打印过程就是在读取接口返回的数据，读取就等于下载，日志打印完毕，也就下载完成了。

**Comment by 1226362423** [comment]
`override fun intercept(chain: Interceptor.Chain): Response {
        val request: Request = chain.request()
        val response = chain.proceed(request)
        val responseBody = response.body
        val source = responseBody!!.source()
        source.request(Long.MAX_VALUE) // Buffer the entire body.

        val buffer: Buffer = source.buffer
        var charset: Charset = UTF8
        val contentType: MediaType? = responseBody.contentType()
        if (contentType != null) {
            charset = contentType.charset(UTF8)!!
        }
        val bodyString: String = buffer.clone().readString(charset)

        val isText: Boolean = isText(contentType)
        if (!isText) {
            return response
        }
        //判断响应是否过期（无效）
        return if (isResponseExpired(response, bodyString)) {
            responseExpired(chain, bodyString)!!
        } else response`

我是加入了一个业务上需要的token验证的拦截器 貌似是拦截器中消费了Response的body内容 但是这个拦截器又不能注释啊 很重要 那这个请问您有没有一个好的解决方案

**Comment by 1226362423** [comment]
目前的情况是下载完成了 才将Progress进度条一次性返回出来

**Comment by liujingxing** [comment]
拦截器里可以通过请求头或tag去判断是否下载请求，是的话，不做任何处理

**Comment by 1226362423** [comment]
> 拦截器里可以通过请求头或tag去判断是否下载请求，是的话，不做任何处理

我试下 用 response中的 Content-Type 判断一下

**Comment by 1226362423** [comment]
> > 拦截器里可以通过请求头或tag去判断是否下载请求，是的话，不做任何处理
> 
> 我试下 用 response中的 Content-Type 判断一下 okhttp 自带的拦截器 不知道怎么拿tag

好像还是没什么用

**Comment by liujingxing** [comment]
贴上现在的代码

**Comment by 1226362423** [comment]
已通过给下载方法单独设置OkHttpClient 下载文件方法OkHttpClient不设置拦截器 解决了该问题

**Comment by 1226362423** [comment]
已通过给下载方法单独设置OkHttpClient 下载文件方法OkHttpClient不设置拦截器 解决了该问题
