### ISSUE TITLE
xml请求报错

### ISSUE THREAD

**Issue by BaiMingxu** [liujingxing/rxhttp#417]
这是是老的方式，现在想用Rxhttp怎么设置呀？

<img width="907" alt="截屏2022-12-01 18 54 19" src="https://user-images.githubusercontent.com/22886455/205035437-330757d9-9bc3-41c4-bac0-26557d81a749.png">

**Comment by liujingxing** [comment]
仅凭这个，我无法做出判断，得说明下，用的什么Convert，我才是知道你发送的是什么数据。

**Comment by BaiMingxu** [comment]
用xmlConvert，发送一个对象
