### ISSUE TITLE
rxhttp.wrapper.param.RxHttp 找不到

### ISSUE THREAD

**Issue by ggzaigl1** [liujingxing/RxHttp#42]
RxHttp.get();
找不到Rxhttp类 下载demo也一样找不到 如何解决

**Comment by liujingxing** [comment]
RxHttp类是通过注解处理器生成的，依赖配置好了，需要rebuild一下

**Comment by a120476536** [comment]
依赖配置没问题 clean 后经常出现 RxHttp 无法找到的情况 ，这个如何破解。很是苦恼。
