### ISSUE TITLE
如何配置返回值可能是对象，又有可能是null的情况，The onParse function returned a null value.  

### ISSUE THREAD

**Issue by Hackerofshi** [liujingxing/rxhttp#420]
返回值如下，当为null的时候报The onParse function returned a null value.  请问有没有优雅的处理方式

{"ecode":0,"emsg":"success","detail":{"answer":"年，它在中国科学院国家图书馆收藏，可见它是多么宝贵了。"}}

{"ecode":0,"emsg":"success","detail":null}

**Comment by liujingxing** [comment]
为null时，抛出异常即可，可参考Demo的[解析器](https://github.com/liujingxing/rxhttp/blob/master/app/src/main/java/com/example/httpsender/parser/java/ResponseParser.java)
