### ISSUE TITLE
code = 1 是成功的数据，我要怎么配置？大神指导一下

### ISSUE THREAD

**Issue by wwg90** [liujingxing/rxhttp#421]
<img width="1301" alt="iShot_2023-02-23_00 29 43" src="https://user-images.githubusercontent.com/12004550/220696840-3431223c-74c9-4d95-8e4d-7f55da59e4d6.png">

我现在拿到的数据都是null值

**Comment by liujingxing** [comment]
请贴上代码

**Comment by wwg90** [comment]
RxHttp.get(MyApi.weatherCurrent + "/" + city)
                .toObservable(WeatherInfoBean.class)
                .subscribe(bean -> {
                    LogUtils.eTag("aaa", bean.toString());
                }, throwable -> {
                    LogUtils.eTag("aaa", throwable.toString());
                });
---------
    private void initRxHttp() {
        RxHttpPlugins.init(null)
                .setDebug(true)
                .setOnParamAssembly(param -> param.addHeader("app_id", Config.AppId)
                        .addHeader("app_secret", Config.AppSecret));
    }
-----
这是有关rxhttp所有的代码了

**Comment by liujingxing** [comment]
`toObservable(WeatherInfoBean.class)`你这实体类跟接口返回的数据都不匹配，解析失败很正常。

想要统一处理code，请参考[自定义Parser文档](https://juejin.cn/post/6844904016380428302#heading-23)

**Comment by wwg90** [comment]
嗯，我看了这个自定义Parser，没搞好，还是失败，我再看看吧

**Comment by liujingxing** [comment]
可以下载demo看看
