### ISSUE TITLE
无法继承UriFactory

### ISSUE THREAD

**Issue by lichenchenisapuppy** [liujingxing/rxhttp#425]
您好，在使用3.0.2版本的时候，继承UriFactory出现问题，找不到如下几个文件：
Cannot resolve symbol 'OutputStreamFactory'
Cannot resolve symbol 'FileOutputStreamFactory'
等

暂时未搜索到同样的问题的解决方式，所以在此求助一下，感谢。

**Comment by lichenchenisapuppy** [comment]
换成了3.0.1就正常了。

**Comment by liujingxing** [comment]
3.0.2将内置kotlin 升级至1.8.0，同步升级你的kotlin版本

**Comment by lichenchenisapuppy** [comment]
收到  感谢。
