### ISSUE TITLE
Content-Type自定义

### ISSUE THREAD

**Issue by yellowhe** [liujingxing/rxhttp#428]
大佬您好，请问下postForm时Content-Type的值能够支持自定义吗，我看现在只能是setMuXXX改固定的值，自己addHeader时加不了

**Comment by liujingxing** [comment]
表单请求就只有那几种固定的值，你想改啥？
另外，`Content-Type`的值，取决于RequestBody的类型，OkHttp的`BridgeInterceptor`拦截器会自动添加`Content-Type`，如果之前有添加，就会被覆盖

**Comment by yellowhe** [comment]
我们是有自己的固件，和固件通讯时有约定这个值，我也不知道他们之前为什么用这个来约定

**Comment by liujingxing** [comment]
[自定义Param](https://github.com/liujingxing/rxhttp/wiki/%E9%AB%98%E7%BA%A7%E5%8A%9F%E8%83%BD#%E8%87%AA%E5%AE%9A%E4%B9%89Param)，重新getRequestBody()方法

**Comment by yellowhe** [comment]
好的，谢谢
