### ISSUE TITLE
toDownload 下载方法问题

### ISSUE THREAD

**Issue by 1226362423** [liujingxing/rxhttp#432]
版本：
implementation 'com.squareup.okhttp3:okhttp:4.9.1'
implementation 'com.github.liujingxing.rxhttp:rxhttp:2.8.0'
kapt 'com.github.liujingxing.rxhttp:rxhttp-compiler:2.8.0'
出现问题：调用下载方法  下载到sd卡的文件明明已经全部下载完毕了 下载的文件大小也是和返回的response大小是一样的。但是rxhttp
toDownload 回调 Progress 返回的最终结果就是 progress //当前进度 是90几 80几  currentSize//当前已完成字节也是少于总子节的。！但是sd卡的文件确实已经下载完了啊 怎么处理这种问题？现在要怎么知道已经下载完成 progress 到不了100。文件为pdf文件

**Comment by liujingxing** [comment]
我确定不存在此问题哈，可以提供你复现的demo

**Comment by liujingxing** [comment]
可以尝试升级rxhttp至最新，或用rxhttp的demo试试
