### ISSUE TITLE
域名从sp动态读取这样写生效吗

### ISSUE THREAD

**Issue by Jasperben** [liujingxing/rxhttp#434]
![image](https://github.com/liujingxing/rxhttp/assets/15630036/163b62b3-1c8e-48dc-a3d9-7c646854f6ee)
@Domain(name = "TestUser")
public static String testUser = SPUtils.getInstance().getString("testUser");

**Comment by liujingxing** [comment]
可以的，但静态变量只会初始化一次，后续想要更改，只能重新赋值

**Comment by Jasperben** [comment]
重新赋值？

**Comment by liujingxing** [comment]
Xxx.testUser = "新的域名"

**Comment by Jasperben** [comment]
OK
