### ISSUE TITLE
数据解析

### ISSUE THREAD

**Issue by Jasperben** [liujingxing/rxhttp#436]
![image](https://github.com/liujingxing/rxhttp/assets/15630036/6f921e7d-e744-4e9a-a72a-e1f4f95b59ee)
{
      "code": 200,
      "data": null,
      "message": "操作成功"
    }
这里data返回null 我想就成功返回null呢

**Comment by liujingxing** [comment]
协程可以，RxJava不支持返回null，具体如何处理看[服务器返回数据不规范，导致数据解析异常](https://github.com/liujingxing/rxhttp/wiki/FAQ#%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%94%E5%9B%9E%E6%95%B0%E6%8D%AE%E4%B8%8D%E8%A7%84%E8%8C%83%E5%AF%BC%E8%87%B4%E6%95%B0%E6%8D%AE%E8%A7%A3%E6%9E%90%E5%BC%82%E5%B8%B8)

**Comment by Jasperben** [comment]
好的
