### ISSUE TITLE
下载怎么获取response当中的Content-Type fileName等信息

### ISSUE THREAD

**Issue by 1226362423** [liujingxing/rxhttp#437]
```
RxHttp.get(downloadUrl)
                .setOkClient(MyApplication.okHttpClient)//需要单独设置okHttpClient
                .toDownload(savePath){
                    val process = it.progress        //已下载进度 0-100
                    val totalSize = it.totalSize     //要下载的总size 单位：byte
                    
                  
                }
                .tryAwait {
                    result.postValue(it)
                }
```

**Comment by 1226362423** [comment]
现在就是 文件类型 文件名都根据服务器的设定来

**Comment by liujingxing** [comment]
> 现在就是 文件类型 文件名都需要根据服务器的设定来存储
'savePath=".../apk/％s" 用占位符替代文件名立刻

**Comment by 1226362423** [comment]
@liujingxing  还是没太明白您说的 我这边savepath=“/storage/emulated/0/Android/data/packename/files/AppFile/%s” 这样没用 下载下来的文件没有后缀格式 文件名也不对
<img width="995" alt="image" src="https://github.com/liujingxing/rxhttp/assets/15227754/2e67c2f7-c92c-4dda-ac94-6467f1d48d0d">


就是response 当中这些信息怎么设置到文件

**Comment by liujingxing** [comment]
用`%s`替代文件名即可，如果有问题，把下载链接发出来

**Comment by 1226362423** [comment]
额 内网的链接 算了 我自己用原生okhttp写一个下载吧  很简单的需求  就是下载的文件名和文件格式类似浏览器那样 直接读文件流上的信息 然后保存到本地

**Comment by liujingxing** [comment]
不清楚你用的版本多少，最新版本的话，到这里去调试
<img width="798" alt="image" src="https://github.com/liujingxing/rxhttp/assets/7237396/b07f53c1-f80f-418a-b043-d2fff001706d">

**Comment by liujingxing** [comment]
这样吧，贴出完整的`Content-Disposition`响应头，我试试看

**Comment by liujingxing** [comment]
你的文件名是中文导致的，[v3.0.6](https://github.com/liujingxing/rxhttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v306)版本已发布，会对filename做`URLDecoder`处理，可以试试

**Comment by 1226362423** [comment]
用的版本是 2.8.0 升级版本改动太大了
 implementation 'com.squareup.okhttp3:okhttp:4.9.1'
    implementation 'com.github.liujingxing.rxhttp:rxhttp:2.8.0'
    kapt 'com.github.liujingxing.rxhttp:rxhttp-compiler:2.8.0'

**Comment by liujingxing** [comment]
升级真没有想象的那么大改动，大部分都是全局替换下就好，详情查看[RxHttp 3.0 更新指南，升级必看](https://github.com/liujingxing/rxhttp/wiki/RxHttp-3.0-%E6%9B%B4%E6%96%B0%E6%8C%87%E5%8D%97%EF%BC%8C%E5%8D%87%E7%BA%A7%E5%BF%85%E7%9C%8B)
