### ISSUE TITLE
一个项目两种接口，返回值不一样，parse怎么处理

### ISSUE THREAD

**Issue by zendro** [liujingxing/RxHttp#44]
有两种接口，java和php，返回的基础参数都不一样，
比如php接口是
{
    "result_flag":true,
    "result_desc":"成功",
    "result_data":{}
}
host是https://xxx.vipabc.com/

java接口是
{
    "code":1,
    "msg":"成功",
    "data":{}
}
host是https://yyy.vipabc.com/
如果项目里共用一套Rxhttp，请问parse怎么处理？

**Comment by liujingxing** [comment]
实体类字段名不一样，用 @SerializedName注解，如下：
```java
public class Response<T> {
    @SerializedName("result_flag")
    private String code;
    @SerializedName("result_desc")
    private String msg;
    @SerializedName("result_data")
    private T data;
}
```
多域名问题，请查看https://juejin.im/post/5ded221a518825125d14a1d4  3.6章节

**Comment by zendro** [comment]
setOnParamAssembly 参数也不同呢，java需要加header  param.addHeader；php需要加公共参数add，，，，怎么处理？
