### ISSUE TITLE
List<List<Data>>类型toObservableResponseList(这里面解析错误)

### ISSUE THREAD

**Issue by Jasperben** [liujingxing/rxhttp#442]
![image](https://github.com/liujingxing/rxhttp/assets/15630036/82d1049d-0f8c-4b29-8810-e0d5a0f7f083)

**Comment by Jasperben** [comment]
![image](https://github.com/liujingxing/rxhttp/assets/15630036/8ca10ce7-f2c5-48fe-9b28-a5287c0c4d30)

**Comment by Jasperben** [comment]
这里怎么写

**Comment by Jasperben** [comment]
![image](https://github.com/liujingxing/rxhttp/assets/15630036/79c8c52f-6b6d-4804-8cb5-4710db69b1f6)

**Comment by liujingxing** [comment]
```kotlin
//kotlin
RxHttp.get("/server/...")
  .toObservable<List<List<Grade>>>()
  .subscribe {
    val user = it.body()
    val response = it.raw()
    val headers = it.headers()
  }


//java
Type type = ParameterizedTypeImpl
  .get(List.class, List.class, Grade.class);

RxHttp.get("/server/...")
  .<List<List<Grade>>>toObservable(type)
  .subscribe(res -> {
    User user = res.body()
    Response response = res.raw()
    Headers headers = res.headers()
  });
```

**Comment by liujingxing** [comment]
详情[查看toXxx方法](https://github.com/liujingxing/rxhttp/wiki/RxJava%E3%80%81Await%E3%80%81Flow-%E5%AF%B9%E5%BA%94%E7%9A%84-asXxx%E3%80%81toXxx%E3%80%81toFlowXxx%E6%96%B9%E6%B3%95%E4%BB%8B%E7%BB%8D)

**Comment by Jasperben** [comment]
收到

**Comment by liujingxing** [comment]
为啥会有`<List<List<Grade>>>`这种数据类型，`List<Grade>`的话，Java环境下，直接用toObservableList(Grade.class)就好

**Comment by Jasperben** [comment]
![image](https://github.com/liujingxing/rxhttp/assets/15630036/ba05d48f-9f6b-49d8-a403-e0c72aa19fe7)

**Comment by Jasperben** [comment]
{
    "code":200,
    "data":[
        [
            {
                "gradeId":66,
                "gradeName":"职教",
                "stageId":5,
                "token":""
            },
            {
                "gradeId":19,
                "gradeName":"前",
                "stageId":4,
                "token":""
            }
        ],
        [
            {
                "gradeId":1,
                "gradeName":"一年级",
                "stageId":1,
                "token":""
            },
            {
                "gradeId":2,
                "gradeName":"二年级",
                "stageId":1,
                "token":""
            },
            {
                "gradeId":3,
                "gradeName":"三年级",
                "stageId":1,
                "token":""
            },
            {
                "gradeId":4,
                "gradeName":"四年级",
                "stageId":1,
                "token":""
            },
            {
                "gradeId":5,
                "gradeName":"五年级",
                "stageId":1,
                "token":""
            },
            {
                "gradeId":6,
                "gradeName":"六年级",
                "stageId":1,
                "token":""
            }
        ],
        [
            {
                "gradeId":27,
                "gradeName":"六年级-五四制",
                "stageId":2,
                "token":""
            },
            {
                "gradeId":7,
                "gradeName":"初一",
                "stageId":2,
                "token":""
            },
            {
                "gradeId":8,
                "gradeName":"初二",
                "stageId":2,
                "token":""
            },
            {
                "gradeId":9,
                "gradeName":"初三",
                "stageId":2,
                "token":""
            }
        ],
        [
            {
                "gradeId":10,
                "gradeName":"高一",
                "stageId":3,
                "token":""
            },
            {
                "gradeId":11,
                "gradeName":"高二",
                "stageId":3,
                "token":""
            },
            {
                "gradeId":12,
                "gradeName":"高三",
                "stageId":3,
                "token":""
            }
        ]
    ],

    "message":"操作成功"
}

**Comment by Jasperben** [comment]
这种格式

**Comment by liujingxing** [comment]
`toObservable`改解析器生成的方法`toObservableResponse`

**Comment by Jasperben** [comment]
好的
