### ISSUE TITLE
setOnParamAssembly能否知道是postForm还是postJson

### ISSUE THREAD

**Issue by Jasperben** [liujingxing/rxhttp#443]
setOnParamAssembly能否知道是postForm还是postJson

**Comment by liujingxing** [comment]
if (param is FormParam) {
}

JsonParam同理

**Comment by Jasperben** [comment]
setOnParamAssembly 添加公共参数   有提供方法能把原来的参数覆盖掉吗 （因为原来添加了这个参数  在setOnParamAssembly添加公共参数重复了  希望有这个参数能够覆盖掉原来的值）

**Comment by liujingxing** [comment]
对于json，参数显然不能重复，所以会自动覆盖；对于form，是支持重复的，如果想要覆盖，强转FormParam后，会有set系列方法

**Comment by Jasperben** [comment]
get方式有提供set系列方法吗

**Comment by liujingxing** [comment]
暂时没有，下个版本所有方法会加上`setQuery(String, Object)`方法

**Comment by Jasperben** [comment]
好的
