### ISSUE TITLE
setOnParamAssembly 参数也不同呢，java需要加header param.addHeader；php需要加公共参数add，，，，怎么处理？

### ISSUE THREAD

**Issue by zendro** [liujingxing/RxHttp#45]
项目里同时存在两种接口。。。。回调问题已经解决，请求如何区分开来？我看rxhttp公共参数和公共head是application里一次性设置的。最好有为两套不同接口做兼容请求的办法，不是每个接口里去add

**Comment by liujingxing** [comment]
rxhttp公共参数/请求头接口，是会在每次发起请求前，都会回调的，你可以通过Param拿到一些信息做判断，添加不同的参数。
