### ISSUE TITLE
你好，我这儿生成不了rxhttp

### ISSUE THREAD

**Issue by yuanmaio** [liujingxing/rxhttp#452]
找不到rxhttp,用的最新版本的库
我的QQ：564556524，请麻烦帮忙看一下

**Comment by liujingxing** [comment]
#446

**Comment by yuanmaio** [comment]
> #446
试过了，还是不行

**Comment by liujingxing** [comment]
把你的配置全部截图出来

**Comment by yuanmaio** [comment]
> 把你的配置全部截图出来
![image](https://github.com/liujingxing/rxhttp/assets/8166762/f4f3ff8d-ecb6-44e4-bc25-33638147dce8)
![image](https://github.com/liujingxing/rxhttp/assets/8166762/44c6f0d2-1987-4bbf-bd19-eae9d97d292e)

**Comment by liujingxing** [comment]
这不生成了吗，报红的那几个类是kotlin编写的，升级你的kotlin版本；但理论上报红不会影响你使用RxHttp类

**Comment by yuanmaio** [comment]
![image](https://github.com/liujingxing/rxhttp/assets/8166762/ea6b03a4-eb49-4288-a41f-01a789c7a6e6)


> 这不生成了吗，报红的那几个类是kotlin编写的，升级你的kotlin版本；但理论上报红不会影响你使用RxHttp类

**Comment by yuanmaio** [comment]
> ![image](https://user-images.githubusercontent.com/8166762/252560500-ea6b03a4-eb49-4288-a41f-01a789c7a6e6.png)
> 
> > 这不生成了吗，报红的那几个类是kotlin编写的，升级你的kotlin版本；但理论上报红不会影响你使用RxHttp类

引用不了

**Comment by liujingxing** [comment]
那就升级kotlin插件版本

**Comment by yuanmaio** [comment]
我这儿不需要kotlin插件啊

**Comment by yuanmaio** [comment]
> 那就升级kotlin插件版本

我这儿不需要kt插件啊

**Comment by liujingxing** [comment]
Android Studio 的kotlin插件

**Comment by yuanmaio** [comment]
> Android Studio 的kotlin插件

和这个有关系？

**Comment by yuanmaio** [comment]
> Android Studio 的kotlin插件

我现在有了，还是报错的

**Comment by yuanmaio** [comment]
> Android Studio 的kotlin插件

我这儿还是引用不了啊，麻烦给看下原因啊

**Comment by liujingxing** [comment]
截图看下版本多少

**Comment by yuanmaio** [comment]
> 截图看下版本多少

android studio 版本吗？还是啥？

**Comment by liujingxing** [comment]
as版本，as的kotlin插件版本

**Comment by yuanmaio** [comment]
> as版本，as的kotlin插件版本
![image](https://github.com/liujingxing/rxhttp/assets/8166762/ed5a8bb6-cdd2-4866-88e2-59c09dde1a20)
![image](https://github.com/liujingxing/rxhttp/assets/8166762/9227cb73-879e-4ad1-890a-6f028f41311c)

**Comment by liujingxing** [comment]
目前kotlin最新1.8.x，你不能升级，是因为as版本太低，请同步升级

**Comment by yuanmaio** [comment]
> 目前kotlin最新1.8.x，你不能升级，是因为as版本太低，请同步升级

![image](https://github.com/liujingxing/rxhttp/assets/8166762/ff1e2751-b26a-47a3-83f2-13b73153e4cc)
 还是引用不了啊

**Comment by liujingxing** [comment]
不应该，加我微信吧  ljx-studio

**Comment by liujingxing** [comment]
经排查后，由于升级版本，部分api没有同步更改导致报错
