### ISSUE TITLE
3.1.0版本，ksp环境下，没有使用@DefaultDomain注解，生成的RxHttp类报错

### ISSUE THREAD

**Issue by liujingxing** [liujingxing/rxhttp#454]
`addDefaultDomainIfAbsent`缺少方法体
<img width="726" alt="image" src="https://github.com/liujingxing/rxhttp/assets/7237396/7392fc71-21ba-4766-8a75-e1f57ced57ee">

**Comment by xiaozuopeng** [comment]
> `addDefaultDomainIfAbsent`缺少方法体 <img alt="image" width="726" src="https://private-user-images.githubusercontent.com/7237396/254472224-7392fc71-21ba-4766-8a75-e1f57ced57ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3Nzk5MDksIm5iZiI6MTcyMDc3OTYwOSwicGF0aCI6Ii83MjM3Mzk2LzI1NDQ3MjIyNC03MzkyZmM3MS0yMWJhLTQ3NjYtOGE3NS1lMWY1N2NlZDU3ZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMTAyMDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGJiMjVhOTRiM2FkNmEwMzRiYjFmNzU0ZjU5MGFlNTIzMzc3YTQyNDc3Y2ZlMjQwMTVmNzVkYjM4ZTM3NTZmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oCaIm5wBQhr-Bwsp-EDrmjkOSG0zMExCzcWOYIiPUZ0">

![1720779702758](https://github.com/user-attachments/assets/17f0dd97-bece-40cc-86dc-6f9fc384c21a)
![image](https://github.com/user-attachments/assets/da7bc5f6-9ac4-46a6-9037-1f3aab0d34aa)
为什么使用的@DefaultDomain注解，但是没有生产默认域名  版本3.2.7
