### ISSUE TITLE
使用ksp编译异常

### ISSUE THREAD

**Issue by gudao20080** [liujingxing/rxhttp#456]
1. 纯Kotlin项目， 准备用ksp 替代 kapt
2. rxHttpVersion = "3.1.1", 
  plugins {
      id ("com.android.application") version "8.0.2" apply false
      id ("com.android.library") version "8.0.2" apply false
      id ("org.jetbrains.kotlin.android") version "1.8.22" apply false
      id("com.google.devtools.ksp") version "1.8.22-1.0.11" apply false
  }
3. 使用kapt编译通过， ksp报错，如下:
![image](https://github.com/liujingxing/rxhttp/assets/6431152/208c91a0-bb4b-4a95-810a-d8fd0ef57940)
![image](https://github.com/liujingxing/rxhttp/assets/6431152/f47935ee-95cb-4edb-bfc7-58585cd93c73)

**Comment by liujingxing** [comment]
自定义解析器截图看下

**Comment by gudao20080** [comment]
`package com.jinmaoedu.smartclass.teacher.net.response

import rxhttp.wrapper.annotation.Parser
import rxhttp.wrapper.exception.ParseException
import rxhttp.wrapper.parse.TypeParser
import rxhttp.wrapper.utils.convertTo
import java.io.IOException
import java.lang.reflect.Type

/**
 * 输入T,输出T,并对code统一判断
 * User: ljx
 * Date: 2018/10/23
 * Time: 13:49
 *
 * 如果使用协程发送请求，wrappers属性可不设置，设置了也无效
 */
@Parser(name = "Response")
open class ResponseParser<T> : TypeParser<T> {
    /**
     * 此构造方法适用于任意Class对象，但更多用于带泛型的Class对象，如：List<Student>
     *
     * 用法:
     * Java: .asParser(new ResponseParser<List<Student>>(){})
     * Kotlin: .asParser(object : ResponseParser<List<Student>>() {})
     *
     * 注：此构造方法一定要用protected关键字修饰，否则调用此构造方法将拿不到泛型类型
     */
    protected constructor() : super()

    /**
     * 此构造方法仅适用于不带泛型的Class对象，如: Student.class
     *
     * 用法
     * Java: .asParser(new ResponseParser<>(Student.class))   或者  .asResponse(Student.class)
     * Kotlin: .asParser(ResponseParser(Student::class.java)) 或者  .asResponse<Student>()
     */
    constructor(type: Type) : super(type)

    @Throws(IOException::class)
    override fun onParse(response: okhttp3.Response): T? {
        val data: ScResponse<T> = response.convertTo(ScResponse::class, *types)
        var t = data.data //获取data字段
//        if (t == null && types[0] === String::class.java) {
//            /*
//             * 考虑到有些时候服务端会返回：{"errorCode":0,"errorMsg":"关注成功"}  类似没有data的数据
//             * 此时code正确，但是data字段为空，直接返回data的话，会报空指针错误，
//             * 所以，判断泛型为String类型时，重新赋值，并确保赋值不为null
//             */
//            @Suppress("UNCHECKED_CAST")
//            t = data.msg as T
//        }
        if (data.code != 0 || t == null) { //code不等于0，说明数据不正确，抛出异常
            throw ParseException(data.code.toString(), data.msg, response)
        }
        return t

    }
}`

照你的抄的，转了一下kotlin, 修改了下

**Comment by liujingxing** [comment]
onParse方法返回类型T?改为T就好
