### ISSUE TITLE
闪退问题，java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by xuegao-tzx** [liujingxing/rxhttp#457]
具体日志：
```
java.lang.NoSuchFieldError: No field Companion of type Lrxhttp/wrapper/param/RxHttp$Companion; in class Lrxhttp/wrapper/param/RxHttp; or its superclasses (declaration of 'rxhttp.wrapper.param.RxHttp' appears in /data/app/~~WVAd3gIT1M1mJTpDa9hgUQ==

Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cbf6fd7, Dispatchers.IO]
```

```kotlin
RxHttp.postJson("/test")
      .add("country", verify.country)
      .toAwait<XCLApiBean.VerifyInfo>()
      .tryAwait()
```

**Comment by liujingxing** [comment]
怎么接入的？rxhttp-compiler有没有依赖多次？

**Comment by xuegao-tzx** [comment]
> 怎么接入的？rxhttp-compiler有没有依赖多次？

implementation("com.github.liujingxing.rxhttp:rxhttp:3.1.1")
    ksp("com.github.liujingxing.rxhttp:rxhttp-compiler:3.1.1")

**Comment by liujingxing** [comment]
就这，没其他得了？

**Comment by xuegao-tzx** [comment]
> 就这，没其他得了？

还有基础的okhttp3的依赖 com.squareup.okhttp3:okhttp

**Comment by liujingxing** [comment]
一般这个问题是多个module依赖了rxhttp-compiler导致的，检查下

**Comment by xuegao-tzx** [comment]
好的

**Comment by liujingxing** [comment]
问题解决了吗

**Comment by q947721485** [comment]
java.lang.NoSuchFieldError: No field Companion of type Lrxhttp/wrapper/param/RxHttp$Companion; in class Lrxhttp/wrapper/param/RxHttp; or its superclasses (declaration of 'rxhttp.wrapper.param.RxHttp' appears in /data/app/~~WKe7naLd7ecjnJoA3eKrWQ==/com.xishidaojia.fuwu-XHrp4duSyPJkNugOeeDssA==/base.apk!classes10.dex)
环境 使用ksp编译 版本3.2.3 ksp版本 1.9.20-1.0.14 无多module依赖 在compose 目前不知道具体问题在什么地方

**Comment by liujingxing** [comment]
#480
