### ISSUE TITLE
postJson请求体里面带/会被转义成\/

### ISSUE THREAD

**Issue by wu19910708** [liujingxing/rxhttp#458]

**Comment by liujingxing** [comment]
不会的，请提供RxHttp版本号及相关代码

**Comment by wu19910708** [comment]
rxhttp版本号：3.0.6
RxHttp.postJson(NetUrl.SUBMIT_PROBLEM)
            .addAll(GsonUtils.toJson(req))
            .toAwaitResponse()
GsonUtils.toJson(req) 这个方法还没有被转义
发送请求的时候就被转义了
<img width="850" alt="image" src="https://github.com/liujingxing/rxhttp/assets/11901662/a2d9a730-e7a7-47ef-a3f3-22adbd0c0716">

**Comment by liujingxing** [comment]
<img width="742" alt="image" src="https://github.com/liujingxing/rxhttp/assets/7237396/f3c43c4c-b0e0-4145-91fa-ff68eee05807">
不会的哈，有可能是你的日志打印有问题，使用RxHttp的日志打印试试看

**Comment by liujingxing** [comment]
如果是发送一个对象，可以使用`postBody方法`，如下：
```kotlin
val user = User()
RxHttp.postBody("")
    .setBody(user)
    ...
```
