### ISSUE TITLE
提一点小建议:内置的打印日志能不能暴露方法，提供打印的级别？

### ISSUE THREAD

**Issue by Power-Android** [liujingxing/RxHttp#46]
Verbose里信息太多，个人习惯放到erro里查看，希望能暴露设置打印级别的方法。

**Comment by Power-Android** [comment]
可以参考下OkGo的打印日志，很详细，类似于这种：
`E/POWER: --> POST https://.................... http/1.1
E/POWER: 	Content-Type: application/x-www-form-urlencoded
E/POWER: 	Content-Length: 35
E/POWER: 	passid: z7gcawmtu4g1blzgnzftns5435638tdl
E/POWER: 	sign: BD6C85FC311A437E6EFC08D1D516537D
E/POWER: 	timestamp: 1576831956
E/POWER:  
E/POWER: 	body:article_id=932&timestamp=1576831956
E/POWER: --> END POST
E/POWER: <-- 200 OK https://.................../getIndexPic (5430ms）
E/POWER: 	Date: Fri, 20 Dec 2019 08:52:37 GMT
E/POWER: 	Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
E/POWER: 	Access-Control-Allow-Origin: http://172.10.10.253:8099
E/POWER: 	Access-Control-Allow-Method: POST,GET
E/POWER: 	Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
E/POWER: 	Access-Control-Allow-Headers: x-requested-with,content-type
E/POWER: 	Vary: Accept-Encoding
E/POWER: 	Keep-Alive: timeout=5, max=100
E/POWER: 	Connection: Keep-Alive
E/POWER: 	Content-Type: text/html; charset=utf-8
E/POWER: 	Cache-Control: public, max-age=60
E/POWER:  
E/POWER: 	body:{.....}`

**Comment by liujingxing** [comment]
![image](https://user-images.githubusercontent.com/7237396/71251201-9e6b0a80-235c-11ea-820e-90d1c359bddc.png)
这是目前RxHttp日志打印结构，对比okgo，不是很明白你是觉得打印信息少了什么？还是说格式不太习惯。另外，对于Verbose信息过多，我个人的习惯是过滤 `RxHttp`，这样日志就一目了然，当然，对于暴露设置打印级别的方法，后续版本会考虑，感谢提出。
