### ISSUE TITLE
关于kotlinx.coroutines.JobCancellationException: Job was cancelled

### ISSUE THREAD

**Issue by berial** [liujingxing/rxhttp#462]
页面上有多个tab，快速切换时会报
`
kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@bbb1315。
`
请求代码为：
```kotlin
if (job != null && job?.isActive == true) 
    job?.cancel()
    job = runBlocking {
        repo.fetchData().onEach{ xxxxxx }.collect() // 一个网络请求转flow
    }
```
不影响使用，但是会打印一个tag为Rxhttp的error日志，请问该如何解决？

**Comment by liujingxing** [comment]
这是正常的，页面关闭，协程会关闭，请求也会跟着关闭，也就有了这个异常。
目前如果不想看到，只能通过`setDebug(false)`方法关闭日志输出
