### ISSUE TITLE
是否支持动态生成代码不同包名

### ISSUE THREAD

**Issue by 1Ezreal** [liujingxing/rxhttp#465]
多模块下 打包成aar 会与主项目动态生成代码的冲突  会默认使用主项目的代码
期望 不同模块可配置生成包名 避免冲突

**Comment by 1Ezreal** [comment]
不好意思 ，没有仔细看demo ，是支持的，牛逼

**Comment by liujingxing** [comment]
大部分情况下，base module依赖rxhttp-compiler就好

**Comment by 1Ezreal** [comment]
单独作为aar的网络请求库，目前遇到初始化问题，如果主项目初始化了，aar再初始化，会覆盖掉初始化参数，反之亦然
