### ISSUE TITLE
老版本的使用文档有吗？

### ISSUE THREAD

**Issue by Mc-dashan** [liujingxing/rxhttp#468]
老版本的使用文档有吗？

**Comment by liujingxing** [comment]
没，新老版本使用方式没变化，新版本只是统一了方法命名，具体改变看[3.0更新指南](https://github.com/liujingxing/rxhttp/wiki/RxHttp-3.0-%E6%9B%B4%E6%96%B0%E6%8C%87%E5%8D%97%EF%BC%8C%E5%8D%87%E7%BA%A7%E5%BF%85%E7%9C%8B)
