### ISSUE TITLE
下载文件的进度是在下载完成后1S内回调的，老版本不是实时返回的吗？

### ISSUE THREAD

**Issue by JoneMa** [liujingxing/rxhttp#469]
代码如下：
```kotlin
 val factory = Android10DownloadFactory(Utils.getApp(), fileName)
        downloadApkDisposable =  RxHttp.get(newApkDownloadUrl)
            .setDecoderEnabled(false)
            .toDownloadObservable(factory,false)
            .onMainProgress {
                CMLogger.e("@@@@@MSP:",it.toString())
                EventBus.getDefault().post(EventCenter(DOWNLOAD_NEW_V_APK_PROGRESS, it.progress))
            }.doOnSubscribe {
                EventBus.getDefault().post(EventCenter(DOWNLOAD_NEW_V_APK_STATE, DownloadFileService.DOWNLOAD_STATE_START))
            }.subscribe({
                CMLogger.e("@@@@@MSP:",it.toString())
                newApkLocalFilePath = it.toString()
                EventBus.getDefault().post(EventCenter(DOWNLOAD_NEW_V_APK_STATE, DownloadFileService.DOWNLOAD_STATE_SUCCESS))
                releaseDownloadNewVersionApk()
            }, {
                EventBus.getDefault().post(EventCenter(DOWNLOAD_NEW_V_APK_STATE, DownloadFileService.DOWNLOAD_STATE_ERROR))
                releaseDownloadNewVersionApk()
            })
```
麻烦帮忙看下可以调整吗。版本号3.2.0

**Comment by JoneMa** [comment]
val factory = Android10DownloadFactory(Utils.getApp(), fileName)
        downloadApkDisposable =  RxHttp.get(newApkDownloadUrl)
            .setDecoderEnabled(false)
            .toDownloadObservable(factory,false)
            .onMainProgress {
                CMLogger.e("@@@@@MSP:",it.toString())
                EventBus.getDefault().post(EventCenter(DOWNLOAD_NEW_V_APK_PROGRESS, it.progress))
            }.doOnSubscribe {
                EventBus.getDefault().post(EventCenter(DOWNLOAD_NEW_V_APK_STATE, DownloadFileService.DOWNLOAD_STATE_START))
            }.subscribe({
                CMLogger.e("@@@@@MSP:",it.toString())
                newApkLocalFilePath = it.toString()
                EventBus.getDefault().post(EventCenter(DOWNLOAD_NEW_V_APK_STATE, DownloadFileService.DOWNLOAD_STATE_SUCCESS))
                releaseDownloadNewVersionApk()
            }, {
                EventBus.getDefault().post(EventCenter(DOWNLOAD_NEW_V_APK_STATE, DownloadFileService.DOWNLOAD_STATE_ERROR))
                releaseDownloadNewVersionApk()
            })

**Comment by liujingxing** [comment]
盲猜你添加了日志拦截器，是的话，取消就好

**Comment by JoneMa** [comment]
日志拦截器是指CMLogger这个里面的吗？还是RxHttp中的设置？

**Comment by liujingxing** [comment]
就是你自己通过OkHttpClient对象添加的日志拦截器

**Comment by JoneMa** [comment]
![image](https://github.com/liujingxing/rxhttp/assets/17917775/8dedeecc-ed22-4827-ae68-81af88d1f2b4)
这里面没有日志拦截器，日志拦截器会影响到Rxhttp内的回调吗

**Comment by liujingxing** [comment]
<img width="578" alt="image" src="https://github.com/liujingxing/rxhttp/assets/7237396/272cc1e4-294f-4030-bfeb-ba53f96874f1">
这两个拦截器去掉再试试，拦截器里读取body的过程就是在下载，你这个解密拦截器应该就读取了body

**Comment by liujingxing** [comment]
可以在拦截器判断下，如果是下载，就直接跳过

**Comment by JoneMa** [comment]
好的 我先试试 多谢多谢
