### ISSUE TITLE
打印接口请求时长

### ISSUE THREAD

**Issue by inshyma** [liujingxing/RxHttp#47]
问下 有没有方法可以把从接口请求到返回的间隔时间打印出来

**Comment by liujingxing** [comment]
这个1.3.2版本就已经有了，你把日志开启，然后过滤RxHttp。如下
![image](https://user-images.githubusercontent.com/7237396/71342910-20477780-2599-11ea-9be4-66ef3a28229b.png)

**Comment by inshyma** [comment]
我的错  我用的还是1.2.3呢...
