### ISSUE TITLE
未使用混淆之前可以正常网络请求，使用混淆之后无法正常网络请求

### ISSUE THREAD

**Issue by bravetou** [liujingxing/rxhttp#472]
```gradle
    def rxhttp_version = '3.0.6'
    implementation 'com.squareup.okhttp3:okhttp:4.10.0'
    implementation "com.github.liujingxing.rxhttp:rxhttp:$rxhttp_version"`
```

```kotlin
@Param(methodName = "postEncryptForm")
class PostEncryptFormParam(url: String?) : FormParam(url, Method.POST) {
    override fun getRequestBody(): RequestBody? {
        val allParam = mutableMapOf<String, Any>()
        // 获取到所有通过add系列方法添加的参数
        bodyParam.forEach {
            allParam[it.key] = it.value
        }
        // 获取到所有通过addQuery系列方法添加的参数
        queryParam?.forEach {
            allParam[it.key] = it.value
        }
        LogUtils.json("RxHttp", allParam)
        val signs = allParam.encryptParamAES(false)
        // 重新组装请求体
        bodyParam.clear()
        queryParam?.clear()
        bodyParam.add(KeyValuePair("signs", signs))
        return super.getRequestBody()
    }
}
```

**Comment by liujingxing** [comment]
具体什么问题？另外，你自己的实体类记得keep

**Comment by bravetou** [comment]
`
# 保持实体类不被混淆
-keep class org.jutuina.com.tuinapro.bean.**{*;}
-keep class org.jutuina.com.tuinapro.core.net.Response{*;}
# -keep class org.jutuina.com.tuinapro.core.net.GetEncryptParam {*;}
# -keep class org.jutuina.com.tuinapro.core.net.PostEncryptFormParam {*;}
# -keep class org.jutuina.com.tuinapro.core.net.PostEncryptJsonParam {*;}
`

混淆了的，具体就是项目中使用了AES（allParam.encryptParamAES(false)）加密所有参数，生成一个新的signs参数，未混淆时一切正常，混淆之后就直接报网络请求失败

**Comment by liujingxing** [comment]
错误日志你要发出来

**Comment by bravetou** [comment]
`
19:13:51.031  D   
                 ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                 │ main, org.jutuina.com.tuinapro.core.net.GetEncryptParam.getHttpUrl(SourceFile:54)
                 ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
                 │ {
                 │   "type": "0",
                 │   "is_distinct": "1",
                 │   "the_wang": "dXJkZXdhbmc\u003ddXJkZXdhbmc\u003d",
                 │   "version": "1.23"
                 │ }
                 └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
19:13:51.063  D  getDecorViewInvisibleHeight: -1920
19:13:51.067  D  duplicate layer name: changing org.jutuina.com.tuinapro/org.jutuina.com.tuinapro.ui.home.HomeActivity to org.jutuina.com.tuinapro/org.jutuina.com.tuinapro.ui.home.HomeActivity#1
19:13:51.073  D  disable<e i a s b h r c s > disable2<q i n g r >
19:13:51.073  D   isNormalMode= true clock visible=true
19:13:51.108  D  getDecorViewInvisibleHeight: 0
19:13:51.121  D  beforeShow
19:13:51.123  E  onFinishInput
19:13:51.124  E  onStartInput
19:13:51.139  D  getDecorViewInvisibleHeight: 0
19:13:51.151  D  beforeDismiss
19:13:51.159  D  getDecorViewInvisibleHeight: 0
19:13:51.161  I  cancelToast pkg=org.jutuina.com.tuinapro callback=android.app.ITransientNotification$Stub$Proxy@369d8bc
19:13:51.161  W  Toast already cancelled. pkg=org.jutuina.com.tuinapro callback=android.app.ITransientNotification$Stub$Proxy@369d8bc
19:13:51.169  I  Show toast from OpPackageName:org.jutuina.com.tuinapro, PackageName:org.jutuina.com.tuinapro
19:13:51.425  D  onShow
19:13:51.440  I  <--- globalEventCb line 124 QMI_LOC_EVENT_GNSS_SV_INFO_IND_V02
19:13:51.440  I  <--- globalEventCb line 124 QMI_LOC_EVENT_POSITION_REPORT_IND_V02
19:13:51.443  I  WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@aa47bf2)
19:13:51.443  I  WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@aa47bf2)
19:13:51.453  D  onDismiss
19:13:51.460  D  disable<e i a s b h r c s > disable2<q i n g r >
19:13:51.460  D   isNormalMode= true clock visible=true
19:13:51.470  E  onFinishInput
19:13:51.471  E  onStartInput
19:13:51.585  D  currentTimeMillis() cache hit
19:13:51.610  D  currentTimeMillis() cache hit
19:13:51.613  E  [PhoneIntfMgr] checkCarrierPrivilegesForPackage: No UICC
19:13:51.618  E  [PhoneIntfMgr] checkCarrierPrivilegesForPackage: No UICC
`

**Comment by liujingxing** [comment]
我需要错误日志，请求失败具体什么表现，比如，请求发出来没，请求回来了没？RxHttp初始化的的时候通过setDebug(true)，随后就会有详细的请求日志

**Comment by bravetou** [comment]
`
21:10:36.269  E  Request end Log printing failed
21:10:36.269  E  java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
`

**Comment by bravetou** [comment]
已增加Gson混淆，谢谢

**Comment by liujingxing** [comment]
晓得了，你应该升级了AGP 8.0，默认开启了R8 full mode，该模式下，混淆时会讲泛型擦除，RxHttp v3.2.1也对该模式进行了兼容 #471
