### ISSUE TITLE
The variable 'DEV_URL' must be String

### ISSUE THREAD

**Issue by fail572872916** [liujingxing/rxhttp#475]
如图错误
![微信截图_20231220004354](https://github.com/liujingxing/rxhttp/assets/19763500/c92dea42-57aa-463e-88b4-8bfaa2166414)
配置如下

![微信截图_20231220004319](https://github.com/liujingxing/rxhttp/assets/19763500/9783da75-9e0b-44b3-9770-d41888dcf51a)
![微信截图_20231220004333](https://github.com/liujingxing/rxhttp/assets/19763500/15929f87-c4ef-445a-81be-4a8cd256c30e)
![微信截图_20231220004429](https://github.com/liujingxing/rxhttp/assets/19763500/71eaee11-34fc-4595-9d72-313c3725890e)

如何解决问题

**Comment by liujingxing** [comment]
抱歉，没注意看邮件，麻烦提供下rxhttp及ksp版本号

**Comment by liujingxing** [comment]
显示为变量声明为String类型，应该就可以，下版本会兼容此问题

**Comment by fail572872916** [comment]
> 抱歉，没注意看邮件，麻烦提供下rxhttp及ksp版本号
 ksp "com.github.liujingxing.rxhttp:rxhttp-compiler:3.0.5"
 api 'com.github.liujingxing.rxhttp:rxhttp:3.0.3'

**Comment by fail572872916** [comment]
const val DEV_URL:String  = BuildConfig.APP_BaseUrl
 这样就可以了

**Comment by liujingxing** [comment]
是的，显示声明类型就好
