### ISSUE TITLE
toDownloadFlow点击Cannot find declaration to go to 

### ISSUE THREAD

**Issue by csh159** [liujingxing/rxhttp#478]
不能跳转，也不能识别，但是运行，打包也不报错，这是为啥 ？

**Comment by liujingxing** [comment]
rxhttp版本号多少，错误日志要提供，详细描述问题

**Comment by liujingxing** [comment]
升级至3.0.2版本？还是3.0.2版本升级至最新版？自定义Parser及对应的实体类贴出来

**Comment by csh159** [comment]
3.2.4的版本 
![1705984060570](https://github.com/liujingxing/rxhttp/assets/4157414/29e81372-4c17-4160-9cbd-2556d152dce2)
![1705984033683](https://github.com/liujingxing/rxhttp/assets/4157414/5c4eb4d5-8189-4c9e-b38f-a5557e357cc5)

**Comment by csh159** [comment]
升級到3.2.4版本 生成不了toObservableCodeResponseList方法。
![1705984200584](https://github.com/liujingxing/rxhttp/assets/4157414/ca5713cb-fc1f-499f-84f0-49443a3b3d96)
![1705984207434](https://github.com/liujingxing/rxhttp/assets/4157414/ebad5d96-19ad-4f0e-9a8a-6a7162bda40e)

**Comment by liujingxing** [comment]
继承TypeParser<T>，
