### ISSUE TITLE
rxhttp最低支持的gradle和kotlin版本是多少

### ISSUE THREAD

**Issue by liuyaxi** [liujingxing/rxhttp#479]
gradle 4.2.2
kotlin  1.6.21
开发工具是鳗鱼版本
再编译期间就会报错
![微信图片_20240120121158](https://github.com/liujingxing/rxhttp/assets/17871784/98d4ce1d-7598-4758-992c-facfb5662323)

**Comment by liuyaxi** [comment]
![Uploading QQ截图20240120121612.png…]()

**Comment by liuyaxi** [comment]
![QQ截图20240120121612](https://github.com/liujingxing/rxhttp/assets/17871784/03cf5aaf-b591-41ec-855b-02db76a24b54)

**Comment by liuyaxi** [comment]
![QQ截图20240120121658](https://github.com/liujingxing/rxhttp/assets/17871784/aacb9c41-7f26-43eb-9469-0650ecff09e8)
这个意思是不是要我升级版本啊  如果不升级的话 是不是就没法用了呢

**Comment by liuyaxi** [comment]
![QQ截图20240120121612](https://github.com/liujingxing/rxhttp/assets/17871784/9e563264-18a2-46cb-803b-945c9087ccd3)

**Comment by liuyaxi** [comment]
![QQ截图20240120122008](https://github.com/liujingxing/rxhttp/assets/17871784/00c3d710-ae8c-476c-b91e-f3f367f00a8b)

**Comment by liujingxing** [comment]
RxHttp对gradle及as版本没有要求，但kotlin对gradle及as版本有要求，你可以升级kotlin插件版本至1.7.x版本。

**Comment by liuyaxi** [comment]
> RxHttp对gradle及as版本没有要求，但kotlin对gradle及as版本有要求，你可以升级kotlin插件版本至1.7.x版本。

好的，大佬 我下午的时候试试看

**Comment by liujingxing** [comment]
还是建议你升级as,早晚的事。
