### ISSUE TITLE
java.lang.NoSuchFieldError: No field Companion of type

### ISSUE THREAD

**Issue by q947721485** [liujingxing/rxhttp#480]
```xml
java.lang.NoSuchFieldError: No field Companion of type Lrxhttp/wrapper/param/RxHttp$Companion; 
in class Lrxhttp/wrapper/param/RxHttp; 
or its superclasses (declaration of 'rxhttp.wrapper.param.RxHttp' appears in /data/app/~~WKe7naLd7ecjnJoA3eKrWQ==/com.xishidaojia.fuwu-XHrp4duSyPJkNugOeeDssA==/base.apk!classes10.dex)
```
环境 使用ksp编译 版本3.2.3 ksp版本 1.9.20-1.0.14 无多module依赖 在compose 目前不知道具体问题在什么地方

**Comment by liujingxing** [comment]
什么情况下出现此问题？打包后？把module结构，及RxHttp依赖配置截图发出

**Comment by liujingxing** [comment]
在Java还是kotlin环境中调用？依赖的kotlin版本又是多少

**Comment by q947721485** [comment]
在kotlin 环境下调用的，kotlin版本为1.9.20 。在调试环境下，运行后调用rxhttp请求网络时出现的
![WechatIMG1](https://github.com/liujingxing/rxhttp/assets/19965109/1038cb81-1cbd-4603-b944-ff38b9c071b1)
![WechatIMG2](https://github.com/liujingxing/rxhttp/assets/19965109/0e612f58-9fc3-496b-bb00-a1793f555f3b)
![WechatIMG3](https://github.com/liujingxing/rxhttp/assets/19965109/e8ffbef3-4966-43ac-9d57-945bb1bbba71)
![WechatIMG4](https://github.com/liujingxing/rxhttp/assets/19965109/02d3d9ba-6e12-416b-8d27-5c61de055aa6)
![WechatIMG5](https://github.com/liujingxing/rxhttp/assets/19965109/5f34a0a1-b37b-4753-99a1-5b9813b2c765)
![WechatIMG6](https://github.com/liujingxing/rxhttp/assets/19965109/055b8cfb-294d-44de-b683-7079f1fdf485)
![WechatIMG7](https://github.com/liujingxing/rxhttp/assets/19965109/e1d56b89-9159-49bc-ac7f-e9c955a35614)

**Comment by liujingxing** [comment]
把kotlin版本改为`1.9.10`，ksp改为`1.9.10-1.0.13`再试试，还是不行话，加我微信 ljx-studio

**Comment by q947721485** [comment]
好的我先试一下再过来回复

**Comment by q947721485** [comment]
你好，还是不行加你微信了

**Comment by liujingxing** [comment]
问题已找到，原因是，`rxhttp-compiler`的`kapt注解处理器`跟`hilt`有点冲突，即使使用`ksp`依赖`rxhttp-compiler`，hilt依然会调用`rxhttp-compiler`的`kapt注解处理器，导致生成Java版本的RxHttp类，而`ksp`依赖`rxhttp-compiler`，又会生成一份kotlin版本`RxHttp`类，如下图所示：
<img width="453" alt="image" src="https://github.com/liujingxing/rxhttp/assets/7237396/fef235ba-3eeb-42de-bb61-af48283d322f">

导致在代码合并时，把kotlin版本的RxHttp类丢失了，而Java版本的RxHttp类，是没有`RxHttp$Companion`变量的，所以就报错了，下个版本会规避这个问题

**Comment by liujingxing** [comment]
在已使用ksp依赖`rxhttp-compiler`的情况下，复现步骤如下
1、在项目的build.gradle文件中添加一下代码
```gradle
buildscript {

    dependencies {
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.48.1'
    }
}

plugins {
    id("com.google.devtools.ksp") version "1.9.10-1.0.13" apply false
}

```


2、在module的build.gradle文件中添加以下代码
```gradle
plugins {
    id 'dagger.hilt.android.plugin'
}

dependencies {
    implementation "com.google.dagger:hilt-android:2.48.1"
    ksp "com.google.dagger:hilt-android-compiler:2.48.1"  //kapt或ksp一样有问题
}
```

3、使用`hilt`任一注解，如：
```java
@HiltAndroidApp
public class AppHolder extends Application {
    //省略部分代码
}
```

项目同步成功后，rebuild一下项目，此时就会出现两个RxHttp类

**Comment by liujingxing** [comment]
***注：使用kapt依赖`rxhttp-compiler`没有此问题***

**Comment by liujingxing** [comment]
[v3.2.4版本已解决该问题](https://github.com/liujingxing/rxhttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v324)
