### ISSUE TITLE
Cannot resolve symbol 'RxHttp'

### ISSUE THREAD

**Issue by YanYangTan** [liujingxing/rxhttp#482]
我的是纯java 项目
![image](https://github.com/liujingxing/rxhttp/assets/50619076/b631eea5-e3b5-41be-9ea7-c2c51df4de6e)
![image](https://github.com/liujingxing/rxhttp/assets/50619076/5f8309b8-ee8d-4f5a-a13b-cd169d699e24)
试了很久还是找不到RxHttp类
我不知道哪里少了什么，能帮我看看吗

**Comment by YanYangTan** [comment]
![image](https://github.com/liujingxing/rxhttp/assets/50619076/a8ffa6e8-0d60-4ede-96a9-3d7e3a999a02)

**Comment by liujingxing** [comment]
注解用了吗，没的话，用上一个

**Comment by YanYangTan** [comment]
可以问一下注解应该写在那里吗？我写在类、函数和使用前都不行：
Annotations are not allowed here

**Comment by YanYangTan** [comment]
或者哪里能找到示例我去看一下

**Comment by YanYangTan** [comment]
我用了以下确实可以了，但是我使用的时候一直报错
![image](https://github.com/liujingxing/rxhttp/assets/50619076/397658ab-2375-4bb2-9307-3b1747ec5fa5)
![image](https://github.com/liujingxing/rxhttp/assets/50619076/bd5ed7a3-0eba-4471-9eb7-f3594d56b670)

**Comment by YanYangTan** [comment]
好的 感谢，能问一下为什么这个库一定要使用注解吗？

**Comment by liujingxing** [comment]
使用annotationProcessor或kapt依赖任何注解处理器，如果检索到对应的注解，便不会工作；ksp则没这个限制
