### ISSUE TITLE
下载文件可能会超时，怎么解决？

### ISSUE THREAD

**Issue by csh159** [liujingxing/rxhttp#483]
下载文件域名是上了cdn，但是cdn动态解析可能会返回无效的ip地址，会导致下载文件下载不了的情况。

**Comment by liujingxing** [comment]
如果是这样，你直接使用okhttp下载一样有问题

**Comment by liujingxing** [comment]
尝试用RxHttp的demo去下载，如果没问题的话，就是你自己的代码问题，检测下你的代码是否有添加相关拦截器，有的话，注释调在试试。
