### ISSUE TITLE
编译报错了

### ISSUE THREAD

**Issue by YanYangTan** [liujingxing/rxhttp#486]
我的是纯java项目，Debug Build时没有问题，使用release Build 就报错了，
能帮我看一下是什么问题吗，感谢
![image](https://github.com/liujingxing/rxhttp/assets/50619076/d71dd450-30a4-4409-9997-83859045927b)

**Comment by YanYangTan** [comment]
C:/Users/YANG/.gradle/caches/modules-2/files-2.1/com.github.liujingxing.rxhttp/rxhttp/3.2.4/ade0e515eedfdcea3fc6d3572a066e4faba33530/rxhttp-3.2.4.jar!/META-INF/rxhttp.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Comment by liujingxing** [comment]
升级kotlinb版本

**Comment by YanYangTan** [comment]
不好意思我是菜鸟，我的是java项目，意思是要导入kotlin环境？

**Comment by liujingxing** [comment]
哦，那不需要，怎么接入的RxHttp，截图看下
