### ISSUE TITLE
RxHttp 生成在 AndroidTest 目录

### ISSUE THREAD

**Issue by dyguests** [liujingxing/rxhttp#488]
我在我的 `myLib` module 中添加 RxHttp依赖。

最终 RxHttp 生成路径在 androidTest目录下，

`myLib/build/generated/ksp/debugAndroidTest/kotlin/rxhttp/wrapper/param/RxHttp.kt`

业务代码无法依赖。

依赖相关代码：

myLib/build.gradle

```
plugins {
    ...
    alias(libs.plugins.ksp)
}

...

dependencies {
    ...
    api libs.okhttp
    api libs.github.rxhttp
    ksp libs.rxhttp.compiler
    ...
}
```

`libs.versions.toml` 文件略

**Comment by liujingxing** [comment]
我试了下，没有此问题，你使用的ksp及RxHttp版本多少？

**Comment by dyguests** [comment]
rxhttpVersion = "3.2.4"
ksp = '1.9.10-1.0.13'

我找到原因了：
似乎是因为我 module 中 `src/main/java` 下没有代码导致的。

我`src/androidTest`中有代码（创建module自动生成的）,所以RxHttp生成到debugAndroidTest中
我在src/main/java随便添加了点代码，就可以正确生成了。

**Comment by liujingxing** [comment]
大概率是ksp的问题，但好像这样的逻辑也没问题，后续有时间我研究下
