### ISSUE TITLE
demo运行不起来

### ISSUE THREAD

**Issue by RyanJeson** [liujingxing/RxHttp#49]
刚刚下载的demo，想运行一下。结果发现RxHttp的包没有找到， 看了一下是有依赖的。
后面又在我自己的项目中引用rxhttp，结果也一样，没有找到rxhttp的包。rxlife倒是没问题

**Comment by liujingxing** [comment]
Rebuild一下，RxHttp类是在编译期自动生成的

**Comment by RyanJeson** [comment]
> Rebuild一下，RxHttp类是在编译期自动生成的

ok
