### ISSUE TITLE
java.lang.NullPointerException: <get-cache>(...) must not be null 这种一般是什么问题呀,不是必现，偶尔出现就会闪退。

### ISSUE THREAD

**Issue by zzzsssbo** [liujingxing/rxhttp#493]
全局缓存目录和缓存模式都配置了
  
java.lang.NullPointerException: <get-cache>(...) must not be null
        at rxhttp.wrapper.intercept.CacheInterceptor.getCache(CacheInterceptor.kt:24)
        at rxhttp.wrapper.intercept.CacheInterceptor.getCacheResponse(CacheInterceptor.kt:72)
        at rxhttp.wrapper.intercept.CacheInterceptor.intercept(CacheInterceptor.kt:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)

**Comment by liujingxing** [comment]
代码贴出来

**Comment by zzzsssbo** [comment]
配置缓存的代码吗

**Comment by liujingxing** [comment]
全局配置及发请求的代码

**Comment by zzzsssbo** [comment]
`   RxHttp.postBody(url)
                .setBody(body)
                .setCacheKey((url))
                .setCacheMode(CacheMode.REQUEST_NETWORK_FAILED_READ_CACHE)
                .setCacheValidTime(-1)
                .asString()
                .as(RxLife.asOnMain(context))
                .subscribe(new MyErrorConsumer(new MyErrorConsumer.OnErrorListener() {
                    @Override
                    public void onError(ErrorBean error) {
                     
                    }
                }) {
                    @Override
                    public void onNext(@NotNull String s) {
                        super.onNext(s);
                     
                    }
                });`

**Comment by zzzsssbo** [comment]
版本是  2.6.6
