### ISSUE TITLE
自定义parser生成失败

### ISSUE THREAD

**Issue by chenww713** [liujingxing/rxhttp#494]
toObservableHttpResponse()方法生成成功了，但是toObservableHttpResponseList()和toObservableHttpResponsePageList()没有生成
![111](https://github.com/liujingxing/rxhttp/assets/170289110/1c6eaa18-5e7d-43c1-860f-bd7a3eae75d7)

**Comment by chenww713** [comment]
![222](https://github.com/liujingxing/rxhttp/assets/170289110/98975624-d2fb-4e43-b55c-adecea290688)

**Comment by liujingxing** [comment]
rxhttp版本号多少

**Comment by chenww713** [comment]
implementation 'com.squareup.okhttp3:okhttp:4.12.0'
implementation "com.github.liujingxing.rxhttp:rxhttp:3.2.6"
annotationProcessor "com.github.liujingxing.rxhttp:rxhttp-compiler:3.2.6"
implementation 'io.reactivex.rxjava3:rxjava:3.1.6'
implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
implementation 'com.github.liujingxing.rxlife:rxlife-rxjava3:2.2.2'

**Comment by liujingxing** [comment]
你是升级rxhttp版本，还是项目首次接入rxhttp?

**Comment by chenww713** [comment]
首次接入rxhttp

**Comment by liujingxing** [comment]
知道了，你的解析起泛型传入了`<HttpResponse<T>>`,这样是不是生成toObserableXxxList系列方法的，改`TypeParser<T>`就会生成

**Comment by chenww713** [comment]
好的问题解决了，谢谢大佬
