### ISSUE TITLE
请问哪种请求方式 参数形式是以text/html 形式提交的

### ISSUE THREAD

**Issue by seaCool96** [liujingxing/rxhttp#497]

**Comment by liujingxing** [comment]
rxhttp.postBody().setBody()

**Comment by seaCool96** [comment]
![QQ截图20240628162955](https://github.com/liujingxing/rxhttp/assets/18422922/e10ef91a-b431-40f8-8cb3-fe8cbf267239)
您好，我这使用的是postbody   这个content-type 不还是 application/json吗
，我在ApiPost 上是可以正常请求的，麻烦解惑，谢谢

**Comment by liujingxing** [comment]
有一系列setBody方法，可以指定content-type
