### ISSUE TITLE
依赖里找不到Rxhttp这个类

### ISSUE THREAD

**Issue by jielundewode** [liujingxing/RxHttp#5]
文件可能上传不完整

**Comment by jielundewode** [comment]
看到你的回复了，但是1.0.2这个版本还是找不到

**Comment by jielundewode** [comment]
了解了，看了您的博客，原来这个类是自己生成的

**Comment by liujingxing** [comment]
是的，1.0.2版本版在baseUrl上使用@DefaultDomain标签，然后rebuild 一下项目。就能看到RxHttp类了
