### ISSUE TITLE
能否在自动重试的基础上增加手动重试机制？

### ISSUE THREAD

**Issue by pangli** [liujingxing/rxhttp#501]
需求描述：在网络请求失败后显示网络异常的弹窗，点击弹窗中的重试按钮，重新发起上次一的请求，如何保存和获取上次的请求参数等数据来进行手动发起重试？

**Comment by liujingxing** [comment]
这属于业务需求，需要自己去实现，一般来说，重试时，只需要再次执行相关方法即可；当然，RxHttp也提供了retry方法，详情点击[RxHttp ，比Retrofit 更优雅的协程体验](https://juejin.cn/post/6844904100090347528#heading-10)
