### ISSUE TITLE
升级3.2.3  出现问题The binary version of its metadata is 1.9.0, expected version is 1.7.1.

### ISSUE THREAD

**Issue by zxc6966927** [liujingxing/rxhttp#504]
![image](https://github.com/user-attachments/assets/cd761326-c942-4fb8-b86e-5f4eff833556)

升级出现bug
请问怎么解决？弄了两天了
![1724393596239](https://github.com/user-attachments/assets/9b47b109-900e-46d1-b5e3-45894a3d4ea2)

**Comment by liujingxing** [comment]
升级android studio 的kotlin插件版本

**Comment by zxc6966927** [comment]
最新的android studio 也没找到能改插件版本的地方
![image](https://github.com/user-attachments/assets/d0882a50-46c2-4661-8e14-fdbf7f8793e4)
![1724402196573](https://github.com/user-attachments/assets/1001a38f-9a6c-4c10-94b2-431f45896ee7)

**Comment by liujingxing** [comment]
插件没问题，检查下哪里使用了kotlin 1.7.1版本，或者下载rxhttp demo尝试下能不能编译通过
