### ISSUE TITLE
跑不起来了了,大佬,最新稳定版的Android Studio

### ISSUE THREAD

**Issue by lydlovezjr** [liujingxing/rxhttp#505]
Failed to calculate the value of task ':rxhttp-converter:converter-serialization:compileJava' property 'javaCompiler'.
Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=8, vendor=any, implementation=vendor-specific} for WINDOWS on x86_64.
No locally installed toolchains match and toolchain download repositories have not been configured.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

**Comment by lydlovezjr** [comment]
怎么说,如何统一那,大佬

**Comment by liujingxing** [comment]
下载demo尝试吧
