### ISSUE TITLE
请教个问题，Kotlin语言下，不使用协程，如何使用RxHttp发起同步请求和异步请求？

### ISSUE THREAD

**Issue by pangli** [liujingxing/rxhttp#506]
请教个问题，Kotlin语言下，不使用协程，如何使用RxHttp发起同步请求和异步请求？

**Comment by liujingxing** [comment]
那就只能使用rxjava，详情点击[RxHttp 优雅的实现请求串行与并行](https://juejin.cn/post/6844903870074732551)

**Comment by pangli** [comment]
> 那就只能使用rxjava，详情点击[RxHttp 优雅的实现请求串行与并行](https://juejin.cn/post/6844903870074732551)

嗯，因为我的项目整个是用Kotlin写的，不想再引用Rxjava，我还是用okhttp直接发起请求，对部分接口进行单独处理

**Comment by liujingxing** [comment]
简单问题不要复杂化，目前协程是最优解

**Comment by pangli** [comment]
> 简单问题不要复杂化，目前协程是最优解

因为适应协程的方式调用，我就需要在协程构建器中调用，因为我调用的地方是在一个后台服务中，不像在ViewMode或者Activity中可以获取viewModelScope或lifecycleScope协程构建器，需要我自己构建一个来自行处理回收等逻辑
