### ISSUE TITLE
遇到一个问题

### ISSUE THREAD

**Issue by hanxiaomeme** [liujingxing/rxhttp#509]
老项目使用的是 kapt 'com.ljx.rxhttp:rxhttp-compiler:2.5.1' & implementation 'com.ljx.rxhttp:rxhttp:2.5.1',但是由于JCenter仓库被关闭,无法下载依赖,请问有什么方法,可以快速的解决问题

**Comment by liujingxing** [comment]
升级至2.6.0及以上版本

**Comment by hanxiaomeme** [comment]
> 升级至2.6.0及以上版，如下
> 
> ```
> com.liujingxing.rxhttp:rxhttp:3.3.0
> com.liujingxing.rxhttp:rxhttp-compiler:3.3.0
> ```

升级的话 就要修改代码了,主要是老项目了,结构不想再去动了,有没有其他的源还能拉到当时的代码?

**Comment by liujingxing** [comment]
去看更新日志，2.6.0是离你最近的版本，应该改动不大

**Comment by hanxiaomeme** [comment]
> 去看更新日志，2.6.0是离你最近的版本，应该改动不大

我试了3.0以下都是not found....不然我也不会提了

**Comment by liujingxing** [comment]
那就是你自己哪里遗漏了，2.6.0及以上在jitpack上，再去看看接入文档
