### ISSUE TITLE
下载进度回调问题

### ISSUE THREAD

**Issue by SanJie-Lang** [liujingxing/rxhttp#510]
最新版本下载回调进度不能实时回调，仅回调一次100%，是不是哪里配置问题？
onMainProgress 方法使用默认的500毫秒更新进度
![image](https://github.com/user-attachments/assets/ec256443-f81a-43df-b67e-53757e1a7e9b)

**Comment by liujingxing** [comment]
猜你添加了日志拦截器，取消就好

**Comment by SanJie-Lang** [comment]
> 猜你添加了日志拦截器，取消就好

好的，谢谢！确实时添加了一个登录拦截器处理了response，处理一下就好了
