### ISSUE TITLE
新版本3.3.0http返回xml就回调到onFailure 里面了 但是xml是正常数据正常返回的

### ISSUE THREAD

**Issue by 1226362423** [liujingxing/rxhttp#511]
<?xml version="1.0" encoding="UTF-8"?><wfs:TransactionResponse xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="htt

**Comment by 1226362423** [comment]
RxHttp.postBody()
                .setBody(wfsBody, Param.HTTP_CONTENT_TYPE.toMediaType())
                .toAwaitString()
                .awaitResult {
                    
                }
                .onFailure {
                   
                }

**Comment by liujingxing** [comment]
贴出返回数据及日志

**Comment by 1226362423** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<wfs:TransactionResponse
    xmlns:xs=""
    xmlns:wfs="http://www.opengis.net/wfs"
    xmlns:gml="http://www.opengis.net/gml"
    xmlns:ogc="http://www.opengis.net/ogc"
    xmlns:ows="http://www.opengis.net/ows"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:xsi="" version="1.1.0" xsi:schemaLocation="">
    <wfs:TransactionSummary>
        <wfs:totalInserted>0</wfs:totalInserted>
        <wfs:totalUpdated>1</wfs:totalUpdated>
        <wfs:totalDeleted>0</wfs:totalDeleted>
    </wfs:TransactionSummary>
    <wfs:TransactionResults/>
    <wfs:InsertResults>
        <wfs:Feature>
            <ogc:FeatureId fid="none"/>
        </wfs:Feature>
    </wfs:InsertResults>
</wfs:TransactionResponse>

**Comment by liujingxing** [comment]
贴上日志，看看啥异常

**Comment by 1226362423** [comment]
3.2.7没问题 3.3.0有问题 代码没动 

<img width="1359" alt="image" src="https://github.com/user-attachments/assets/0342e0d2-ffb8-4d8d-9465-2adbaed7d339">

**Comment by liujingxing** [comment]
看了下，是有问题，3.3.0版本改一个需求引起的，这样看来，应该是要还原回去

**Comment by liujingxing** [comment]
[v3.3.1版本已更新](https://github.com/liujingxing/rxhttp/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)
