### ISSUE TITLE
请求头参数值前面的空格是框架自动加入的吗

### ISSUE THREAD

**Issue by 1226362423** [liujingxing/rxhttp#512]
通过在application当中加入的公共header 
header当中的参数值前面都加了一个空格 这个没有必要吧？好像http协议也没必要说加入空格吧 这个导致服务器识别不了 空格这个自己去处理又麻烦 得加拦截器

以下是gpt的解答：
<img width="805" alt="image" src="https://github.com/user-attachments/assets/e3c06611-8446-4580-941e-b0b9accf258b">
<img width="814" alt="image" src="https://github.com/user-attachments/assets/a68e0e94-8fb7-48a7-9dcd-cdd5bb00e8ae">

**Comment by liujingxing** [comment]
哪里看出加空格了？日志？为了美观，日志打印时会添加空格
