### ISSUE TITLE
Could not find com.ljx.rxhttp:rxhttp-compiler:2.3.5?

### ISSUE THREAD

**Issue by sujiewen** [liujingxing/rxhttp#515]
Could not determine the dependencies of task ':app:compileReleaseHttpJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:releaseHttpAnnotationProcessorClasspath'.
   > Could not find com.ljx.rxhttp:rxhttp-compiler:2.3.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/ljx/rxhttp/rxhttp-compiler/2.3.5/rxhttp-compiler-2.3.5.pom
       - https://jcenter.bintray.com/com/ljx/rxhttp/rxhttp-compiler/2.3.5/rxhttp-compiler-2.3.5.pom
       - https://jitpack.io/com/ljx/rxhttp/rxhttp-compiler/2.3.5/rxhttp-compiler-2.3.5.pom
     Required by:
         project :app

**Comment by liujingxing** [comment]
2.6.0及以上版本在jitpack上，之前版本在jcenter上，由于jcenter老早不维护了，所以2.3.5版本下载不了，请升级版本

**Comment by sujiewen** [comment]
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugAnnotationProcessorClasspath'.
   > Could not find com.ljx.rxhttp:rxhttp-compiler:2.9.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/ljx/rxhttp/rxhttp-compiler/2.9.5/rxhttp-compiler-2.9.5.pom
       - https://jcenter.bintray.com/com/ljx/rxhttp/rxhttp-compiler/2.9.5/rxhttp-compiler-2.9.5.pom
       - https://jitpack.io/com/ljx/rxhttp/rxhttp-compiler/2.9.5/rxhttp-compiler-2.9.5.pom
     Required by:
         project :app

**Comment by sujiewen** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply from: "config.gradle"

println("根build.gradle 开始配置")
buildscript {
    repositories {
        google()
        jcenter()
        //添加
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.3.0'
        classpath 'com.tencent.bugly:symtabfileuploader:latest.release'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
println("根build.gradle 配置完成")

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://jitpack.io'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}




apply plugin: 'com.android.application'
。。。。

dependencies {
    annotationProcessor "com.ljx.rxhttp:rxhttp-compiler:${versionConfig.rxhttp_version}"
}

我是不是build.gradle还要修改什么？

**Comment by liujingxing** [comment]
注意路径，2.6.0版本起是   com.liujingxing.rxhttp
