### ISSUE TITLE
多模块下有个奇怪的问题

### ISSUE THREAD

**Issue by tanzhihao1qaz** [liujingxing/rxhttp#516]
B,C模块都依赖的RxHttp，也有各自的初始化，然后主项目A依赖了B,C；之所以有各自的初始化，是因为各自的加解密是不一样。奇怪的现象来了，当A调用B的接口时，居然触发了C的拦截器，B,C两个模块是独立的，而且我已经在gradle里区分了两个模块的RxHttp类生成位置

**Comment by tanzhihao1qaz** [comment]
同样如果B,C都有设置setResultDecoder，调用B接口时却会触发C的ResultDecoder

**Comment by liujingxing** [comment]
这是正常的，RxHttp类可以有多个，但RxHttp的核心只有一个，它是单例的

**Comment by liujingxing** [comment]
Base module依赖rxhttp，其他module依赖base

**Comment by tanzhihao1qaz** [comment]
> Base module依赖rxhttp，其他module依赖base
这种就是上面提到的代码是自己写还可以这样抽出来，但要用别人（第三方）封装好的框架（他也用到了rxhttp），那是不是没法子了？

**Comment by tanzhihao1qaz** [comment]
> Base module依赖rxhttp，其他module依赖base

这种就是上面提到的代码是自己写还可以这样抽出来，但要用别人（第三方）封装好的框架（他也用到了rxhttp），那是不是没法子了？

**Comment by liujingxing** [comment]
偏离话题了，即使别人再次封装，也会提供初始化方法，对于解密需求，建议使用拦截器去实现

**Comment by tanzhihao1qaz** [comment]
> 偏离话题了，即使别人再次封装，也会提供初始化方法，对于解密需求，建议使用拦截器去实现

哇，谢谢大佬指点，瞬间明白了
