### ISSUE TITLE
要是能在纯Kotlin项目下运行就好了

### ISSUE THREAD

**Issue by artillerymans** [liujingxing/rxhttp#518]
现在导入后发现还有
import android.content.Context
import android.net.Uri
等的引用
按道理来说网络库不应该(我自己的理解)

**Comment by liujingxing** [comment]
声明非android 平台就好，如下：
```gradle
ksp {
    arg("rxhttp_android_platform", "false") //默认true
}
//或
kapt {
    arguments {
        arg("rxhttp_android_platform", "false")  //默认true
    }
}
```

**Comment by artillerymans** [comment]
> 声明非android 平台就好，如下：
> 
> ```groovy-gradle
> ksp {
>     arg("rxhttp_android_platform", "false") //默认true
> }
> //或
> kapt {
>     arguments {
>         arg("rxhttp_android_platform", "false")  //默认true
>     }
> }
> ```

@liujingxing 完美,谢谢老哥
