### ISSUE TITLE
设置公共参数问题

### ISSUE THREAD

**Issue by jielundewode** [liujingxing/RxHttp#6]
简单看了下您的代码，设置公共参数时是覆盖上一次的设置的，能不能增加一个api，改为追加上一次的设置

**Comment by liujingxing** [comment]
设置公共参数，就是追加，不是覆盖，除非你追加的参数key一样，就会覆盖。Param内部的参数通过Map存储的

**Comment by jielundewode** [comment]
大神，我的Rxhttp类一直无法生成，测试用的是kotlin，配置如下：
`implementation 'com.rxjava.rxhttp:rxhttp:1.0.2'
    //注解处理器，生成RxHttp类，即可一条链发送请求
    kapt 'com.rxjava.rxhttp:rxhttp-compiler:1.0.2'`

**Comment by jielundewode** [comment]
添加domin注解后可以用了，建议大神再介绍中写清楚，避免大家走弯路

**Comment by liujingxing** [comment]
真不好意思，刚开始写作不久，以后会注意。
