### ISSUE TITLE
如图

### ISSUE THREAD

**Issue by jielundewode** [liujingxing/RxHttp#7]
![TIM截图20190429093310](https://user-images.githubusercontent.com/10189846/56873064-3e88c200-6a62-11e9-9705-3dae9a74fc59.png)

**Comment by jielundewode** [comment]
出现这个问题时需要将项目Java的编译版本设为1.8
`    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }`

**Comment by liujingxing** [comment]
是的，这个被我遗忘了。RxHttp内部使用的就是Java 8
