### ISSUE TITLE
请问怎么支持泛型,比如Result里的data字段是个泛型, 该怎么写

### ISSUE THREAD

**Issue by twangithub** [liujingxing/RxHttp#9]

**Comment by liujingxing** [comment]
https://juejin.im/post/5cc095b7f265da0379417be0  数据解析器  ，您先看看。有问题我再为您解答。  另外，我想问下，您是从哪个平台了解到RxHttp的？

**Comment by liujingxing** [comment]
欢迎加群交流  378530627

**Comment by twangithub** [comment]
谢谢回答,我知道怎么用, 但希望类似Result这种的可以提供一个api. 不过自己封装也很快.

**Comment by liujingxing** [comment]
有提供的，可以使用SimpleParser解析器，如：.from(new SimpleParser<Response<Student>>(){})

**Comment by liujingxing** [comment]
有提供的，如：.from(new SimpleParser<Response<Student>>(){})

**Comment by liujingxing** [comment]
有提供的，如：`.from(new SimpleParser<Response<Student>>(){})`

**Comment by twangithub** [comment]
好的

**Comment by liujingxing** [comment]
可以问下，您是从哪个平台了解到RxHttp的吗？

**Comment by twangithub** [comment]
我很早就知道了, 今早刘皇叔推送你的库, 然后我特地来验证了一下文件上传, 哈哈
